Shader "KriptoFX/ME/LightningParticles" {
	Properties {
		[HDR] _TintColor ("Tint Color", Vector) = (0.5,0.5,0.5,0.5)
		_MainTex ("Main Texture", 2D) = "white" {}
		_DistortTex1 ("Distort Texture1", 2D) = "white" {}
		_DistortTex2 ("Distort Texture2", 2D) = "white" {}
		_DistortSpeed ("Distort Speed Scale (xy/zw)", Vector) = (1,0.1,1,0.1)
		_Offset ("Offset", Float) = 0
		_UseVelocity ("UseVelocity", Range(0, 1)) = 0
	}
	SubShader {
		Tags { "IGNOREPROJECTOR" = "true" "QUEUE" = "Transparent" "RenderType" = "Transparent" }
		Pass {
			Tags { "IGNOREPROJECTOR" = "true" "QUEUE" = "Transparent" "RenderType" = "Transparent" }
			Blend SrcAlpha One, SrcAlpha One
			ZWrite Off
			Cull Off
			GpuProgramID 48606
			Program "vp" {
				SubProgram "d3d11 " {
					"!!vs_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyzw
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xy          2     NONE   float   xy  
					// TEXCOORD                 1   xyz         3     NONE   float   xyz 
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xy          2     NONE   float   xy  
					// TEXCOORD                 2     z         2     NONE   float     z 
					// TEXCOORD                 1   xyzw        3     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[9], immediateIndexed
					dcl_constantbuffer CB1[1], immediateIndexed
					dcl_constantbuffer CB2[4], immediateIndexed
					dcl_constantbuffer CB3[21], immediateIndexed
					dcl_input v0.xyzw
					dcl_input v1.xyzw
					dcl_input v2.xy
					dcl_input v3.xyz
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xy
					dcl_output o2.z
					dcl_output o3.xyzw
					dcl_temps 3
					mul r0.xyzw, v0.yyyy, cb2[1].xyzw
					mad r0.xyzw, cb2[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb2[2].xyzw, v0.zzzz, r0.xyzw
					add r1.xyzw, r0.xyzw, cb2[3].xyzw
					mad r0.xy, cb2[3].xyxx, v0.wwww, r0.xyxx
					mul r2.xyzw, r1.yyyy, cb3[18].xyzw
					mad r2.xyzw, cb3[17].xyzw, r1.xxxx, r2.xyzw
					mad r2.xyzw, cb3[19].xyzw, r1.zzzz, r2.xyzw
					mad o0.xyzw, cb3[20].xyzw, r1.wwww, r2.xyzw
					mov o1.xyzw, v1.xyzw
					dp3 r0.z, v3.xyzx, v3.xyzx
					sqrt r0.z, r0.z
					add r0.w, -r0.z, cb1[0].x
					mad o2.z, cb0[5].y, r0.w, r0.z
					mad o2.xy, v2.xyxx, cb0[6].xyxx, cb0[6].zwzz
					mad o3.xy, r0.xyxx, cb0[7].xyxx, cb0[7].zwzz
					mad o3.zw, r0.xxxy, cb0[8].xxxy, cb0[8].zzzw
					ret 
					// Approximately 0 instruction slots used"
				}
			}
			Program "fp" {
				SubProgram "d3d11 " {
					"!!ps_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// COLOR                    0   xyzw        1     NONE   float      w
					// TEXCOORD                 0   xy          2     NONE   float   xy  
					// TEXCOORD                 2     z         2     NONE   float     z 
					// TEXCOORD                 1   xyzw        3     NONE   float   xyzw
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[6], immediateIndexed
					dcl_constantbuffer CB1[1], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_sampler s1, mode_default
					dcl_sampler s2, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_resource_texture2d (float,float,float,float) t1
					dcl_resource_texture2d (float,float,float,float) t2
					dcl_input_ps linear v1.w
					dcl_input_ps linear v2.xy
					dcl_input_ps linear v2.z
					dcl_input_ps linear v3.xyzw
					dcl_output o0.xyzw
					dcl_temps 3
					mul r0.x, cb1[0].x, l(5.000000)
					mad r0.xy, v2.xyxx, l(7.000000, 7.000000, 0.000000, 0.000000), r0.xxxx
					sample r0.xyzw, r0.xyxx, t2.xyzw, s0
					add r0.x, -r0.z, v1.w
					lt r0.x, r0.x, l(0.000000)
					discard_nz r0.x
					mul r0.xyzw, v2.zzzz, cb0[4].xxzz
					mad r0.xyzw, -r0.xyzw, l(1.400000, 1.400000, 1.250000, 1.250000), v3.xyzw
					add r0.xyzw, r0.xyzw, l(0.400000, 0.600000, 0.300000, 0.700000)
					sample r1.xyzw, r0.zwzz, t1.xyzw, s2
					sample r0.xyzw, r0.xyxx, t0.xyzw, s1
					mad r0.xy, r0.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
					mad r0.zw, r1.xxxy, l(0.000000, 0.000000, 2.000000, 2.000000), l(0.000000, 0.000000, -1.000000, -1.000000)
					mad r1.xyzw, cb0[4].xxzz, v2.zzzz, v3.xyzw
					sample r2.xyzw, r1.zwzz, t1.xyzw, s2
					sample r1.xyzw, r1.xyxx, t0.xyzw, s1
					mad r1.xy, r1.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
					add r0.xy, r0.xyxx, r1.xyxx
					mad r1.xy, r2.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
					add r0.zw, r0.zzzw, r1.xxxy
					mul r0.xyzw, r0.xyzw, cb0[4].yyww
					sample r1.xyzw, v2.xyxx, t2.xyzw, s0
					add_sat r1.x, r1.y, cb0[5].x
					mad r0.xy, r0.xyxx, r1.xxxx, v2.xyxx
					mad r0.xy, r0.zwzz, r1.xxxx, r0.xyxx
					sample r0.xyzw, r0.xyxx, t2.xyzw, s0
					add r1.xyzw, cb0[2].xyzw, cb0[2].xyzw
					mul r0.xyzw, r0.xxxx, r1.xyzw
					mul o0.xyzw, r0.xyzw, v1.wwww
					ret 
					// Approximately 0 instruction slots used"
				}
			}
		}
	}
}