Shader "KriptoFX/ME/DistortionMobile" {
	Properties {
		[Header(Main Settings)] [Toggle(USE_MAINTEX)] _UseMainTex ("Use Main Texture", Float) = 0
		[HDR] _TintColor ("Tint Color", Vector) = (1,1,1,1)
		_MainTex ("Main Texture", 2D) = "black" {}
		[Header(Height Settings)] [Normal] _NormalTex ("Normal(RG) Alpha(A)", 2D) = "bump" {}
		[HDR] _MainColor ("Main Color", Vector) = (1,1,1,1)
		_Distortion ("Distortion", Float) = 100
		[Toggle(USE_REFRACTIVE)] _UseRefractive ("Use Refractive Distort", Float) = 0
		_RefractiveStrength ("Refractive Strength", Range(-1, 1)) = 0
		[Toggle(USE_SOFT_PARTICLES)] _UseSoft ("Use Soft Particles", Float) = 0
		_InvFade ("Soft Particles Factor", Float) = 3
		[Space] [Header(Height Settings)] [Toggle(USE_HEIGHT)] _UseHeight ("Use Height Map", Float) = 0
		_HeightTex ("Height Tex", 2D) = "white" {}
		_Height ("_Height", Float) = 0.1
		_HeightUVScrollDistort ("Height UV Scroll(XY)", Vector) = (8,12,0,0)
		[Space] [Header(Fresnel)] [Toggle(USE_FRESNEL)] _UseFresnel ("Use Fresnel", Float) = 0
		[HDR] _FresnelColor ("Fresnel Color", Vector) = (0.5,0.5,0.5,1)
		_FresnelPow ("Fresnel Pow", Float) = 5
		_FresnelR0 ("Fresnel R0", Float) = 0.04
		_FresnelDistort ("Fresnel Distort", Float) = 1500
		[Space] [Header(Cutout)] [Toggle(USE_CUTOUT)] _UseCutout ("Use Cutout", Float) = 0
		_CutoutTex ("Cutout Tex", 2D) = "white" {}
		_Cutout ("Cutout", Range(0, 1)) = 1
		[HDR] _CutoutColor ("Cutout Color", Vector) = (1,1,1,1)
		_CutoutThreshold ("Cutout Threshold", Range(0, 1)) = 0.015
		[Space] [Header(Rendering)] [Toggle] _ZWriteMode ("ZWrite On?", Float) = 0
		[Enum(Off,0,Front,1,Back,2)] _CullMode ("Culling", Float) = 2
		[Toggle(USE_ALPHA_CLIPING)] _UseAlphaCliping ("Use Alpha Cliping", Float) = 0
		_AlphaClip ("Alpha Clip Threshold", Float) = 10
		[Toggle(USE_BLENDING)] _UseBlending ("Use Blending", Float) = 0
	}
	SubShader {
		LOD 100
		Tags { "IGNOREPROJECTOR" = "true" "QUEUE" = "Transparent" "RenderType" = "Transparent" }
		Pass {
			LOD 100
			Tags { "IGNOREPROJECTOR" = "true" "QUEUE" = "Transparent" "RenderType" = "Transparent" }
			Blend SrcAlpha OneMinusSrcAlpha, SrcAlpha OneMinusSrcAlpha
			ZWrite Off
			Cull Off
			Offset -1, -1
			GpuProgramID 32979
			Program "vp" {
				SubProgram "d3d11 " {
					"!!vs_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xy          2     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xy          2     NONE   float   xy  
					// TEXCOORD                 2   xyzw        3     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[3], immediateIndexed
					dcl_constantbuffer CB1[4], immediateIndexed
					dcl_constantbuffer CB2[21], immediateIndexed
					dcl_input v0.xyz
					dcl_input v1.xyzw
					dcl_input v2.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xy
					dcl_output o3.xyzw
					dcl_temps 2
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					add r0.xyzw, r0.xyzw, cb1[3].xyzw
					mul r1.xyzw, r0.yyyy, cb2[18].xyzw
					mad r1.xyzw, cb2[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb2[19].xyzw, r0.zzzz, r1.xyzw
					mad r0.xyzw, cb2[20].xyzw, r0.wwww, r1.xyzw
					mov o0.xyzw, r0.xyzw
					mov o1.xyzw, v1.xyzw
					mad o2.xy, v2.xyxx, cb0[2].xyxx, cb0[2].zwzz
					mul r1.xyz, r0.xwyx, l(0.500000, 0.500000, -0.500000, 0.000000)
					mov o3.zw, r0.zzzw
					add o3.xy, r1.yyyy, r1.xzxx
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "SOFTPARTICLES_ON" "USE_FRESNEL" "USE_CUTOUT" "USE_MAINTEX" "USE_HEIGHT" }
					"!!vs_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyzw
					// NORMAL                   0   xyz         1     NONE   float   xyz 
					// COLOR                    0   xyzw        2     NONE   float   xyzw
					// TEXCOORD                 0   xy          3     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xy          2     NONE   float   xy  
					// TEXCOORD                 4     zw        2     NONE   float     zw
					// TEXCOORD                 2   xyzw        3     NONE   float   xyzw
					// TEXCOORD                 6   xy          4     NONE   float   xy  
					// TEXCOORD                 7   xyzw        5     NONE   float   xyzw
					// TEXCOORD                 8   xyz         6     NONE   float   xyz 
					//
					vs_4_0
					dcl_constantbuffer CB0[20], immediateIndexed
					dcl_constantbuffer CB1[5], immediateIndexed
					dcl_constantbuffer CB2[8], immediateIndexed
					dcl_constantbuffer CB3[21], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_input v0.xyzw
					dcl_input v1.xyz
					dcl_input v2.xyzw
					dcl_input v3.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xy
					dcl_output o2.zw
					dcl_output o3.xyzw
					dcl_output o4.xy
					dcl_output o5.xyzw
					dcl_output o6.xyz
					dcl_temps 3
					mad r0.xy, v3.xyxx, cb0[7].xyxx, cb0[7].zwzz
					mad r0.xy, cb1[0].xxxx, cb0[8].xyxx, r0.xyxx
					sample_l r0.xyzw, r0.xyxx, t0.xyzw, s0, l(0.000000)
					mul r1.xyz, v1.xyzx, cb0[9].xxxx
					mul r2.xyz, r1.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000)
					mad r0.xyz, r1.xyzx, r0.xyzx, -r2.xyzx
					add r0.xyz, r0.xyzx, v0.xyzx
					mul r1.xyzw, r0.yyyy, cb2[1].xyzw
					mad r1.xyzw, cb2[0].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb2[2].xyzw, r0.zzzz, r1.xyzw
					add r1.xyzw, r1.xyzw, cb2[3].xyzw
					mul r2.xyzw, r1.yyyy, cb3[18].xyzw
					mad r2.xyzw, cb3[17].xyzw, r1.xxxx, r2.xyzw
					mad r2.xyzw, cb3[19].xyzw, r1.zzzz, r2.xyzw
					mad r1.xyzw, cb3[20].xyzw, r1.wwww, r2.xyzw
					mov o0.xyzw, r1.xyzw
					mov o1.xyzw, v2.xyzw
					mul r2.xy, r0.yyyy, cb0[17].xzxx
					mad r2.xy, cb0[16].xzxx, r0.xxxx, r2.xyxx
					mad r2.xy, cb0[18].xzxx, r0.zzzz, r2.xyxx
					add r2.xy, r2.xyxx, cb0[19].xzxx
					add r2.xy, r2.xyxx, l(-0.500000, -0.500000, 0.000000, 0.000000)
					mad o2.zw, r2.xxxy, cb0[12].xxxy, cb0[12].zzzw
					mad r2.xy, v3.xyxx, cb0[2].xyxx, cb0[2].zwzz
					mad o2.xy, cb1[0].xxxx, cb0[8].xyxx, r2.xyxx
					mul r2.xyz, r1.xwyx, l(0.500000, 0.500000, -0.500000, 0.000000)
					mov o3.zw, r1.zzzw
					add o3.xy, r2.yyyy, r2.xzxx
					mad r1.xy, v3.xyxx, cb0[3].xyxx, cb0[3].zwzz
					mad o4.xy, cb1[0].xxxx, cb0[8].xyxx, r1.xyxx
					mov o5.xyz, r0.xyzx
					mov o5.w, v0.w
					mul r1.xyz, cb1[4].yyyy, cb2[5].xyzx
					mad r1.xyz, cb2[4].xyzx, cb1[4].xxxx, r1.xyzx
					mad r1.xyz, cb2[6].xyzx, cb1[4].zzzz, r1.xyzx
					add r1.xyz, r1.xyzx, cb2[7].xyzx
					add r0.xyz, -r0.xyzx, r1.xyzx
					dp3 r0.w, r0.xyzx, r0.xyzx
					rsq r0.w, r0.w
					mul o6.xyz, r0.wwww, r0.xyzx
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "SOFTPARTICLES_ON" }
					"!!vs_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xy          2     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xy          2     NONE   float   xy  
					// TEXCOORD                 2   xyzw        3     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[3], immediateIndexed
					dcl_constantbuffer CB1[4], immediateIndexed
					dcl_constantbuffer CB2[21], immediateIndexed
					dcl_input v0.xyz
					dcl_input v1.xyzw
					dcl_input v2.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xy
					dcl_output o3.xyzw
					dcl_temps 2
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					add r0.xyzw, r0.xyzw, cb1[3].xyzw
					mul r1.xyzw, r0.yyyy, cb2[18].xyzw
					mad r1.xyzw, cb2[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb2[19].xyzw, r0.zzzz, r1.xyzw
					mad r0.xyzw, cb2[20].xyzw, r0.wwww, r1.xyzw
					mov o0.xyzw, r0.xyzw
					mov o1.xyzw, v1.xyzw
					mad o2.xy, v2.xyxx, cb0[2].xyxx, cb0[2].zwzz
					mul r1.xyz, r0.xwyx, l(0.500000, 0.500000, -0.500000, 0.000000)
					mov o3.zw, r0.zzzw
					add o3.xy, r1.yyyy, r1.xzxx
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "USE_FRESNEL" "USE_CUTOUT" "USE_MAINTEX" "USE_HEIGHT" }
					"!!vs_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyzw
					// NORMAL                   0   xyz         1     NONE   float   xyz 
					// COLOR                    0   xyzw        2     NONE   float   xyzw
					// TEXCOORD                 0   xy          3     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xy          2     NONE   float   xy  
					// TEXCOORD                 4     zw        2     NONE   float     zw
					// TEXCOORD                 2   xyzw        3     NONE   float   xyzw
					// TEXCOORD                 6   xy          4     NONE   float   xy  
					// TEXCOORD                 7   xyzw        5     NONE   float   xyzw
					// TEXCOORD                 8   xyz         6     NONE   float   xyz 
					//
					vs_4_0
					dcl_constantbuffer CB0[20], immediateIndexed
					dcl_constantbuffer CB1[5], immediateIndexed
					dcl_constantbuffer CB2[8], immediateIndexed
					dcl_constantbuffer CB3[21], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_input v0.xyzw
					dcl_input v1.xyz
					dcl_input v2.xyzw
					dcl_input v3.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xy
					dcl_output o2.zw
					dcl_output o3.xyzw
					dcl_output o4.xy
					dcl_output o5.xyzw
					dcl_output o6.xyz
					dcl_temps 3
					mad r0.xy, v3.xyxx, cb0[7].xyxx, cb0[7].zwzz
					mad r0.xy, cb1[0].xxxx, cb0[8].xyxx, r0.xyxx
					sample_l r0.xyzw, r0.xyxx, t0.xyzw, s0, l(0.000000)
					mul r1.xyz, v1.xyzx, cb0[9].xxxx
					mul r2.xyz, r1.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000)
					mad r0.xyz, r1.xyzx, r0.xyzx, -r2.xyzx
					add r0.xyz, r0.xyzx, v0.xyzx
					mul r1.xyzw, r0.yyyy, cb2[1].xyzw
					mad r1.xyzw, cb2[0].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb2[2].xyzw, r0.zzzz, r1.xyzw
					add r1.xyzw, r1.xyzw, cb2[3].xyzw
					mul r2.xyzw, r1.yyyy, cb3[18].xyzw
					mad r2.xyzw, cb3[17].xyzw, r1.xxxx, r2.xyzw
					mad r2.xyzw, cb3[19].xyzw, r1.zzzz, r2.xyzw
					mad r1.xyzw, cb3[20].xyzw, r1.wwww, r2.xyzw
					mov o0.xyzw, r1.xyzw
					mov o1.xyzw, v2.xyzw
					mul r2.xy, r0.yyyy, cb0[17].xzxx
					mad r2.xy, cb0[16].xzxx, r0.xxxx, r2.xyxx
					mad r2.xy, cb0[18].xzxx, r0.zzzz, r2.xyxx
					add r2.xy, r2.xyxx, cb0[19].xzxx
					add r2.xy, r2.xyxx, l(-0.500000, -0.500000, 0.000000, 0.000000)
					mad o2.zw, r2.xxxy, cb0[12].xxxy, cb0[12].zzzw
					mad r2.xy, v3.xyxx, cb0[2].xyxx, cb0[2].zwzz
					mad o2.xy, cb1[0].xxxx, cb0[8].xyxx, r2.xyxx
					mul r2.xyz, r1.xwyx, l(0.500000, 0.500000, -0.500000, 0.000000)
					mov o3.zw, r1.zzzw
					add o3.xy, r2.yyyy, r2.xzxx
					mad r1.xy, v3.xyxx, cb0[3].xyxx, cb0[3].zwzz
					mad o4.xy, cb1[0].xxxx, cb0[8].xyxx, r1.xyxx
					mov o5.xyz, r0.xyzx
					mov o5.w, v0.w
					mul r1.xyz, cb1[4].yyyy, cb2[5].xyzx
					mad r1.xyz, cb2[4].xyzx, cb1[4].xxxx, r1.xyzx
					mad r1.xyz, cb2[6].xyzx, cb1[4].zzzz, r1.xyzx
					add r1.xyz, r1.xyzx, cb2[7].xyzx
					add r0.xyz, -r0.xyzx, r1.xyzx
					dp3 r0.w, r0.xyzx, r0.xyzx
					rsq r0.w, r0.w
					mul o6.xyz, r0.wwww, r0.xyzx
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "DISTORT_OFF" }
					"!!vs_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xy          2     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xy          2     NONE   float   xy  
					// TEXCOORD                 2   xyzw        3     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[3], immediateIndexed
					dcl_constantbuffer CB1[4], immediateIndexed
					dcl_constantbuffer CB2[21], immediateIndexed
					dcl_input v0.xyz
					dcl_input v1.xyzw
					dcl_input v2.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xy
					dcl_output o3.xyzw
					dcl_temps 2
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					add r0.xyzw, r0.xyzw, cb1[3].xyzw
					mul r1.xyzw, r0.yyyy, cb2[18].xyzw
					mad r1.xyzw, cb2[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb2[19].xyzw, r0.zzzz, r1.xyzw
					mad r0.xyzw, cb2[20].xyzw, r0.wwww, r1.xyzw
					mov o0.xyzw, r0.xyzw
					mov o1.xyzw, v1.xyzw
					mad o2.xy, v2.xyxx, cb0[2].xyxx, cb0[2].zwzz
					mul r1.xyz, r0.xwyx, l(0.500000, 0.500000, -0.500000, 0.000000)
					mov o3.zw, r0.zzzw
					add o3.xy, r1.yyyy, r1.xzxx
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "SOFTPARTICLES_ON" "USE_FRESNEL" "USE_CUTOUT" "DISTORT_OFF" "USE_MAINTEX" "USE_HEIGHT" }
					"!!vs_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyzw
					// NORMAL                   0   xyz         1     NONE   float   xyz 
					// COLOR                    0   xyzw        2     NONE   float   xyzw
					// TEXCOORD                 0   xy          3     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xy          2     NONE   float   xy  
					// TEXCOORD                 4     zw        2     NONE   float     zw
					// TEXCOORD                 2   xyzw        3     NONE   float   xyzw
					// TEXCOORD                 6   xy          4     NONE   float   xy  
					// TEXCOORD                 7   xyzw        5     NONE   float   xyzw
					// TEXCOORD                 8   xyz         6     NONE   float   xyz 
					//
					vs_4_0
					dcl_constantbuffer CB0[20], immediateIndexed
					dcl_constantbuffer CB1[5], immediateIndexed
					dcl_constantbuffer CB2[8], immediateIndexed
					dcl_constantbuffer CB3[21], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_input v0.xyzw
					dcl_input v1.xyz
					dcl_input v2.xyzw
					dcl_input v3.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xy
					dcl_output o2.zw
					dcl_output o3.xyzw
					dcl_output o4.xy
					dcl_output o5.xyzw
					dcl_output o6.xyz
					dcl_temps 3
					mad r0.xy, v3.xyxx, cb0[7].xyxx, cb0[7].zwzz
					mad r0.xy, cb1[0].xxxx, cb0[8].xyxx, r0.xyxx
					sample_l r0.xyzw, r0.xyxx, t0.xyzw, s0, l(0.000000)
					mul r1.xyz, v1.xyzx, cb0[9].xxxx
					mul r2.xyz, r1.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000)
					mad r0.xyz, r1.xyzx, r0.xyzx, -r2.xyzx
					add r0.xyz, r0.xyzx, v0.xyzx
					mul r1.xyzw, r0.yyyy, cb2[1].xyzw
					mad r1.xyzw, cb2[0].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb2[2].xyzw, r0.zzzz, r1.xyzw
					add r1.xyzw, r1.xyzw, cb2[3].xyzw
					mul r2.xyzw, r1.yyyy, cb3[18].xyzw
					mad r2.xyzw, cb3[17].xyzw, r1.xxxx, r2.xyzw
					mad r2.xyzw, cb3[19].xyzw, r1.zzzz, r2.xyzw
					mad r1.xyzw, cb3[20].xyzw, r1.wwww, r2.xyzw
					mov o0.xyzw, r1.xyzw
					mov o1.xyzw, v2.xyzw
					mul r2.xy, r0.yyyy, cb0[17].xzxx
					mad r2.xy, cb0[16].xzxx, r0.xxxx, r2.xyxx
					mad r2.xy, cb0[18].xzxx, r0.zzzz, r2.xyxx
					add r2.xy, r2.xyxx, cb0[19].xzxx
					add r2.xy, r2.xyxx, l(-0.500000, -0.500000, 0.000000, 0.000000)
					mad o2.zw, r2.xxxy, cb0[12].xxxy, cb0[12].zzzw
					mad r2.xy, v3.xyxx, cb0[2].xyxx, cb0[2].zwzz
					mad o2.xy, cb1[0].xxxx, cb0[8].xyxx, r2.xyxx
					mul r2.xyz, r1.xwyx, l(0.500000, 0.500000, -0.500000, 0.000000)
					mov o3.zw, r1.zzzw
					add o3.xy, r2.yyyy, r2.xzxx
					mad r1.xy, v3.xyxx, cb0[3].xyxx, cb0[3].zwzz
					mad o4.xy, cb1[0].xxxx, cb0[8].xyxx, r1.xyxx
					mov o5.xyz, r0.xyzx
					mov o5.w, v0.w
					mul r1.xyz, cb1[4].yyyy, cb2[5].xyzx
					mad r1.xyz, cb2[4].xyzx, cb1[4].xxxx, r1.xyzx
					mad r1.xyz, cb2[6].xyzx, cb1[4].zzzz, r1.xyzx
					add r1.xyz, r1.xyzx, cb2[7].xyzx
					add r0.xyz, -r0.xyzx, r1.xyzx
					dp3 r0.w, r0.xyzx, r0.xyzx
					rsq r0.w, r0.w
					mul o6.xyz, r0.wwww, r0.xyzx
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "SOFTPARTICLES_ON" "DISTORT_OFF" }
					"!!vs_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xy          2     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xy          2     NONE   float   xy  
					// TEXCOORD                 2   xyzw        3     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[3], immediateIndexed
					dcl_constantbuffer CB1[4], immediateIndexed
					dcl_constantbuffer CB2[21], immediateIndexed
					dcl_input v0.xyz
					dcl_input v1.xyzw
					dcl_input v2.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xy
					dcl_output o3.xyzw
					dcl_temps 2
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					add r0.xyzw, r0.xyzw, cb1[3].xyzw
					mul r1.xyzw, r0.yyyy, cb2[18].xyzw
					mad r1.xyzw, cb2[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb2[19].xyzw, r0.zzzz, r1.xyzw
					mad r0.xyzw, cb2[20].xyzw, r0.wwww, r1.xyzw
					mov o0.xyzw, r0.xyzw
					mov o1.xyzw, v1.xyzw
					mad o2.xy, v2.xyxx, cb0[2].xyxx, cb0[2].zwzz
					mul r1.xyz, r0.xwyx, l(0.500000, 0.500000, -0.500000, 0.000000)
					mov o3.zw, r0.zzzw
					add o3.xy, r1.yyyy, r1.xzxx
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "USE_FRESNEL" "USE_CUTOUT" "DISTORT_OFF" "USE_MAINTEX" "USE_HEIGHT" }
					"!!vs_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyzw
					// NORMAL                   0   xyz         1     NONE   float   xyz 
					// COLOR                    0   xyzw        2     NONE   float   xyzw
					// TEXCOORD                 0   xy          3     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xy          2     NONE   float   xy  
					// TEXCOORD                 4     zw        2     NONE   float     zw
					// TEXCOORD                 2   xyzw        3     NONE   float   xyzw
					// TEXCOORD                 6   xy          4     NONE   float   xy  
					// TEXCOORD                 7   xyzw        5     NONE   float   xyzw
					// TEXCOORD                 8   xyz         6     NONE   float   xyz 
					//
					vs_4_0
					dcl_constantbuffer CB0[20], immediateIndexed
					dcl_constantbuffer CB1[5], immediateIndexed
					dcl_constantbuffer CB2[8], immediateIndexed
					dcl_constantbuffer CB3[21], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_input v0.xyzw
					dcl_input v1.xyz
					dcl_input v2.xyzw
					dcl_input v3.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xy
					dcl_output o2.zw
					dcl_output o3.xyzw
					dcl_output o4.xy
					dcl_output o5.xyzw
					dcl_output o6.xyz
					dcl_temps 3
					mad r0.xy, v3.xyxx, cb0[7].xyxx, cb0[7].zwzz
					mad r0.xy, cb1[0].xxxx, cb0[8].xyxx, r0.xyxx
					sample_l r0.xyzw, r0.xyxx, t0.xyzw, s0, l(0.000000)
					mul r1.xyz, v1.xyzx, cb0[9].xxxx
					mul r2.xyz, r1.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000)
					mad r0.xyz, r1.xyzx, r0.xyzx, -r2.xyzx
					add r0.xyz, r0.xyzx, v0.xyzx
					mul r1.xyzw, r0.yyyy, cb2[1].xyzw
					mad r1.xyzw, cb2[0].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb2[2].xyzw, r0.zzzz, r1.xyzw
					add r1.xyzw, r1.xyzw, cb2[3].xyzw
					mul r2.xyzw, r1.yyyy, cb3[18].xyzw
					mad r2.xyzw, cb3[17].xyzw, r1.xxxx, r2.xyzw
					mad r2.xyzw, cb3[19].xyzw, r1.zzzz, r2.xyzw
					mad r1.xyzw, cb3[20].xyzw, r1.wwww, r2.xyzw
					mov o0.xyzw, r1.xyzw
					mov o1.xyzw, v2.xyzw
					mul r2.xy, r0.yyyy, cb0[17].xzxx
					mad r2.xy, cb0[16].xzxx, r0.xxxx, r2.xyxx
					mad r2.xy, cb0[18].xzxx, r0.zzzz, r2.xyxx
					add r2.xy, r2.xyxx, cb0[19].xzxx
					add r2.xy, r2.xyxx, l(-0.500000, -0.500000, 0.000000, 0.000000)
					mad o2.zw, r2.xxxy, cb0[12].xxxy, cb0[12].zzzw
					mad r2.xy, v3.xyxx, cb0[2].xyxx, cb0[2].zwzz
					mad o2.xy, cb1[0].xxxx, cb0[8].xyxx, r2.xyxx
					mul r2.xyz, r1.xwyx, l(0.500000, 0.500000, -0.500000, 0.000000)
					mov o3.zw, r1.zzzw
					add o3.xy, r2.yyyy, r2.xzxx
					mad r1.xy, v3.xyxx, cb0[3].xyxx, cb0[3].zwzz
					mad o4.xy, cb1[0].xxxx, cb0[8].xyxx, r1.xyxx
					mov o5.xyz, r0.xyzx
					mov o5.w, v0.w
					mul r1.xyz, cb1[4].yyyy, cb2[5].xyzx
					mad r1.xyz, cb2[4].xyzx, cb1[4].xxxx, r1.xyzx
					mad r1.xyz, cb2[6].xyzx, cb1[4].zzzz, r1.xyzx
					add r1.xyz, r1.xyzx, cb2[7].xyzx
					add r0.xyz, -r0.xyzx, r1.xyzx
					dp3 r0.w, r0.xyzx, r0.xyzx
					rsq r0.w, r0.w
					mul o6.xyz, r0.wwww, r0.xyzx
					ret 
					// Approximately 0 instruction slots used"
				}
			}
			Program "fp" {
				SubProgram "d3d11 " {
					"!!ps_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// COLOR                    0   xyzw        1     NONE   float      w
					// TEXCOORD                 0   xy          2     NONE   float   xy  
					// TEXCOORD                 2   xyzw        3     NONE   float   xy w
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[7], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_sampler s1, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_resource_texture2d (float,float,float,float) t1
					dcl_input_ps linear v1.w
					dcl_input_ps linear v2.xy
					dcl_input_ps linear v3.xyw
					dcl_output o0.xyzw
					dcl_temps 2
					sample r0.xyzw, v2.xyxx, t0.xyzw, s1
					mul r0.x, r0.w, r0.x
					mad r0.xy, r0.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
					mul r0.xy, r0.xyxx, cb0[6].xxxx
					mul r0.xy, r0.xyxx, v1.wwww
					mad r0.xy, r0.xyxx, l(0.001000, 0.001000, 0.000000, 0.000000), v3.xyxx
					div r0.xy, r0.xyxx, v3.wwww
					sample_l r0.xyzw, r0.xyxx, t1.xyzw, s0, l(0.000000)
					add r1.xyz, cb0[5].xyzx, l(-1.000000, -1.000000, -1.000000, 0.000000)
					mad r1.xyz, v1.wwww, r1.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
					mul o0.xyz, r0.xyzx, r1.xyzx
					mul r0.x, cb0[5].w, cb0[5].w
					mul_sat o0.w, r0.x, cb0[5].w
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "SOFTPARTICLES_ON" "USE_FRESNEL" "USE_CUTOUT" "USE_MAINTEX" "USE_HEIGHT" }
					"!!ps_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xy          2     NONE   float   xy  
					// TEXCOORD                 4     zw        2     NONE   float     zw
					// TEXCOORD                 2   xyzw        3     NONE   float   xy w
					// TEXCOORD                 6   xy          4     NONE   float   xy  
					// TEXCOORD                 7   xyzw        5     NONE   float   xyz 
					// TEXCOORD                 8   xyz         6     NONE   float   xyz 
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[16], immediateIndexed
					dcl_constantbuffer CB1[6], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_sampler s1, mode_default
					dcl_sampler s2, mode_default
					dcl_sampler s3, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_resource_texture2d (float,float,float,float) t1
					dcl_resource_texture2d (float,float,float,float) t2
					dcl_resource_texture2d (float,float,float,float) t3
					dcl_input_ps linear v1.xyzw
					dcl_input_ps linear v2.xy
					dcl_input_ps linear v2.zw
					dcl_input_ps linear v3.xyw
					dcl_input_ps linear v4.xy
					dcl_input_ps linear v5.xyz
					dcl_input_ps linear v6.xyz
					dcl_output o0.xyzw
					dcl_temps 5
					deriv_rty r0.xyz, v5.yzxy
					mul r0.xyz, r0.xyzx, cb1[5].xxxx
					deriv_rtx r1.xyz, v5.zxyz
					mul r2.xyz, r0.xyzx, r1.xyzx
					mad r0.xyz, r1.zxyz, r0.yzxy, -r2.xyzx
					dp3 r0.w, r0.xyzx, r0.xyzx
					rsq r0.w, r0.w
					mul r0.xyz, r0.wwww, r0.xyzx
					dp3 r0.x, r0.xyzx, v6.xyzx
					add r0.x, -r0.x, l(1.000000)
					log r0.x, r0.x
					mul r0.x, r0.x, cb0[11].x
					exp r0.x, r0.x
					add r0.y, -cb0[11].y, l(1.000000)
					mad_sat r0.x, r0.y, r0.x, cb0[11].y
					mul r0.y, r0.x, cb0[11].z
					mul r0.xzw, r0.xxxx, cb0[10].xxyz
					mul r0.y, r0.y, l(0.001000)
					sample r1.xyzw, v2.xyxx, t0.xyzw, s2
					mul r1.x, r1.w, r1.x
					mad r1.xy, r1.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
					mul r1.zw, r0.yyyy, r1.xxxy
					mul r2.xy, r1.xyxx, cb0[6].xxxx
					add r0.y, r1.y, r1.x
					mad r1.xy, r2.xyxx, l(0.001000, 0.001000, 0.000000, 0.000000), r1.zwzz
					mad r1.zw, r1.xxxy, v1.wwww, v3.xxxy
					div r1.xy, r1.xyxx, cb0[4].wwww
					add r1.xy, -r1.xyxx, v4.xyxx
					sample r2.xyzw, r1.xyxx, t3.xyzw, s1
					mul r2.xyz, r2.wwww, r2.xyzx
					mul r2.xyz, r2.xyzx, cb0[4].xyzx
					div r1.xy, r1.zwzz, v3.wwww
					sample_l r1.xyzw, r1.xyxx, t2.xyzw, s0, l(0.000000)
					mul r0.xzw, |r0.yyyy|, r0.xxzw
					mul r0.xzw, r0.xxzw, v1.xxyz
					mul r0.xzw, r0.xxzw, v1.wwww
					add r0.xzw, r0.xxzw, r0.xxzw
					mul r3.xyz, r1.xyzx, r0.xzwx
					dp3 r0.x, r0.xzwx, l(0.330000, 0.330000, 0.330000, 0.000000)
					mul_sat r0.x, r0.x, l(10.000000)
					add r4.xyz, cb0[5].xyzx, l(-1.000000, -1.000000, -1.000000, 0.000000)
					mad r4.xyz, v1.wwww, r4.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
					mad r1.xyz, r1.xyzx, r4.xyzx, r3.xyzx
					sample r3.xyzw, v2.zwzz, t1.xyzw, s3
					mad r0.y, -r0.y, l(0.100000), r3.x
					add r0.y, -r0.y, cb0[13].x
					ge r0.z, r0.y, l(0.000000)
					add r0.y, r0.y, cb0[15].x
					ge r0.y, r0.y, l(0.000000)
					and r0.y, r0.y, l(0x3f800000)
					movc r0.z, r0.z, l(-1.000000), l(-0.000000)
					add r0.z, r0.z, r0.y
					max r0.z, r0.z, l(0.000000)
					mad r1.xyz, cb0[14].xyzx, r0.zzzz, r1.xyzx
					mad o0.xyz, r2.xyzx, v1.wwww, r1.xyzx
					mul r0.z, r0.x, cb0[10].w
					mad r0.x, -r0.x, cb0[10].w, cb0[5].w
					mad r0.x, cb0[5].w, r0.x, r0.z
					log r0.z, cb0[13].x
					mul r0.z, r0.z, l(0.200000)
					exp r0.z, r0.z
					mul r0.y, r0.z, r0.y
					mul r0.x, r0.y, r0.x
					mul_sat o0.w, r0.x, cb0[5].w
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "SOFTPARTICLES_ON" }
					"!!ps_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// COLOR                    0   xyzw        1     NONE   float      w
					// TEXCOORD                 0   xy          2     NONE   float   xy  
					// TEXCOORD                 2   xyzw        3     NONE   float   xy w
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[7], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_sampler s1, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_resource_texture2d (float,float,float,float) t1
					dcl_input_ps linear v1.w
					dcl_input_ps linear v2.xy
					dcl_input_ps linear v3.xyw
					dcl_output o0.xyzw
					dcl_temps 2
					sample r0.xyzw, v2.xyxx, t0.xyzw, s1
					mul r0.x, r0.w, r0.x
					mad r0.xy, r0.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
					mul r0.xy, r0.xyxx, cb0[6].xxxx
					mul r0.xy, r0.xyxx, v1.wwww
					mad r0.xy, r0.xyxx, l(0.001000, 0.001000, 0.000000, 0.000000), v3.xyxx
					div r0.xy, r0.xyxx, v3.wwww
					sample_l r0.xyzw, r0.xyxx, t1.xyzw, s0, l(0.000000)
					add r1.xyz, cb0[5].xyzx, l(-1.000000, -1.000000, -1.000000, 0.000000)
					mad r1.xyz, v1.wwww, r1.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
					mul o0.xyz, r0.xyzx, r1.xyzx
					mul r0.x, cb0[5].w, cb0[5].w
					mul_sat o0.w, r0.x, cb0[5].w
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "USE_FRESNEL" "USE_CUTOUT" "USE_MAINTEX" "USE_HEIGHT" }
					"!!ps_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xy          2     NONE   float   xy  
					// TEXCOORD                 4     zw        2     NONE   float     zw
					// TEXCOORD                 2   xyzw        3     NONE   float   xy w
					// TEXCOORD                 6   xy          4     NONE   float   xy  
					// TEXCOORD                 7   xyzw        5     NONE   float   xyz 
					// TEXCOORD                 8   xyz         6     NONE   float   xyz 
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[16], immediateIndexed
					dcl_constantbuffer CB1[6], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_sampler s1, mode_default
					dcl_sampler s2, mode_default
					dcl_sampler s3, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_resource_texture2d (float,float,float,float) t1
					dcl_resource_texture2d (float,float,float,float) t2
					dcl_resource_texture2d (float,float,float,float) t3
					dcl_input_ps linear v1.xyzw
					dcl_input_ps linear v2.xy
					dcl_input_ps linear v2.zw
					dcl_input_ps linear v3.xyw
					dcl_input_ps linear v4.xy
					dcl_input_ps linear v5.xyz
					dcl_input_ps linear v6.xyz
					dcl_output o0.xyzw
					dcl_temps 5
					deriv_rty r0.xyz, v5.yzxy
					mul r0.xyz, r0.xyzx, cb1[5].xxxx
					deriv_rtx r1.xyz, v5.zxyz
					mul r2.xyz, r0.xyzx, r1.xyzx
					mad r0.xyz, r1.zxyz, r0.yzxy, -r2.xyzx
					dp3 r0.w, r0.xyzx, r0.xyzx
					rsq r0.w, r0.w
					mul r0.xyz, r0.wwww, r0.xyzx
					dp3 r0.x, r0.xyzx, v6.xyzx
					add r0.x, -r0.x, l(1.000000)
					log r0.x, r0.x
					mul r0.x, r0.x, cb0[11].x
					exp r0.x, r0.x
					add r0.y, -cb0[11].y, l(1.000000)
					mad_sat r0.x, r0.y, r0.x, cb0[11].y
					mul r0.y, r0.x, cb0[11].z
					mul r0.xzw, r0.xxxx, cb0[10].xxyz
					mul r0.y, r0.y, l(0.001000)
					sample r1.xyzw, v2.xyxx, t0.xyzw, s2
					mul r1.x, r1.w, r1.x
					mad r1.xy, r1.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
					mul r1.zw, r0.yyyy, r1.xxxy
					mul r2.xy, r1.xyxx, cb0[6].xxxx
					add r0.y, r1.y, r1.x
					mad r1.xy, r2.xyxx, l(0.001000, 0.001000, 0.000000, 0.000000), r1.zwzz
					mad r1.zw, r1.xxxy, v1.wwww, v3.xxxy
					div r1.xy, r1.xyxx, cb0[4].wwww
					add r1.xy, -r1.xyxx, v4.xyxx
					sample r2.xyzw, r1.xyxx, t3.xyzw, s1
					mul r2.xyz, r2.wwww, r2.xyzx
					mul r2.xyz, r2.xyzx, cb0[4].xyzx
					div r1.xy, r1.zwzz, v3.wwww
					sample_l r1.xyzw, r1.xyxx, t2.xyzw, s0, l(0.000000)
					mul r0.xzw, |r0.yyyy|, r0.xxzw
					mul r0.xzw, r0.xxzw, v1.xxyz
					mul r0.xzw, r0.xxzw, v1.wwww
					add r0.xzw, r0.xxzw, r0.xxzw
					mul r3.xyz, r1.xyzx, r0.xzwx
					dp3 r0.x, r0.xzwx, l(0.330000, 0.330000, 0.330000, 0.000000)
					mul_sat r0.x, r0.x, l(10.000000)
					add r4.xyz, cb0[5].xyzx, l(-1.000000, -1.000000, -1.000000, 0.000000)
					mad r4.xyz, v1.wwww, r4.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
					mad r1.xyz, r1.xyzx, r4.xyzx, r3.xyzx
					sample r3.xyzw, v2.zwzz, t1.xyzw, s3
					mad r0.y, -r0.y, l(0.100000), r3.x
					add r0.y, -r0.y, cb0[13].x
					ge r0.z, r0.y, l(0.000000)
					add r0.y, r0.y, cb0[15].x
					ge r0.y, r0.y, l(0.000000)
					and r0.y, r0.y, l(0x3f800000)
					movc r0.z, r0.z, l(-1.000000), l(-0.000000)
					add r0.z, r0.z, r0.y
					max r0.z, r0.z, l(0.000000)
					mad r1.xyz, cb0[14].xyzx, r0.zzzz, r1.xyzx
					mad o0.xyz, r2.xyzx, v1.wwww, r1.xyzx
					mul r0.z, r0.x, cb0[10].w
					mad r0.x, -r0.x, cb0[10].w, cb0[5].w
					mad r0.x, cb0[5].w, r0.x, r0.z
					log r0.z, cb0[13].x
					mul r0.z, r0.z, l(0.200000)
					exp r0.z, r0.z
					mul r0.y, r0.z, r0.y
					mul r0.x, r0.y, r0.x
					mul_sat o0.w, r0.x, cb0[5].w
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "DISTORT_OFF" }
					"!!ps_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// COLOR                    0   xyzw        1     NONE   float       
					// TEXCOORD                 0   xy          2     NONE   float       
					// TEXCOORD                 2   xyzw        3     NONE   float       
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_output o0.xyzw
					mov o0.xyzw, l(0,0,0,0)
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "SOFTPARTICLES_ON" "USE_FRESNEL" "USE_CUTOUT" "DISTORT_OFF" "USE_MAINTEX" "USE_HEIGHT" }
					"!!ps_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// COLOR                    0   xyzw        1     NONE   float       
					// TEXCOORD                 0   xy          2     NONE   float       
					// TEXCOORD                 4     zw        2     NONE   float       
					// TEXCOORD                 2   xyzw        3     NONE   float       
					// TEXCOORD                 6   xy          4     NONE   float       
					// TEXCOORD                 7   xyzw        5     NONE   float       
					// TEXCOORD                 8   xyz         6     NONE   float       
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_output o0.xyzw
					mov o0.xyzw, l(0,0,0,0)
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "SOFTPARTICLES_ON" "DISTORT_OFF" }
					"!!ps_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// COLOR                    0   xyzw        1     NONE   float       
					// TEXCOORD                 0   xy          2     NONE   float       
					// TEXCOORD                 2   xyzw        3     NONE   float       
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_output o0.xyzw
					mov o0.xyzw, l(0,0,0,0)
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "USE_FRESNEL" "USE_CUTOUT" "DISTORT_OFF" "USE_MAINTEX" "USE_HEIGHT" }
					"!!ps_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// COLOR                    0   xyzw        1     NONE   float       
					// TEXCOORD                 0   xy          2     NONE   float       
					// TEXCOORD                 4     zw        2     NONE   float       
					// TEXCOORD                 2   xyzw        3     NONE   float       
					// TEXCOORD                 6   xy          4     NONE   float       
					// TEXCOORD                 7   xyzw        5     NONE   float       
					// TEXCOORD                 8   xyz         6     NONE   float       
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_output o0.xyzw
					mov o0.xyzw, l(0,0,0,0)
					ret 
					// Approximately 0 instruction slots used"
				}
			}
		}
	}
	CustomEditor "ME_CustomShaderGUI"
}