Shader "KriptoFX/ME/Particle" {
	Properties {
		[Header(Main Settings)] [Space] [PerRendererData] [HDR] _TintColor ("Tint Color", Vector) = (1,1,1,1)
		_MainTex ("Main Texture", 2D) = "white" {}
		[Header(Fading)] [Space] [Toggle(_FADING_ON)] _UseSoft ("Use Soft Particles", Float) = 0
		_InvFade ("Soft Particles Factor", Float) = 1
		_SoftInverted ("Inverted Soft Particles", Range(0, 1)) = 0
		[Toggle(USE_FRESNEL_FADING)] _UseFresnelFading ("Use Fresnel Fading", Float) = 0
		_FresnelFadeFactor ("Fresnel Fade Factor", Float) = 3
		[Space] [Header(Light)] [Toggle(USE_VERTEX_LIGHT)] _UseVertexLight ("Use Vertex Lighting", Float) = 0
		[Space] [Header(Noise Distortion)] [Toggle(USE_NOISE_DISTORTION)] _UseNoiseDistortion ("Use Noise Distortion", Float) = 0
		_NoiseTex ("Noise Texture (RG)", 2D) = "black" {}
		_DistortionSpeedScale ("Speed (XY) Scale(XY)", Vector) = (1,-1,0.15,0.15)
		_UseVertexStreamRandom ("Use Vertex Stream Random", Float) = 0
		[Space] [Header(Fresnel)] [Toggle(USE_FRESNEL)] _UseFresnel ("Use Fresnel", Float) = 0
		[HDR] _FresnelColor ("Fresnel Color", Vector) = (1,1,1,1)
		_FresnelPow ("Fresnel Pow", Float) = 5
		_FresnelR0 ("Fresnel R0", Float) = 0.04
		[Space] [Header(Cutout)] [Toggle(USE_CUTOUT)] _UseCutout ("Use Cutout", Float) = 0
		[PerRendererData] _Cutout ("Cutout", Range(0, 1)) = 1
		_UseSoftCutout ("Use Soft Cutout", Float) = 0
		_UseParticlesAlphaCutout ("Use Particles Alpha", Float) = 0
		[Toggle(USE_CUTOUT_TEX)] _UseCutoutTex ("Use Cutout Texture", Float) = 0
		_CutoutTex ("Cutout Tex", 2D) = "white" {}
		[Toggle(USE_CUTOUT_THRESHOLD)] _UseCutoutThreshold ("Use Cutout Threshold", Float) = 0
		[HDR] _CutoutColor ("Cutout Color", Vector) = (1,1,1,1)
		_CutoutThreshold ("Cutout Threshold", Range(0, 1)) = 0.015
		[Space] [Header(Rendering)] [Toggle(_FLIPBOOK_BLENDING)] _UseFrameBlending ("Use Frame Blending", Float) = 0
		[Toggle] _ZWriteMode ("ZWrite On?", Float) = 0
		[Enum(Cull Off,0, Cull Front,1, Cull Back,2)] _CullMode ("Culling", Float) = 0
		[KeywordEnum(Add, Blend, Mul)] _BlendMode ("Blend Mode", Float) = 1
		_SrcMode ("SrcMode", Float) = 5
		_DstMode ("DstMode", Float) = 10
		_FogColorMultiplier ("Fog Color Multiplier", Vector) = (0,0,0,0)
	}
	SubShader {
		Tags { "IGNOREPROJECTOR" = "true" "QUEUE" = "Transparent" "RenderType" = "Transparent" }
		Pass {
			Tags { "IGNOREPROJECTOR" = "true" "QUEUE" = "Transparent" "RenderType" = "Transparent" }
			Blend Zero Zero, Zero Zero
			ZWrite Off
			Cull Off
			Offset -1, -1
			GpuProgramID 49604
			Program "vp" {
				SubProgram "d3d11 " {
					"!!vs_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// NORMAL                   0   xyzw        1     NONE   float       
					// COLOR                    0   xyzw        2     NONE   float   xyzw
					// TEXCOORD                 0   xy          3     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xy          2     NONE   float   xy  
					//
					vs_4_0
					dcl_constantbuffer CB0[3], immediateIndexed
					dcl_constantbuffer CB1[4], immediateIndexed
					dcl_constantbuffer CB2[21], immediateIndexed
					dcl_input v0.xyz
					dcl_input v2.xyzw
					dcl_input v3.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xy
					dcl_temps 2
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					add r0.xyzw, r0.xyzw, cb1[3].xyzw
					mul r1.xyzw, r0.yyyy, cb2[18].xyzw
					mad r1.xyzw, cb2[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb2[19].xyzw, r0.zzzz, r1.xyzw
					mad o0.xyzw, cb2[20].xyzw, r0.wwww, r1.xyzw
					mov o1.xyzw, v2.xyzw
					mad o2.xy, v3.xyxx, cb0[2].xyxx, cb0[2].zwzz
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "SOFTPARTICLES_ON" "_FADING_ON" }
					"!!vs_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// NORMAL                   0   xyzw        1     NONE   float       
					// COLOR                    0   xyzw        2     NONE   float   xyzw
					// TEXCOORD                 0   xy          3     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xy          2     NONE   float   xy  
					// TEXCOORD                 5   xyzw        3     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[3], immediateIndexed
					dcl_constantbuffer CB1[6], immediateIndexed
					dcl_constantbuffer CB2[4], immediateIndexed
					dcl_constantbuffer CB3[21], immediateIndexed
					dcl_input v0.xyz
					dcl_input v2.xyzw
					dcl_input v3.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xy
					dcl_output o3.xyzw
					dcl_temps 2
					mul r0.xyzw, v0.yyyy, cb2[1].xyzw
					mad r0.xyzw, cb2[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb2[2].xyzw, v0.zzzz, r0.xyzw
					add r0.xyzw, r0.xyzw, cb2[3].xyzw
					mul r1.xyzw, r0.yyyy, cb3[18].xyzw
					mad r1.xyzw, cb3[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb3[19].xyzw, r0.zzzz, r1.xyzw
					mad r1.xyzw, cb3[20].xyzw, r0.wwww, r1.xyzw
					mov o0.xyzw, r1.xyzw
					mov o1.xyzw, v2.xyzw
					mad o2.xy, v3.xyxx, cb0[2].xyxx, cb0[2].zwzz
					mul r0.y, r0.y, cb3[10].z
					mad r0.x, cb3[9].z, r0.x, r0.y
					mad r0.x, cb3[11].z, r0.z, r0.x
					mad r0.x, cb3[12].z, r0.w, r0.x
					mov o3.z, -r0.x
					mul r0.x, r1.y, cb1[5].x
					mul r0.w, r0.x, l(0.500000)
					mul r0.xz, r1.xxwx, l(0.500000, 0.000000, 0.500000, 0.000000)
					mov o3.w, r1.w
					add o3.xy, r0.zzzz, r0.xwxx
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "SOFTPARTICLES_ON" "_BLENDMODE_BLEND" }
					"!!vs_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// NORMAL                   0   xyzw        1     NONE   float       
					// COLOR                    0   xyzw        2     NONE   float   xyzw
					// TEXCOORD                 0   xy          3     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xy          2     NONE   float   xy  
					//
					vs_4_0
					dcl_constantbuffer CB0[3], immediateIndexed
					dcl_constantbuffer CB1[4], immediateIndexed
					dcl_constantbuffer CB2[21], immediateIndexed
					dcl_input v0.xyz
					dcl_input v2.xyzw
					dcl_input v3.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xy
					dcl_temps 2
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					add r0.xyzw, r0.xyzw, cb1[3].xyzw
					mul r1.xyzw, r0.yyyy, cb2[18].xyzw
					mad r1.xyzw, cb2[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb2[19].xyzw, r0.zzzz, r1.xyzw
					mad o0.xyzw, cb2[20].xyzw, r0.wwww, r1.xyzw
					mov o1.xyzw, v2.xyzw
					mad o2.xy, v3.xyxx, cb0[2].xyxx, cb0[2].zwzz
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "SOFTPARTICLES_ON" "_FADING_ON" "_BLENDMODE_BLEND" }
					"!!vs_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// NORMAL                   0   xyzw        1     NONE   float       
					// COLOR                    0   xyzw        2     NONE   float   xyzw
					// TEXCOORD                 0   xy          3     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xy          2     NONE   float   xy  
					// TEXCOORD                 5   xyzw        3     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[3], immediateIndexed
					dcl_constantbuffer CB1[6], immediateIndexed
					dcl_constantbuffer CB2[4], immediateIndexed
					dcl_constantbuffer CB3[21], immediateIndexed
					dcl_input v0.xyz
					dcl_input v2.xyzw
					dcl_input v3.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xy
					dcl_output o3.xyzw
					dcl_temps 2
					mul r0.xyzw, v0.yyyy, cb2[1].xyzw
					mad r0.xyzw, cb2[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb2[2].xyzw, v0.zzzz, r0.xyzw
					add r0.xyzw, r0.xyzw, cb2[3].xyzw
					mul r1.xyzw, r0.yyyy, cb3[18].xyzw
					mad r1.xyzw, cb3[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb3[19].xyzw, r0.zzzz, r1.xyzw
					mad r1.xyzw, cb3[20].xyzw, r0.wwww, r1.xyzw
					mov o0.xyzw, r1.xyzw
					mov o1.xyzw, v2.xyzw
					mad o2.xy, v3.xyxx, cb0[2].xyxx, cb0[2].zwzz
					mul r0.y, r0.y, cb3[10].z
					mad r0.x, cb3[9].z, r0.x, r0.y
					mad r0.x, cb3[11].z, r0.z, r0.x
					mad r0.x, cb3[12].z, r0.w, r0.x
					mov o3.z, -r0.x
					mul r0.x, r1.y, cb1[5].x
					mul r0.w, r0.x, l(0.500000)
					mul r0.xz, r1.xxwx, l(0.500000, 0.000000, 0.500000, 0.000000)
					mov o3.w, r1.w
					add o3.xy, r0.zzzz, r0.xwxx
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "SOFTPARTICLES_ON" "_FADING_ON" "_FLIPBOOK_BLENDING" "_BLENDMODE_BLEND" }
					"!!vs_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// NORMAL                   0   xyzw        1     NONE   float       
					// COLOR                    0   xyzw        2     NONE   float   xyzw
					// TEXCOORD                 0   xy          3     NONE   float   xy  
					// TEXCOORD                 1   xyzw        4     NONE   float   xyz 
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xyzw        2     NONE   float   xyzw
					// TEXCOORD                 1   x           3     NONE   float   x   
					// TEXCOORD                 5   xyzw        4     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[3], immediateIndexed
					dcl_constantbuffer CB1[6], immediateIndexed
					dcl_constantbuffer CB2[4], immediateIndexed
					dcl_constantbuffer CB3[21], immediateIndexed
					dcl_input v0.xyz
					dcl_input v2.xyzw
					dcl_input v3.xy
					dcl_input v4.xyz
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xyzw
					dcl_output o3.x
					dcl_output o4.xyzw
					dcl_temps 2
					mul r0.xyzw, v0.yyyy, cb2[1].xyzw
					mad r0.xyzw, cb2[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb2[2].xyzw, v0.zzzz, r0.xyzw
					add r0.xyzw, r0.xyzw, cb2[3].xyzw
					mul r1.xyzw, r0.yyyy, cb3[18].xyzw
					mad r1.xyzw, cb3[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb3[19].xyzw, r0.zzzz, r1.xyzw
					mad r1.xyzw, cb3[20].xyzw, r0.wwww, r1.xyzw
					mov o0.xyzw, r1.xyzw
					mov o1.xyzw, v2.xyzw
					mad o2.xy, v3.xyxx, cb0[2].xyxx, cb0[2].zwzz
					mad o2.zw, v4.xxxy, cb0[2].xxxy, cb0[2].zzzw
					mov o3.x, v4.z
					mul r0.y, r0.y, cb3[10].z
					mad r0.x, cb3[9].z, r0.x, r0.y
					mad r0.x, cb3[11].z, r0.z, r0.x
					mad r0.x, cb3[12].z, r0.w, r0.x
					mov o4.z, -r0.x
					mul r0.x, r1.y, cb1[5].x
					mul r0.w, r0.x, l(0.500000)
					mul r0.xz, r1.xxwx, l(0.500000, 0.000000, 0.500000, 0.000000)
					mov o4.w, r1.w
					add o4.xy, r0.zzzz, r0.xwxx
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "SOFTPARTICLES_ON" "_BLENDMODE_BLEND" "USE_VERTEX_LIGHT" }
					"!!vs_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyzw
					// NORMAL                   0   xyzw        1     NONE   float       
					// COLOR                    0   xyzw        2     NONE   float   xyzw
					// TEXCOORD                 0   xy          3     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xy          2     NONE   float   xy  
					//
					vs_4_0
					dcl_constantbuffer CB0[103], dynamicIndexed
					dcl_constantbuffer CB1[7], immediateIndexed
					dcl_constantbuffer CB2[21], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_input v0.xyzw
					dcl_input v2.xyzw
					dcl_input v3.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xy
					dcl_temps 5
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					add r1.xyzw, r0.xyzw, cb1[3].xyzw
					mul r2.xyzw, r1.yyyy, cb2[18].xyzw
					mad r2.xyzw, cb2[17].xyzw, r1.xxxx, r2.xyzw
					mad r2.xyzw, cb2[19].xyzw, r1.zzzz, r2.xyzw
					mad o0.xyzw, cb2[20].xyzw, r1.wwww, r2.xyzw
					mad r0.xyz, cb1[3].xyzx, v0.wwww, r0.xyzx
					dp3 r1.x, l(1.000000, 1.000000, 1.000000, 0.000000), cb1[4].xyzx
					dp3 r1.y, l(1.000000, 1.000000, 1.000000, 0.000000), cb1[5].xyzx
					dp3 r1.z, l(1.000000, 1.000000, 1.000000, 0.000000), cb1[6].xyzx
					dp3 r0.w, r1.xyzx, r1.xyzx
					rsq r0.w, r0.w
					mul r1.xyz, r0.wwww, r1.xyzx
					mov r2.xyz, l(0,0,0,0)
					mov r0.w, l(0)
					loop 
					  ige r1.w, r0.w, cb0[102].x
					  breakc_nz r1.w
					  mad r3.xyz, -r0.xyzx, cb0[r0.w + 62].wwww, cb0[r0.w + 22].xyzx
					  dp3 r1.w, r3.xyzx, r3.xyzx
					  sqrt r2.w, r1.w
					  div r2.w, r2.w, cb0[r0.w + 22].w
					  sample_l r4.xyzw, r2.wwww, t0.xyzw, s0, l(0.000000)
					  add r2.w, r4.x, l(-1.000000)
					  mad r2.w, cb0[r0.w + 62].w, r2.w, l(1.000000)
					  rsq r1.w, r1.w
					  mul r3.xyz, r1.wwww, r3.xyzx
					  dp3 r1.w, r1.xyzx, r3.xyzx
					  max r1.w, r1.w, l(0.000000)
					  mul r1.w, r2.w, r1.w
					  mad r2.xyz, cb0[r0.w + 62].xyzx, r1.wwww, r2.xyzx
					  iadd r0.w, r0.w, l(1)
					endloop 
					mul r0.xyz, r2.xyzx, v2.xyzx
					mul o1.xyz, r0.xyzx, l(3.000000, 3.000000, 3.000000, 0.000000)
					mad o2.xy, v3.xyxx, cb0[2].xyxx, cb0[2].zwzz
					mov o1.w, v2.w
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "SOFTPARTICLES_ON" }
					"!!vs_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// NORMAL                   0   xyzw        1     NONE   float       
					// COLOR                    0   xyzw        2     NONE   float   xyzw
					// TEXCOORD                 0   xy          3     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xy          2     NONE   float   xy  
					//
					vs_4_0
					dcl_constantbuffer CB0[3], immediateIndexed
					dcl_constantbuffer CB1[4], immediateIndexed
					dcl_constantbuffer CB2[21], immediateIndexed
					dcl_input v0.xyz
					dcl_input v2.xyzw
					dcl_input v3.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xy
					dcl_temps 2
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					add r0.xyzw, r0.xyzw, cb1[3].xyzw
					mul r1.xyzw, r0.yyyy, cb2[18].xyzw
					mad r1.xyzw, cb2[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb2[19].xyzw, r0.zzzz, r1.xyzw
					mad o0.xyzw, cb2[20].xyzw, r0.wwww, r1.xyzw
					mov o1.xyzw, v2.xyzw
					mad o2.xy, v3.xyxx, cb0[2].xyxx, cb0[2].zwzz
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "_FADING_ON" }
					"!!vs_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// NORMAL                   0   xyzw        1     NONE   float       
					// COLOR                    0   xyzw        2     NONE   float   xyzw
					// TEXCOORD                 0   xy          3     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xy          2     NONE   float   xy  
					//
					vs_4_0
					dcl_constantbuffer CB0[3], immediateIndexed
					dcl_constantbuffer CB1[4], immediateIndexed
					dcl_constantbuffer CB2[21], immediateIndexed
					dcl_input v0.xyz
					dcl_input v2.xyzw
					dcl_input v3.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xy
					dcl_temps 2
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					add r0.xyzw, r0.xyzw, cb1[3].xyzw
					mul r1.xyzw, r0.yyyy, cb2[18].xyzw
					mad r1.xyzw, cb2[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb2[19].xyzw, r0.zzzz, r1.xyzw
					mad o0.xyzw, cb2[20].xyzw, r0.wwww, r1.xyzw
					mov o1.xyzw, v2.xyzw
					mad o2.xy, v3.xyxx, cb0[2].xyxx, cb0[2].zwzz
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "_BLENDMODE_BLEND" }
					"!!vs_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// NORMAL                   0   xyzw        1     NONE   float       
					// COLOR                    0   xyzw        2     NONE   float   xyzw
					// TEXCOORD                 0   xy          3     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xy          2     NONE   float   xy  
					//
					vs_4_0
					dcl_constantbuffer CB0[3], immediateIndexed
					dcl_constantbuffer CB1[4], immediateIndexed
					dcl_constantbuffer CB2[21], immediateIndexed
					dcl_input v0.xyz
					dcl_input v2.xyzw
					dcl_input v3.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xy
					dcl_temps 2
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					add r0.xyzw, r0.xyzw, cb1[3].xyzw
					mul r1.xyzw, r0.yyyy, cb2[18].xyzw
					mad r1.xyzw, cb2[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb2[19].xyzw, r0.zzzz, r1.xyzw
					mad o0.xyzw, cb2[20].xyzw, r0.wwww, r1.xyzw
					mov o1.xyzw, v2.xyzw
					mad o2.xy, v3.xyxx, cb0[2].xyxx, cb0[2].zwzz
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "_FADING_ON" "_BLENDMODE_BLEND" }
					"!!vs_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// NORMAL                   0   xyzw        1     NONE   float       
					// COLOR                    0   xyzw        2     NONE   float   xyzw
					// TEXCOORD                 0   xy          3     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xy          2     NONE   float   xy  
					//
					vs_4_0
					dcl_constantbuffer CB0[3], immediateIndexed
					dcl_constantbuffer CB1[4], immediateIndexed
					dcl_constantbuffer CB2[21], immediateIndexed
					dcl_input v0.xyz
					dcl_input v2.xyzw
					dcl_input v3.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xy
					dcl_temps 2
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					add r0.xyzw, r0.xyzw, cb1[3].xyzw
					mul r1.xyzw, r0.yyyy, cb2[18].xyzw
					mad r1.xyzw, cb2[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb2[19].xyzw, r0.zzzz, r1.xyzw
					mad o0.xyzw, cb2[20].xyzw, r0.wwww, r1.xyzw
					mov o1.xyzw, v2.xyzw
					mad o2.xy, v3.xyxx, cb0[2].xyxx, cb0[2].zwzz
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "_FADING_ON" "_FLIPBOOK_BLENDING" "_BLENDMODE_BLEND" }
					"!!vs_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// NORMAL                   0   xyzw        1     NONE   float       
					// COLOR                    0   xyzw        2     NONE   float   xyzw
					// TEXCOORD                 0   xy          3     NONE   float   xy  
					// TEXCOORD                 1   xyzw        4     NONE   float   xyz 
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xyzw        2     NONE   float   xyzw
					// TEXCOORD                 1   x           3     NONE   float   x   
					//
					vs_4_0
					dcl_constantbuffer CB0[3], immediateIndexed
					dcl_constantbuffer CB1[4], immediateIndexed
					dcl_constantbuffer CB2[21], immediateIndexed
					dcl_input v0.xyz
					dcl_input v2.xyzw
					dcl_input v3.xy
					dcl_input v4.xyz
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xyzw
					dcl_output o3.x
					dcl_temps 2
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					add r0.xyzw, r0.xyzw, cb1[3].xyzw
					mul r1.xyzw, r0.yyyy, cb2[18].xyzw
					mad r1.xyzw, cb2[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb2[19].xyzw, r0.zzzz, r1.xyzw
					mad o0.xyzw, cb2[20].xyzw, r0.wwww, r1.xyzw
					mov o1.xyzw, v2.xyzw
					mad o2.xy, v3.xyxx, cb0[2].xyxx, cb0[2].zwzz
					mad o2.zw, v4.xxxy, cb0[2].xxxy, cb0[2].zzzw
					mov o3.x, v4.z
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "_BLENDMODE_BLEND" "USE_VERTEX_LIGHT" }
					"!!vs_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyzw
					// NORMAL                   0   xyzw        1     NONE   float       
					// COLOR                    0   xyzw        2     NONE   float   xyzw
					// TEXCOORD                 0   xy          3     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xy          2     NONE   float   xy  
					//
					vs_4_0
					dcl_constantbuffer CB0[103], dynamicIndexed
					dcl_constantbuffer CB1[7], immediateIndexed
					dcl_constantbuffer CB2[21], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_input v0.xyzw
					dcl_input v2.xyzw
					dcl_input v3.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xy
					dcl_temps 5
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					add r1.xyzw, r0.xyzw, cb1[3].xyzw
					mul r2.xyzw, r1.yyyy, cb2[18].xyzw
					mad r2.xyzw, cb2[17].xyzw, r1.xxxx, r2.xyzw
					mad r2.xyzw, cb2[19].xyzw, r1.zzzz, r2.xyzw
					mad o0.xyzw, cb2[20].xyzw, r1.wwww, r2.xyzw
					mad r0.xyz, cb1[3].xyzx, v0.wwww, r0.xyzx
					dp3 r1.x, l(1.000000, 1.000000, 1.000000, 0.000000), cb1[4].xyzx
					dp3 r1.y, l(1.000000, 1.000000, 1.000000, 0.000000), cb1[5].xyzx
					dp3 r1.z, l(1.000000, 1.000000, 1.000000, 0.000000), cb1[6].xyzx
					dp3 r0.w, r1.xyzx, r1.xyzx
					rsq r0.w, r0.w
					mul r1.xyz, r0.wwww, r1.xyzx
					mov r2.xyz, l(0,0,0,0)
					mov r0.w, l(0)
					loop 
					  ige r1.w, r0.w, cb0[102].x
					  breakc_nz r1.w
					  mad r3.xyz, -r0.xyzx, cb0[r0.w + 62].wwww, cb0[r0.w + 22].xyzx
					  dp3 r1.w, r3.xyzx, r3.xyzx
					  sqrt r2.w, r1.w
					  div r2.w, r2.w, cb0[r0.w + 22].w
					  sample_l r4.xyzw, r2.wwww, t0.xyzw, s0, l(0.000000)
					  add r2.w, r4.x, l(-1.000000)
					  mad r2.w, cb0[r0.w + 62].w, r2.w, l(1.000000)
					  rsq r1.w, r1.w
					  mul r3.xyz, r1.wwww, r3.xyzx
					  dp3 r1.w, r1.xyzx, r3.xyzx
					  max r1.w, r1.w, l(0.000000)
					  mul r1.w, r2.w, r1.w
					  mad r2.xyz, cb0[r0.w + 62].xyzx, r1.wwww, r2.xyzx
					  iadd r0.w, r0.w, l(1)
					endloop 
					mul r0.xyz, r2.xyzx, v2.xyzx
					mul o1.xyz, r0.xyzx, l(3.000000, 3.000000, 3.000000, 0.000000)
					mad o2.xy, v3.xyxx, cb0[2].xyxx, cb0[2].zwzz
					mov o1.w, v2.w
					ret 
					// Approximately 0 instruction slots used"
				}
			}
			Program "fp" {
				SubProgram "d3d11 " {
					"!!ps_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xy          2     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[18], immediateIndexed
					dcl_constantbuffer CB1[1], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_input_ps linear v1.xyzw
					dcl_input_ps linear v2.xy
					dcl_output o0.xyzw
					dcl_temps 3
					sample r0.xyzw, v2.xyxx, t0.xyzw, s0
					mul r0.xyzw, r0.xyzw, cb1[0].xyzw
					mul r0.xyzw, r0.xyzw, v1.xyzw
					mad r1.xyz, r0.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)
					add r2.xyzw, r0.xyzw, r0.xyzw
					mov_sat r2.w, r2.w
					mad r1.xyz, r2.wwww, r1.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
					mov o0.w, r2.w
					mad r0.xyz, -r0.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), r1.xyzx
					mad o0.xyz, cb0[17].xxxx, r0.xyzx, r2.xyzx
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "SOFTPARTICLES_ON" "_FADING_ON" }
					"!!ps_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xy          2     NONE   float   xy  
					// TEXCOORD                 5   xyzw        3     NONE   float   xyzw
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[19], immediateIndexed
					dcl_constantbuffer CB1[8], immediateIndexed
					dcl_constantbuffer CB2[1], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_sampler s1, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_resource_texture2d (float,float,float,float) t1
					dcl_input_ps linear v1.xyzw
					dcl_input_ps linear v2.xy
					dcl_input_ps linear v3.xyzw
					dcl_output o0.xyzw
					dcl_temps 3
					div r0.xy, v3.xyxx, v3.wwww
					sample r0.xyzw, r0.xyxx, t0.xyzw, s1
					mad r0.x, cb1[7].z, r0.x, cb1[7].w
					div r0.x, l(1.000000, 1.000000, 1.000000, 1.000000), r0.x
					add r0.x, r0.x, -v3.z
					mul_sat r0.x, r0.x, cb0[18].x
					add r0.y, -r0.x, l(1.000000)
					add r0.y, -r0.x, r0.y
					mad r0.x, cb0[18].y, r0.y, r0.x
					mul r0.w, r0.x, v1.w
					sample r1.xyzw, v2.xyxx, t1.xyzw, s0
					mul r1.xyzw, r1.xyzw, cb2[0].xyzw
					mov r0.xyz, v1.xyzx
					mul r0.xyzw, r0.xyzw, r1.xyzw
					mad r1.xyz, r0.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)
					add r2.xyzw, r0.xyzw, r0.xyzw
					mov_sat r2.w, r2.w
					mad r1.xyz, r2.wwww, r1.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
					mov o0.w, r2.w
					mad r0.xyz, -r0.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), r1.xyzx
					mad o0.xyz, cb0[17].xxxx, r0.xyzx, r2.xyzx
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "SOFTPARTICLES_ON" "_BLENDMODE_BLEND" }
					"!!ps_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xy          2     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[1], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_input_ps linear v1.xyzw
					dcl_input_ps linear v2.xy
					dcl_output o0.xyzw
					dcl_temps 1
					sample r0.xyzw, v2.xyxx, t0.xyzw, s0
					mul r0.xyzw, r0.xyzw, cb0[0].xyzw
					mul r0.xyzw, r0.xyzw, v1.xyzw
					add r0.xyzw, r0.xyzw, r0.xyzw
					mov_sat o0.w, r0.w
					mov o0.xyz, r0.xyzx
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "SOFTPARTICLES_ON" "_FADING_ON" "_BLENDMODE_BLEND" }
					"!!ps_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xy          2     NONE   float   xy  
					// TEXCOORD                 5   xyzw        3     NONE   float   xyzw
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[19], immediateIndexed
					dcl_constantbuffer CB1[8], immediateIndexed
					dcl_constantbuffer CB2[1], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_sampler s1, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_resource_texture2d (float,float,float,float) t1
					dcl_input_ps linear v1.xyzw
					dcl_input_ps linear v2.xy
					dcl_input_ps linear v3.xyzw
					dcl_output o0.xyzw
					dcl_temps 2
					div r0.xy, v3.xyxx, v3.wwww
					sample r0.xyzw, r0.xyxx, t0.xyzw, s1
					mad r0.x, cb1[7].z, r0.x, cb1[7].w
					div r0.x, l(1.000000, 1.000000, 1.000000, 1.000000), r0.x
					add r0.x, r0.x, -v3.z
					mul_sat r0.x, r0.x, cb0[18].x
					add r0.y, -r0.x, l(1.000000)
					add r0.y, -r0.x, r0.y
					mad r0.x, cb0[18].y, r0.y, r0.x
					mul r0.w, r0.x, v1.w
					sample r1.xyzw, v2.xyxx, t1.xyzw, s0
					mul r1.xyzw, r1.xyzw, cb2[0].xyzw
					mov r0.xyz, v1.xyzx
					mul r0.xyzw, r0.xyzw, r1.xyzw
					add r0.xyzw, r0.xyzw, r0.xyzw
					mov_sat o0.w, r0.w
					mov o0.xyz, r0.xyzx
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "SOFTPARTICLES_ON" "_FADING_ON" "_FLIPBOOK_BLENDING" "_BLENDMODE_BLEND" }
					"!!ps_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xyzw        2     NONE   float   xyzw
					// TEXCOORD                 1   x           3     NONE   float   x   
					// TEXCOORD                 5   xyzw        4     NONE   float   xyzw
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[19], immediateIndexed
					dcl_constantbuffer CB1[8], immediateIndexed
					dcl_constantbuffer CB2[1], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_sampler s1, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_resource_texture2d (float,float,float,float) t1
					dcl_input_ps linear v1.xyzw
					dcl_input_ps linear v2.xyzw
					dcl_input_ps linear v3.x
					dcl_input_ps linear v4.xyzw
					dcl_output o0.xyzw
					dcl_temps 3
					div r0.xy, v4.xyxx, v4.wwww
					sample r0.xyzw, r0.xyxx, t0.xyzw, s1
					mad r0.x, cb1[7].z, r0.x, cb1[7].w
					div r0.x, l(1.000000, 1.000000, 1.000000, 1.000000), r0.x
					add r0.x, r0.x, -v4.z
					mul_sat r0.x, r0.x, cb0[18].x
					add r0.y, -r0.x, l(1.000000)
					add r0.y, -r0.x, r0.y
					mad r0.x, cb0[18].y, r0.y, r0.x
					mul r0.w, r0.x, v1.w
					sample r1.xyzw, v2.zwzz, t1.xyzw, s0
					sample r2.xyzw, v2.xyxx, t1.xyzw, s0
					add r1.xyzw, r1.xyzw, -r2.xyzw
					mad r1.xyzw, v3.xxxx, r1.xyzw, r2.xyzw
					mul r1.xyzw, r1.xyzw, cb2[0].xyzw
					mov r0.xyz, v1.xyzx
					mul r0.xyzw, r0.xyzw, r1.xyzw
					add r0.xyzw, r0.xyzw, r0.xyzw
					mov_sat o0.w, r0.w
					mov o0.xyz, r0.xyzx
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "SOFTPARTICLES_ON" "_BLENDMODE_BLEND" "USE_VERTEX_LIGHT" }
					"!!ps_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xy          2     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[1], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_input_ps linear v1.xyzw
					dcl_input_ps linear v2.xy
					dcl_output o0.xyzw
					dcl_temps 1
					sample r0.xyzw, v2.xyxx, t0.xyzw, s0
					mul r0.xyzw, r0.xyzw, cb0[0].xyzw
					mul r0.xyzw, r0.xyzw, v1.xyzw
					add r0.xyzw, r0.xyzw, r0.xyzw
					mov_sat o0.w, r0.w
					mov o0.xyz, r0.xyzx
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "SOFTPARTICLES_ON" }
					"!!ps_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xy          2     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[18], immediateIndexed
					dcl_constantbuffer CB1[1], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_input_ps linear v1.xyzw
					dcl_input_ps linear v2.xy
					dcl_output o0.xyzw
					dcl_temps 3
					sample r0.xyzw, v2.xyxx, t0.xyzw, s0
					mul r0.xyzw, r0.xyzw, cb1[0].xyzw
					mul r0.xyzw, r0.xyzw, v1.xyzw
					mad r1.xyz, r0.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)
					add r2.xyzw, r0.xyzw, r0.xyzw
					mov_sat r2.w, r2.w
					mad r1.xyz, r2.wwww, r1.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
					mov o0.w, r2.w
					mad r0.xyz, -r0.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), r1.xyzx
					mad o0.xyz, cb0[17].xxxx, r0.xyzx, r2.xyzx
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "_FADING_ON" }
					"!!ps_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xy          2     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[18], immediateIndexed
					dcl_constantbuffer CB1[1], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_input_ps linear v1.xyzw
					dcl_input_ps linear v2.xy
					dcl_output o0.xyzw
					dcl_temps 3
					sample r0.xyzw, v2.xyxx, t0.xyzw, s0
					mul r0.xyzw, r0.xyzw, cb1[0].xyzw
					mul r0.xyzw, r0.xyzw, v1.xyzw
					mad r1.xyz, r0.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)
					add r2.xyzw, r0.xyzw, r0.xyzw
					mov_sat r2.w, r2.w
					mad r1.xyz, r2.wwww, r1.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
					mov o0.w, r2.w
					mad r0.xyz, -r0.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), r1.xyzx
					mad o0.xyz, cb0[17].xxxx, r0.xyzx, r2.xyzx
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "_BLENDMODE_BLEND" }
					"!!ps_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xy          2     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[1], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_input_ps linear v1.xyzw
					dcl_input_ps linear v2.xy
					dcl_output o0.xyzw
					dcl_temps 1
					sample r0.xyzw, v2.xyxx, t0.xyzw, s0
					mul r0.xyzw, r0.xyzw, cb0[0].xyzw
					mul r0.xyzw, r0.xyzw, v1.xyzw
					add r0.xyzw, r0.xyzw, r0.xyzw
					mov_sat o0.w, r0.w
					mov o0.xyz, r0.xyzx
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "_FADING_ON" "_BLENDMODE_BLEND" }
					"!!ps_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xy          2     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[1], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_input_ps linear v1.xyzw
					dcl_input_ps linear v2.xy
					dcl_output o0.xyzw
					dcl_temps 1
					sample r0.xyzw, v2.xyxx, t0.xyzw, s0
					mul r0.xyzw, r0.xyzw, cb0[0].xyzw
					mul r0.xyzw, r0.xyzw, v1.xyzw
					add r0.xyzw, r0.xyzw, r0.xyzw
					mov_sat o0.w, r0.w
					mov o0.xyz, r0.xyzx
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "_FADING_ON" "_FLIPBOOK_BLENDING" "_BLENDMODE_BLEND" }
					"!!ps_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xyzw        2     NONE   float   xyzw
					// TEXCOORD                 1   x           3     NONE   float   x   
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[1], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_input_ps linear v1.xyzw
					dcl_input_ps linear v2.xyzw
					dcl_input_ps linear v3.x
					dcl_output o0.xyzw
					dcl_temps 2
					sample r0.xyzw, v2.zwzz, t0.xyzw, s0
					sample r1.xyzw, v2.xyxx, t0.xyzw, s0
					add r0.xyzw, r0.xyzw, -r1.xyzw
					mad r0.xyzw, v3.xxxx, r0.xyzw, r1.xyzw
					mul r0.xyzw, r0.xyzw, cb0[0].xyzw
					mul r0.xyzw, r0.xyzw, v1.xyzw
					add r0.xyzw, r0.xyzw, r0.xyzw
					mov_sat o0.w, r0.w
					mov o0.xyz, r0.xyzx
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "_BLENDMODE_BLEND" "USE_VERTEX_LIGHT" }
					"!!ps_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xy          2     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[1], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_input_ps linear v1.xyzw
					dcl_input_ps linear v2.xy
					dcl_output o0.xyzw
					dcl_temps 1
					sample r0.xyzw, v2.xyxx, t0.xyzw, s0
					mul r0.xyzw, r0.xyzw, cb0[0].xyzw
					mul r0.xyzw, r0.xyzw, v1.xyzw
					add r0.xyzw, r0.xyzw, r0.xyzw
					mov_sat o0.w, r0.w
					mov o0.xyz, r0.xyzx
					ret 
					// Approximately 0 instruction slots used"
				}
			}
		}
	}
	CustomEditor "ME_UberParticleGUI"
}