Shader "KriptoFX/RFX4/Decal" {
	Properties {
		[Header(Main Settings)] [Space] [PerRendererData] [HDR] _TintColor ("Tint Color", Vector) = (1,1,1,1)
		_MainTex ("Main Texture", 2D) = "white" {}
		[Toggle(USE_ALPHA_POW)] _UseAlphaPow ("Use Alpha Pow", Float) = 0
		_AlphaPow ("Alpha pow", Float) = 1
		[Space] [Header(Light)] [Space] [Header(Noise Distortion)] [Toggle(USE_NOISE_DISTORTION)] _UseNoiseDistortion ("Use Noise Distortion", Float) = 0
		_NoiseTex ("Noise Texture (RG)", 2D) = "gray" {}
		_DistortSpeed ("Distort Speed", Float) = 1
		_DistortScale ("Distort Scale", Float) = 0.1
		[Space] [Header(Cutout)] [Toggle(USE_CUTOUT)] _UseCutout ("Use Cutout", Float) = 0
		[PerRendererData] _Cutout ("Cutout", Range(0, 1)) = 1
		_CutoutAlphaMul ("Alpha multiplier", Float) = 1
		[Toggle(USE_CUTOUT_TEX)] _UseCutoutTex ("Use Cutout Texture", Float) = 0
		_CutoutTex ("Cutout Tex", 2D) = "white" {}
		[Toggle(USE_CUTOUT_THRESHOLD)] _UseCutoutThreshold ("Use Cutout Threshold", Float) = 0
		[HDR] _CutoutColor ("Cutout Color", Vector) = (1,1,1,1)
		[Space] [Header(Rendering)] [Toggle(USE_WORLD_SPACE_UV)] _UseWorldSpaceUV ("Use World Space UV", Float) = 0
		[Toggle(USE_FRAME_BLENDING)] _UseFrameBlending ("Use Frame Blending", Float) = 0
		[KeywordEnum(Add, Blend, Mul)] _BlendMode ("Blend Mode", Float) = 1
		_SrcMode ("SrcMode", Float) = 5
		_DstMode ("DstMode", Float) = 10
		_ZTest1 ("_ZTest1", Float) = 5
	}
	SubShader {
		Tags { "IGNOREPROJECTOR" = "true" "QUEUE" = "Geometry+1" "RenderType" = "Transparent" }
		Pass {
			Tags { "IGNOREPROJECTOR" = "true" "QUEUE" = "Geometry+1" "RenderType" = "Transparent" }
			Blend Zero Zero, Zero Zero
			ZWrite Off
			Cull Front
			GpuProgramID 17760
			Program "vp" {
				SubProgram "d3d11 " {
					Keywords { "_BLENDMODE_ADD" }
					"!!vs_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// NORMAL                   0   xyzw        1     NONE   float       
					// COLOR                    0   xyzw        2     NONE   float   xyzw
					// TEXCOORD                 0   xyzw        3     NONE   float       
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xyzw        2     NONE   float   xyzw
					// TEXCOORD                 1   xyz         3     NONE   float   xyz 
					//
					vs_4_0
					dcl_constantbuffer CB0[6], immediateIndexed
					dcl_constantbuffer CB1[4], immediateIndexed
					dcl_constantbuffer CB2[21], immediateIndexed
					dcl_input v0.xyz
					dcl_input v2.xyzw
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xyzw
					dcl_output o3.xyz
					dcl_temps 3
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					add r0.xyzw, r0.xyzw, cb1[3].xyzw
					mul r1.xyzw, r0.yyyy, cb2[18].xyzw
					mad r1.xyzw, cb2[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb2[19].xyzw, r0.zzzz, r1.xyzw
					mad r1.xyzw, cb2[20].xyzw, r0.wwww, r1.xyzw
					mov o0.xyzw, r1.xyzw
					mov o1.xyzw, v2.xyzw
					mul r1.y, r1.y, cb0[5].x
					mul r2.xzw, r1.xxwy, l(0.500000, 0.000000, 0.500000, 0.500000)
					mov o2.zw, r1.zzzw
					add o2.xy, r2.zzzz, r2.xwxx
					mul r1.xyz, r0.yyyy, cb2[10].xyzx
					mad r1.xyz, cb2[9].xyzx, r0.xxxx, r1.xyzx
					mad r0.xyz, cb2[11].xyzx, r0.zzzz, r1.xyzx
					mad r0.xyz, cb2[12].xyzx, r0.wwww, r0.xyzx
					mul o3.xyz, r0.xyzx, l(-1.000000, -1.000000, 1.000000, 0.000000)
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "_BLENDMODE_ADD" "USE_QUAD_DECAL" }
					"!!vs_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// NORMAL                   0   xyzw        1     NONE   float       
					// COLOR                    0   xyzw        2     NONE   float   xyzw
					// TEXCOORD                 0   xyzw        3     NONE   float       
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xyzw        2     NONE   float   xyzw
					// TEXCOORD                 1   xyz         3     NONE   float   xyz 
					// TEXCOORD                 2   xy          4     NONE   float   xy  
					//
					vs_4_0
					dcl_constantbuffer CB0[6], immediateIndexed
					dcl_constantbuffer CB1[4], immediateIndexed
					dcl_constantbuffer CB2[21], immediateIndexed
					dcl_input v0.xyz
					dcl_input v2.xyzw
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xyzw
					dcl_output o3.xyz
					dcl_output o4.xy
					dcl_temps 3
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					add r0.xyzw, r0.xyzw, cb1[3].xyzw
					mul r1.xyzw, r0.yyyy, cb2[18].xyzw
					mad r1.xyzw, cb2[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb2[19].xyzw, r0.zzzz, r1.xyzw
					mad r1.xyzw, cb2[20].xyzw, r0.wwww, r1.xyzw
					mov o0.xyzw, r1.xyzw
					mov o1.xyzw, v2.xyzw
					mul r1.y, r1.y, cb0[5].x
					mul r2.xzw, r1.xxwy, l(0.500000, 0.000000, 0.500000, 0.500000)
					mov o2.zw, r1.zzzw
					add o2.xy, r2.zzzz, r2.xwxx
					mul r1.xyz, r0.yyyy, cb2[10].xyzx
					mad r1.xyz, cb2[9].xyzx, r0.xxxx, r1.xyzx
					mad r0.xyz, cb2[11].xyzx, r0.zzzz, r1.xyzx
					mad r0.xyz, cb2[12].xyzx, r0.wwww, r0.xyzx
					mul o3.xyz, r0.xyzx, l(-1.000000, -1.000000, 1.000000, 0.000000)
					add o4.xy, v0.xzxx, l(0.500000, 0.500000, 0.000000, 0.000000)
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "USE_NOISE_DISTORTION" "USE_CUTOUT" "USE_CUTOUT_TEX" "_BLENDMODE_ADD" "USE_QUAD_DECAL" "USE_ALPHA_POW" }
					"!!vs_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// NORMAL                   0   xyzw        1     NONE   float       
					// COLOR                    0   xyzw        2     NONE   float   xyzw
					// TEXCOORD                 0   xyzw        3     NONE   float       
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xyzw        2     NONE   float   xyzw
					// TEXCOORD                 1   xyz         3     NONE   float   xyz 
					// TEXCOORD                 2   xy          4     NONE   float   xy  
					//
					vs_4_0
					dcl_constantbuffer CB0[6], immediateIndexed
					dcl_constantbuffer CB1[4], immediateIndexed
					dcl_constantbuffer CB2[21], immediateIndexed
					dcl_input v0.xyz
					dcl_input v2.xyzw
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xyzw
					dcl_output o3.xyz
					dcl_output o4.xy
					dcl_temps 3
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					add r0.xyzw, r0.xyzw, cb1[3].xyzw
					mul r1.xyzw, r0.yyyy, cb2[18].xyzw
					mad r1.xyzw, cb2[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb2[19].xyzw, r0.zzzz, r1.xyzw
					mad r1.xyzw, cb2[20].xyzw, r0.wwww, r1.xyzw
					mov o0.xyzw, r1.xyzw
					mov o1.xyzw, v2.xyzw
					mul r1.y, r1.y, cb0[5].x
					mul r2.xzw, r1.xxwy, l(0.500000, 0.000000, 0.500000, 0.500000)
					mov o2.zw, r1.zzzw
					add o2.xy, r2.zzzz, r2.xwxx
					mul r1.xyz, r0.yyyy, cb2[10].xyzx
					mad r1.xyz, cb2[9].xyzx, r0.xxxx, r1.xyzx
					mad r0.xyz, cb2[11].xyzx, r0.zzzz, r1.xyzx
					mad r0.xyz, cb2[12].xyzx, r0.wwww, r0.xyzx
					mul o3.xyz, r0.xyzx, l(-1.000000, -1.000000, 1.000000, 0.000000)
					add o4.xy, v0.xzxx, l(0.500000, 0.500000, 0.000000, 0.000000)
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "INSTANCING_ON" "_BLENDMODE_ADD" }
					"!!vs_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// NORMAL                   0   xyzw        1     NONE   float       
					// COLOR                    0   xyzw        2     NONE   float   xyzw
					// TEXCOORD                 0   xyzw        3     NONE   float       
					// SV_InstanceID            0   x           4   INSTID    uint   x   
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xyzw        2     NONE   float   xyzw
					// TEXCOORD                 1   xyz         3     NONE   float   xyz 
					// SV_InstanceID            0   x           4     NONE    uint   x   
					//
					vs_4_0
					dcl_constantbuffer CB0[6], immediateIndexed
					dcl_constantbuffer CB1[21], immediateIndexed
					dcl_constantbuffer CB2[1], immediateIndexed
					dcl_constantbuffer CB3[12], dynamicIndexed
					dcl_input v0.xyz
					dcl_input v2.xyzw
					dcl_input_sgv v4.x, instance_id
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xyzw
					dcl_output o3.xyz
					dcl_output o4.x
					dcl_temps 3
					iadd r0.x, v4.x, cb2[0].x
					ishl r0.x, r0.x, l(3)
					mul r1.xyzw, v0.yyyy, cb3[r0.x + 1].xyzw
					mad r1.xyzw, cb3[r0.x + 0].xyzw, v0.xxxx, r1.xyzw
					mad r1.xyzw, cb3[r0.x + 2].xyzw, v0.zzzz, r1.xyzw
					add r0.xyzw, r1.xyzw, cb3[r0.x + 3].xyzw
					mul r1.xyzw, r0.yyyy, cb1[18].xyzw
					mad r1.xyzw, cb1[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb1[19].xyzw, r0.zzzz, r1.xyzw
					mad r1.xyzw, cb1[20].xyzw, r0.wwww, r1.xyzw
					mov o0.xyzw, r1.xyzw
					mov o1.xyzw, v2.xyzw
					mul r1.y, r1.y, cb0[5].x
					mul r2.xzw, r1.xxwy, l(0.500000, 0.000000, 0.500000, 0.500000)
					mov o2.zw, r1.zzzw
					add o2.xy, r2.zzzz, r2.xwxx
					mul r1.xyz, r0.yyyy, cb1[10].xyzx
					mad r1.xyz, cb1[9].xyzx, r0.xxxx, r1.xyzx
					mad r0.xyz, cb1[11].xyzx, r0.zzzz, r1.xyzx
					mad r0.xyz, cb1[12].xyzx, r0.wwww, r0.xyzx
					mul o3.xyz, r0.xyzx, l(-1.000000, -1.000000, 1.000000, 0.000000)
					mov o4.x, v4.x
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "INSTANCING_ON" "_BLENDMODE_ADD" "USE_QUAD_DECAL" }
					"!!vs_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// NORMAL                   0   xyzw        1     NONE   float       
					// COLOR                    0   xyzw        2     NONE   float   xyzw
					// TEXCOORD                 0   xyzw        3     NONE   float       
					// SV_InstanceID            0   x           4   INSTID    uint   x   
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xyzw        2     NONE   float   xyzw
					// TEXCOORD                 1   xyz         3     NONE   float   xyz 
					// TEXCOORD                 2   xy          4     NONE   float   xy  
					// SV_InstanceID            0   x           5     NONE    uint   x   
					//
					vs_4_0
					dcl_constantbuffer CB0[6], immediateIndexed
					dcl_constantbuffer CB1[21], immediateIndexed
					dcl_constantbuffer CB2[1], immediateIndexed
					dcl_constantbuffer CB3[12], dynamicIndexed
					dcl_input v0.xyz
					dcl_input v2.xyzw
					dcl_input_sgv v4.x, instance_id
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xyzw
					dcl_output o3.xyz
					dcl_output o4.xy
					dcl_output o5.x
					dcl_temps 3
					iadd r0.x, v4.x, cb2[0].x
					ishl r0.x, r0.x, l(3)
					mul r1.xyzw, v0.yyyy, cb3[r0.x + 1].xyzw
					mad r1.xyzw, cb3[r0.x + 0].xyzw, v0.xxxx, r1.xyzw
					mad r1.xyzw, cb3[r0.x + 2].xyzw, v0.zzzz, r1.xyzw
					add r0.xyzw, r1.xyzw, cb3[r0.x + 3].xyzw
					mul r1.xyzw, r0.yyyy, cb1[18].xyzw
					mad r1.xyzw, cb1[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb1[19].xyzw, r0.zzzz, r1.xyzw
					mad r1.xyzw, cb1[20].xyzw, r0.wwww, r1.xyzw
					mov o0.xyzw, r1.xyzw
					mov o1.xyzw, v2.xyzw
					mul r1.y, r1.y, cb0[5].x
					mul r2.xzw, r1.xxwy, l(0.500000, 0.000000, 0.500000, 0.500000)
					mov o2.zw, r1.zzzw
					add o2.xy, r2.zzzz, r2.xwxx
					mul r1.xyz, r0.yyyy, cb1[10].xyzx
					mad r1.xyz, cb1[9].xyzx, r0.xxxx, r1.xyzx
					mad r0.xyz, cb1[11].xyzx, r0.zzzz, r1.xyzx
					mad r0.xyz, cb1[12].xyzx, r0.wwww, r0.xyzx
					mul o3.xyz, r0.xyzx, l(-1.000000, -1.000000, 1.000000, 0.000000)
					add o4.xy, v0.xzxx, l(0.500000, 0.500000, 0.000000, 0.000000)
					mov o5.x, v4.x
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "INSTANCING_ON" "USE_NOISE_DISTORTION" "USE_CUTOUT" "USE_CUTOUT_TEX" "_BLENDMODE_ADD" "USE_QUAD_DECAL" "USE_ALPHA_POW" }
					"!!vs_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// NORMAL                   0   xyzw        1     NONE   float       
					// COLOR                    0   xyzw        2     NONE   float   xyzw
					// TEXCOORD                 0   xyzw        3     NONE   float       
					// SV_InstanceID            0   x           4   INSTID    uint   x   
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xyzw        2     NONE   float   xyzw
					// TEXCOORD                 1   xyz         3     NONE   float   xyz 
					// TEXCOORD                 2   xy          4     NONE   float   xy  
					// SV_InstanceID            0   x           5     NONE    uint   x   
					//
					vs_4_0
					dcl_constantbuffer CB0[6], immediateIndexed
					dcl_constantbuffer CB1[21], immediateIndexed
					dcl_constantbuffer CB2[1], immediateIndexed
					dcl_constantbuffer CB3[12], dynamicIndexed
					dcl_input v0.xyz
					dcl_input v2.xyzw
					dcl_input_sgv v4.x, instance_id
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xyzw
					dcl_output o3.xyz
					dcl_output o4.xy
					dcl_output o5.x
					dcl_temps 3
					iadd r0.x, v4.x, cb2[0].x
					ishl r0.x, r0.x, l(3)
					mul r1.xyzw, v0.yyyy, cb3[r0.x + 1].xyzw
					mad r1.xyzw, cb3[r0.x + 0].xyzw, v0.xxxx, r1.xyzw
					mad r1.xyzw, cb3[r0.x + 2].xyzw, v0.zzzz, r1.xyzw
					add r0.xyzw, r1.xyzw, cb3[r0.x + 3].xyzw
					mul r1.xyzw, r0.yyyy, cb1[18].xyzw
					mad r1.xyzw, cb1[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb1[19].xyzw, r0.zzzz, r1.xyzw
					mad r1.xyzw, cb1[20].xyzw, r0.wwww, r1.xyzw
					mov o0.xyzw, r1.xyzw
					mov o1.xyzw, v2.xyzw
					mul r1.y, r1.y, cb0[5].x
					mul r2.xzw, r1.xxwy, l(0.500000, 0.000000, 0.500000, 0.500000)
					mov o2.zw, r1.zzzw
					add o2.xy, r2.zzzz, r2.xwxx
					mul r1.xyz, r0.yyyy, cb1[10].xyzx
					mad r1.xyz, cb1[9].xyzx, r0.xxxx, r1.xyzx
					mad r0.xyz, cb1[11].xyzx, r0.zzzz, r1.xyzx
					mad r0.xyz, cb1[12].xyzx, r0.wwww, r0.xyzx
					mul o3.xyz, r0.xyzx, l(-1.000000, -1.000000, 1.000000, 0.000000)
					add o4.xy, v0.xzxx, l(0.500000, 0.500000, 0.000000, 0.000000)
					mov o5.x, v4.x
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "_BLENDMODE_BLEND" }
					"!!vs_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// NORMAL                   0   xyzw        1     NONE   float       
					// COLOR                    0   xyzw        2     NONE   float   xyzw
					// TEXCOORD                 0   xyzw        3     NONE   float       
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xyzw        2     NONE   float   xyzw
					// TEXCOORD                 1   xyz         3     NONE   float   xyz 
					//
					vs_4_0
					dcl_constantbuffer CB0[6], immediateIndexed
					dcl_constantbuffer CB1[4], immediateIndexed
					dcl_constantbuffer CB2[21], immediateIndexed
					dcl_input v0.xyz
					dcl_input v2.xyzw
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xyzw
					dcl_output o3.xyz
					dcl_temps 3
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					add r0.xyzw, r0.xyzw, cb1[3].xyzw
					mul r1.xyzw, r0.yyyy, cb2[18].xyzw
					mad r1.xyzw, cb2[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb2[19].xyzw, r0.zzzz, r1.xyzw
					mad r1.xyzw, cb2[20].xyzw, r0.wwww, r1.xyzw
					mov o0.xyzw, r1.xyzw
					mov o1.xyzw, v2.xyzw
					mul r1.y, r1.y, cb0[5].x
					mul r2.xzw, r1.xxwy, l(0.500000, 0.000000, 0.500000, 0.500000)
					mov o2.zw, r1.zzzw
					add o2.xy, r2.zzzz, r2.xwxx
					mul r1.xyz, r0.yyyy, cb2[10].xyzx
					mad r1.xyz, cb2[9].xyzx, r0.xxxx, r1.xyzx
					mad r0.xyz, cb2[11].xyzx, r0.zzzz, r1.xyzx
					mad r0.xyz, cb2[12].xyzx, r0.wwww, r0.xyzx
					mul o3.xyz, r0.xyzx, l(-1.000000, -1.000000, 1.000000, 0.000000)
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "_BLENDMODE_BLEND" "USE_QUAD_DECAL" }
					"!!vs_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// NORMAL                   0   xyzw        1     NONE   float       
					// COLOR                    0   xyzw        2     NONE   float   xyzw
					// TEXCOORD                 0   xyzw        3     NONE   float       
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xyzw        2     NONE   float   xyzw
					// TEXCOORD                 1   xyz         3     NONE   float   xyz 
					// TEXCOORD                 2   xy          4     NONE   float   xy  
					//
					vs_4_0
					dcl_constantbuffer CB0[6], immediateIndexed
					dcl_constantbuffer CB1[4], immediateIndexed
					dcl_constantbuffer CB2[21], immediateIndexed
					dcl_input v0.xyz
					dcl_input v2.xyzw
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xyzw
					dcl_output o3.xyz
					dcl_output o4.xy
					dcl_temps 3
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					add r0.xyzw, r0.xyzw, cb1[3].xyzw
					mul r1.xyzw, r0.yyyy, cb2[18].xyzw
					mad r1.xyzw, cb2[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb2[19].xyzw, r0.zzzz, r1.xyzw
					mad r1.xyzw, cb2[20].xyzw, r0.wwww, r1.xyzw
					mov o0.xyzw, r1.xyzw
					mov o1.xyzw, v2.xyzw
					mul r1.y, r1.y, cb0[5].x
					mul r2.xzw, r1.xxwy, l(0.500000, 0.000000, 0.500000, 0.500000)
					mov o2.zw, r1.zzzw
					add o2.xy, r2.zzzz, r2.xwxx
					mul r1.xyz, r0.yyyy, cb2[10].xyzx
					mad r1.xyz, cb2[9].xyzx, r0.xxxx, r1.xyzx
					mad r0.xyz, cb2[11].xyzx, r0.zzzz, r1.xyzx
					mad r0.xyz, cb2[12].xyzx, r0.wwww, r0.xyzx
					mul o3.xyz, r0.xyzx, l(-1.000000, -1.000000, 1.000000, 0.000000)
					add o4.xy, v0.xzxx, l(0.500000, 0.500000, 0.000000, 0.000000)
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "USE_NOISE_DISTORTION" "USE_CUTOUT" "USE_CUTOUT_TEX" "_BLENDMODE_BLEND" "USE_QUAD_DECAL" "USE_ALPHA_POW" }
					"!!vs_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// NORMAL                   0   xyzw        1     NONE   float       
					// COLOR                    0   xyzw        2     NONE   float   xyzw
					// TEXCOORD                 0   xyzw        3     NONE   float       
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xyzw        2     NONE   float   xyzw
					// TEXCOORD                 1   xyz         3     NONE   float   xyz 
					// TEXCOORD                 2   xy          4     NONE   float   xy  
					//
					vs_4_0
					dcl_constantbuffer CB0[6], immediateIndexed
					dcl_constantbuffer CB1[4], immediateIndexed
					dcl_constantbuffer CB2[21], immediateIndexed
					dcl_input v0.xyz
					dcl_input v2.xyzw
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xyzw
					dcl_output o3.xyz
					dcl_output o4.xy
					dcl_temps 3
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					add r0.xyzw, r0.xyzw, cb1[3].xyzw
					mul r1.xyzw, r0.yyyy, cb2[18].xyzw
					mad r1.xyzw, cb2[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb2[19].xyzw, r0.zzzz, r1.xyzw
					mad r1.xyzw, cb2[20].xyzw, r0.wwww, r1.xyzw
					mov o0.xyzw, r1.xyzw
					mov o1.xyzw, v2.xyzw
					mul r1.y, r1.y, cb0[5].x
					mul r2.xzw, r1.xxwy, l(0.500000, 0.000000, 0.500000, 0.500000)
					mov o2.zw, r1.zzzw
					add o2.xy, r2.zzzz, r2.xwxx
					mul r1.xyz, r0.yyyy, cb2[10].xyzx
					mad r1.xyz, cb2[9].xyzx, r0.xxxx, r1.xyzx
					mad r0.xyz, cb2[11].xyzx, r0.zzzz, r1.xyzx
					mad r0.xyz, cb2[12].xyzx, r0.wwww, r0.xyzx
					mul o3.xyz, r0.xyzx, l(-1.000000, -1.000000, 1.000000, 0.000000)
					add o4.xy, v0.xzxx, l(0.500000, 0.500000, 0.000000, 0.000000)
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "INSTANCING_ON" "_BLENDMODE_BLEND" }
					"!!vs_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// NORMAL                   0   xyzw        1     NONE   float       
					// COLOR                    0   xyzw        2     NONE   float   xyzw
					// TEXCOORD                 0   xyzw        3     NONE   float       
					// SV_InstanceID            0   x           4   INSTID    uint   x   
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xyzw        2     NONE   float   xyzw
					// TEXCOORD                 1   xyz         3     NONE   float   xyz 
					// SV_InstanceID            0   x           4     NONE    uint   x   
					//
					vs_4_0
					dcl_constantbuffer CB0[6], immediateIndexed
					dcl_constantbuffer CB1[21], immediateIndexed
					dcl_constantbuffer CB2[1], immediateIndexed
					dcl_constantbuffer CB3[12], dynamicIndexed
					dcl_input v0.xyz
					dcl_input v2.xyzw
					dcl_input_sgv v4.x, instance_id
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xyzw
					dcl_output o3.xyz
					dcl_output o4.x
					dcl_temps 3
					iadd r0.x, v4.x, cb2[0].x
					ishl r0.x, r0.x, l(3)
					mul r1.xyzw, v0.yyyy, cb3[r0.x + 1].xyzw
					mad r1.xyzw, cb3[r0.x + 0].xyzw, v0.xxxx, r1.xyzw
					mad r1.xyzw, cb3[r0.x + 2].xyzw, v0.zzzz, r1.xyzw
					add r0.xyzw, r1.xyzw, cb3[r0.x + 3].xyzw
					mul r1.xyzw, r0.yyyy, cb1[18].xyzw
					mad r1.xyzw, cb1[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb1[19].xyzw, r0.zzzz, r1.xyzw
					mad r1.xyzw, cb1[20].xyzw, r0.wwww, r1.xyzw
					mov o0.xyzw, r1.xyzw
					mov o1.xyzw, v2.xyzw
					mul r1.y, r1.y, cb0[5].x
					mul r2.xzw, r1.xxwy, l(0.500000, 0.000000, 0.500000, 0.500000)
					mov o2.zw, r1.zzzw
					add o2.xy, r2.zzzz, r2.xwxx
					mul r1.xyz, r0.yyyy, cb1[10].xyzx
					mad r1.xyz, cb1[9].xyzx, r0.xxxx, r1.xyzx
					mad r0.xyz, cb1[11].xyzx, r0.zzzz, r1.xyzx
					mad r0.xyz, cb1[12].xyzx, r0.wwww, r0.xyzx
					mul o3.xyz, r0.xyzx, l(-1.000000, -1.000000, 1.000000, 0.000000)
					mov o4.x, v4.x
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "INSTANCING_ON" "_BLENDMODE_BLEND" "USE_QUAD_DECAL" }
					"!!vs_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// NORMAL                   0   xyzw        1     NONE   float       
					// COLOR                    0   xyzw        2     NONE   float   xyzw
					// TEXCOORD                 0   xyzw        3     NONE   float       
					// SV_InstanceID            0   x           4   INSTID    uint   x   
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xyzw        2     NONE   float   xyzw
					// TEXCOORD                 1   xyz         3     NONE   float   xyz 
					// TEXCOORD                 2   xy          4     NONE   float   xy  
					// SV_InstanceID            0   x           5     NONE    uint   x   
					//
					vs_4_0
					dcl_constantbuffer CB0[6], immediateIndexed
					dcl_constantbuffer CB1[21], immediateIndexed
					dcl_constantbuffer CB2[1], immediateIndexed
					dcl_constantbuffer CB3[12], dynamicIndexed
					dcl_input v0.xyz
					dcl_input v2.xyzw
					dcl_input_sgv v4.x, instance_id
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xyzw
					dcl_output o3.xyz
					dcl_output o4.xy
					dcl_output o5.x
					dcl_temps 3
					iadd r0.x, v4.x, cb2[0].x
					ishl r0.x, r0.x, l(3)
					mul r1.xyzw, v0.yyyy, cb3[r0.x + 1].xyzw
					mad r1.xyzw, cb3[r0.x + 0].xyzw, v0.xxxx, r1.xyzw
					mad r1.xyzw, cb3[r0.x + 2].xyzw, v0.zzzz, r1.xyzw
					add r0.xyzw, r1.xyzw, cb3[r0.x + 3].xyzw
					mul r1.xyzw, r0.yyyy, cb1[18].xyzw
					mad r1.xyzw, cb1[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb1[19].xyzw, r0.zzzz, r1.xyzw
					mad r1.xyzw, cb1[20].xyzw, r0.wwww, r1.xyzw
					mov o0.xyzw, r1.xyzw
					mov o1.xyzw, v2.xyzw
					mul r1.y, r1.y, cb0[5].x
					mul r2.xzw, r1.xxwy, l(0.500000, 0.000000, 0.500000, 0.500000)
					mov o2.zw, r1.zzzw
					add o2.xy, r2.zzzz, r2.xwxx
					mul r1.xyz, r0.yyyy, cb1[10].xyzx
					mad r1.xyz, cb1[9].xyzx, r0.xxxx, r1.xyzx
					mad r0.xyz, cb1[11].xyzx, r0.zzzz, r1.xyzx
					mad r0.xyz, cb1[12].xyzx, r0.wwww, r0.xyzx
					mul o3.xyz, r0.xyzx, l(-1.000000, -1.000000, 1.000000, 0.000000)
					add o4.xy, v0.xzxx, l(0.500000, 0.500000, 0.000000, 0.000000)
					mov o5.x, v4.x
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "INSTANCING_ON" "USE_NOISE_DISTORTION" "USE_CUTOUT" "USE_CUTOUT_TEX" "_BLENDMODE_BLEND" "USE_QUAD_DECAL" "USE_ALPHA_POW" }
					"!!vs_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// NORMAL                   0   xyzw        1     NONE   float       
					// COLOR                    0   xyzw        2     NONE   float   xyzw
					// TEXCOORD                 0   xyzw        3     NONE   float       
					// SV_InstanceID            0   x           4   INSTID    uint   x   
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xyzw        2     NONE   float   xyzw
					// TEXCOORD                 1   xyz         3     NONE   float   xyz 
					// TEXCOORD                 2   xy          4     NONE   float   xy  
					// SV_InstanceID            0   x           5     NONE    uint   x   
					//
					vs_4_0
					dcl_constantbuffer CB0[6], immediateIndexed
					dcl_constantbuffer CB1[21], immediateIndexed
					dcl_constantbuffer CB2[1], immediateIndexed
					dcl_constantbuffer CB3[12], dynamicIndexed
					dcl_input v0.xyz
					dcl_input v2.xyzw
					dcl_input_sgv v4.x, instance_id
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xyzw
					dcl_output o3.xyz
					dcl_output o4.xy
					dcl_output o5.x
					dcl_temps 3
					iadd r0.x, v4.x, cb2[0].x
					ishl r0.x, r0.x, l(3)
					mul r1.xyzw, v0.yyyy, cb3[r0.x + 1].xyzw
					mad r1.xyzw, cb3[r0.x + 0].xyzw, v0.xxxx, r1.xyzw
					mad r1.xyzw, cb3[r0.x + 2].xyzw, v0.zzzz, r1.xyzw
					add r0.xyzw, r1.xyzw, cb3[r0.x + 3].xyzw
					mul r1.xyzw, r0.yyyy, cb1[18].xyzw
					mad r1.xyzw, cb1[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb1[19].xyzw, r0.zzzz, r1.xyzw
					mad r1.xyzw, cb1[20].xyzw, r0.wwww, r1.xyzw
					mov o0.xyzw, r1.xyzw
					mov o1.xyzw, v2.xyzw
					mul r1.y, r1.y, cb0[5].x
					mul r2.xzw, r1.xxwy, l(0.500000, 0.000000, 0.500000, 0.500000)
					mov o2.zw, r1.zzzw
					add o2.xy, r2.zzzz, r2.xwxx
					mul r1.xyz, r0.yyyy, cb1[10].xyzx
					mad r1.xyz, cb1[9].xyzx, r0.xxxx, r1.xyzx
					mad r0.xyz, cb1[11].xyzx, r0.zzzz, r1.xyzx
					mad r0.xyz, cb1[12].xyzx, r0.wwww, r0.xyzx
					mul o3.xyz, r0.xyzx, l(-1.000000, -1.000000, 1.000000, 0.000000)
					add o4.xy, v0.xzxx, l(0.500000, 0.500000, 0.000000, 0.000000)
					mov o5.x, v4.x
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "_BLENDMODE_MUL" }
					"!!vs_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// NORMAL                   0   xyzw        1     NONE   float       
					// COLOR                    0   xyzw        2     NONE   float   xyzw
					// TEXCOORD                 0   xyzw        3     NONE   float       
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xyzw        2     NONE   float   xyzw
					// TEXCOORD                 1   xyz         3     NONE   float   xyz 
					//
					vs_4_0
					dcl_constantbuffer CB0[6], immediateIndexed
					dcl_constantbuffer CB1[4], immediateIndexed
					dcl_constantbuffer CB2[21], immediateIndexed
					dcl_input v0.xyz
					dcl_input v2.xyzw
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xyzw
					dcl_output o3.xyz
					dcl_temps 3
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					add r0.xyzw, r0.xyzw, cb1[3].xyzw
					mul r1.xyzw, r0.yyyy, cb2[18].xyzw
					mad r1.xyzw, cb2[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb2[19].xyzw, r0.zzzz, r1.xyzw
					mad r1.xyzw, cb2[20].xyzw, r0.wwww, r1.xyzw
					mov o0.xyzw, r1.xyzw
					mov o1.xyzw, v2.xyzw
					mul r1.y, r1.y, cb0[5].x
					mul r2.xzw, r1.xxwy, l(0.500000, 0.000000, 0.500000, 0.500000)
					mov o2.zw, r1.zzzw
					add o2.xy, r2.zzzz, r2.xwxx
					mul r1.xyz, r0.yyyy, cb2[10].xyzx
					mad r1.xyz, cb2[9].xyzx, r0.xxxx, r1.xyzx
					mad r0.xyz, cb2[11].xyzx, r0.zzzz, r1.xyzx
					mad r0.xyz, cb2[12].xyzx, r0.wwww, r0.xyzx
					mul o3.xyz, r0.xyzx, l(-1.000000, -1.000000, 1.000000, 0.000000)
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "_BLENDMODE_MUL" "USE_QUAD_DECAL" }
					"!!vs_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// NORMAL                   0   xyzw        1     NONE   float       
					// COLOR                    0   xyzw        2     NONE   float   xyzw
					// TEXCOORD                 0   xyzw        3     NONE   float       
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xyzw        2     NONE   float   xyzw
					// TEXCOORD                 1   xyz         3     NONE   float   xyz 
					// TEXCOORD                 2   xy          4     NONE   float   xy  
					//
					vs_4_0
					dcl_constantbuffer CB0[6], immediateIndexed
					dcl_constantbuffer CB1[4], immediateIndexed
					dcl_constantbuffer CB2[21], immediateIndexed
					dcl_input v0.xyz
					dcl_input v2.xyzw
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xyzw
					dcl_output o3.xyz
					dcl_output o4.xy
					dcl_temps 3
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					add r0.xyzw, r0.xyzw, cb1[3].xyzw
					mul r1.xyzw, r0.yyyy, cb2[18].xyzw
					mad r1.xyzw, cb2[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb2[19].xyzw, r0.zzzz, r1.xyzw
					mad r1.xyzw, cb2[20].xyzw, r0.wwww, r1.xyzw
					mov o0.xyzw, r1.xyzw
					mov o1.xyzw, v2.xyzw
					mul r1.y, r1.y, cb0[5].x
					mul r2.xzw, r1.xxwy, l(0.500000, 0.000000, 0.500000, 0.500000)
					mov o2.zw, r1.zzzw
					add o2.xy, r2.zzzz, r2.xwxx
					mul r1.xyz, r0.yyyy, cb2[10].xyzx
					mad r1.xyz, cb2[9].xyzx, r0.xxxx, r1.xyzx
					mad r0.xyz, cb2[11].xyzx, r0.zzzz, r1.xyzx
					mad r0.xyz, cb2[12].xyzx, r0.wwww, r0.xyzx
					mul o3.xyz, r0.xyzx, l(-1.000000, -1.000000, 1.000000, 0.000000)
					add o4.xy, v0.xzxx, l(0.500000, 0.500000, 0.000000, 0.000000)
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "USE_NOISE_DISTORTION" "USE_CUTOUT" "USE_CUTOUT_TEX" "_BLENDMODE_MUL" "USE_QUAD_DECAL" "USE_ALPHA_POW" }
					"!!vs_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// NORMAL                   0   xyzw        1     NONE   float       
					// COLOR                    0   xyzw        2     NONE   float   xyzw
					// TEXCOORD                 0   xyzw        3     NONE   float       
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xyzw        2     NONE   float   xyzw
					// TEXCOORD                 1   xyz         3     NONE   float   xyz 
					// TEXCOORD                 2   xy          4     NONE   float   xy  
					//
					vs_4_0
					dcl_constantbuffer CB0[6], immediateIndexed
					dcl_constantbuffer CB1[4], immediateIndexed
					dcl_constantbuffer CB2[21], immediateIndexed
					dcl_input v0.xyz
					dcl_input v2.xyzw
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xyzw
					dcl_output o3.xyz
					dcl_output o4.xy
					dcl_temps 3
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					add r0.xyzw, r0.xyzw, cb1[3].xyzw
					mul r1.xyzw, r0.yyyy, cb2[18].xyzw
					mad r1.xyzw, cb2[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb2[19].xyzw, r0.zzzz, r1.xyzw
					mad r1.xyzw, cb2[20].xyzw, r0.wwww, r1.xyzw
					mov o0.xyzw, r1.xyzw
					mov o1.xyzw, v2.xyzw
					mul r1.y, r1.y, cb0[5].x
					mul r2.xzw, r1.xxwy, l(0.500000, 0.000000, 0.500000, 0.500000)
					mov o2.zw, r1.zzzw
					add o2.xy, r2.zzzz, r2.xwxx
					mul r1.xyz, r0.yyyy, cb2[10].xyzx
					mad r1.xyz, cb2[9].xyzx, r0.xxxx, r1.xyzx
					mad r0.xyz, cb2[11].xyzx, r0.zzzz, r1.xyzx
					mad r0.xyz, cb2[12].xyzx, r0.wwww, r0.xyzx
					mul o3.xyz, r0.xyzx, l(-1.000000, -1.000000, 1.000000, 0.000000)
					add o4.xy, v0.xzxx, l(0.500000, 0.500000, 0.000000, 0.000000)
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "INSTANCING_ON" "_BLENDMODE_MUL" }
					"!!vs_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// NORMAL                   0   xyzw        1     NONE   float       
					// COLOR                    0   xyzw        2     NONE   float   xyzw
					// TEXCOORD                 0   xyzw        3     NONE   float       
					// SV_InstanceID            0   x           4   INSTID    uint   x   
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xyzw        2     NONE   float   xyzw
					// TEXCOORD                 1   xyz         3     NONE   float   xyz 
					// SV_InstanceID            0   x           4     NONE    uint   x   
					//
					vs_4_0
					dcl_constantbuffer CB0[6], immediateIndexed
					dcl_constantbuffer CB1[21], immediateIndexed
					dcl_constantbuffer CB2[1], immediateIndexed
					dcl_constantbuffer CB3[12], dynamicIndexed
					dcl_input v0.xyz
					dcl_input v2.xyzw
					dcl_input_sgv v4.x, instance_id
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xyzw
					dcl_output o3.xyz
					dcl_output o4.x
					dcl_temps 3
					iadd r0.x, v4.x, cb2[0].x
					ishl r0.x, r0.x, l(3)
					mul r1.xyzw, v0.yyyy, cb3[r0.x + 1].xyzw
					mad r1.xyzw, cb3[r0.x + 0].xyzw, v0.xxxx, r1.xyzw
					mad r1.xyzw, cb3[r0.x + 2].xyzw, v0.zzzz, r1.xyzw
					add r0.xyzw, r1.xyzw, cb3[r0.x + 3].xyzw
					mul r1.xyzw, r0.yyyy, cb1[18].xyzw
					mad r1.xyzw, cb1[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb1[19].xyzw, r0.zzzz, r1.xyzw
					mad r1.xyzw, cb1[20].xyzw, r0.wwww, r1.xyzw
					mov o0.xyzw, r1.xyzw
					mov o1.xyzw, v2.xyzw
					mul r1.y, r1.y, cb0[5].x
					mul r2.xzw, r1.xxwy, l(0.500000, 0.000000, 0.500000, 0.500000)
					mov o2.zw, r1.zzzw
					add o2.xy, r2.zzzz, r2.xwxx
					mul r1.xyz, r0.yyyy, cb1[10].xyzx
					mad r1.xyz, cb1[9].xyzx, r0.xxxx, r1.xyzx
					mad r0.xyz, cb1[11].xyzx, r0.zzzz, r1.xyzx
					mad r0.xyz, cb1[12].xyzx, r0.wwww, r0.xyzx
					mul o3.xyz, r0.xyzx, l(-1.000000, -1.000000, 1.000000, 0.000000)
					mov o4.x, v4.x
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "INSTANCING_ON" "_BLENDMODE_MUL" "USE_QUAD_DECAL" }
					"!!vs_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// NORMAL                   0   xyzw        1     NONE   float       
					// COLOR                    0   xyzw        2     NONE   float   xyzw
					// TEXCOORD                 0   xyzw        3     NONE   float       
					// SV_InstanceID            0   x           4   INSTID    uint   x   
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xyzw        2     NONE   float   xyzw
					// TEXCOORD                 1   xyz         3     NONE   float   xyz 
					// TEXCOORD                 2   xy          4     NONE   float   xy  
					// SV_InstanceID            0   x           5     NONE    uint   x   
					//
					vs_4_0
					dcl_constantbuffer CB0[6], immediateIndexed
					dcl_constantbuffer CB1[21], immediateIndexed
					dcl_constantbuffer CB2[1], immediateIndexed
					dcl_constantbuffer CB3[12], dynamicIndexed
					dcl_input v0.xyz
					dcl_input v2.xyzw
					dcl_input_sgv v4.x, instance_id
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xyzw
					dcl_output o3.xyz
					dcl_output o4.xy
					dcl_output o5.x
					dcl_temps 3
					iadd r0.x, v4.x, cb2[0].x
					ishl r0.x, r0.x, l(3)
					mul r1.xyzw, v0.yyyy, cb3[r0.x + 1].xyzw
					mad r1.xyzw, cb3[r0.x + 0].xyzw, v0.xxxx, r1.xyzw
					mad r1.xyzw, cb3[r0.x + 2].xyzw, v0.zzzz, r1.xyzw
					add r0.xyzw, r1.xyzw, cb3[r0.x + 3].xyzw
					mul r1.xyzw, r0.yyyy, cb1[18].xyzw
					mad r1.xyzw, cb1[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb1[19].xyzw, r0.zzzz, r1.xyzw
					mad r1.xyzw, cb1[20].xyzw, r0.wwww, r1.xyzw
					mov o0.xyzw, r1.xyzw
					mov o1.xyzw, v2.xyzw
					mul r1.y, r1.y, cb0[5].x
					mul r2.xzw, r1.xxwy, l(0.500000, 0.000000, 0.500000, 0.500000)
					mov o2.zw, r1.zzzw
					add o2.xy, r2.zzzz, r2.xwxx
					mul r1.xyz, r0.yyyy, cb1[10].xyzx
					mad r1.xyz, cb1[9].xyzx, r0.xxxx, r1.xyzx
					mad r0.xyz, cb1[11].xyzx, r0.zzzz, r1.xyzx
					mad r0.xyz, cb1[12].xyzx, r0.wwww, r0.xyzx
					mul o3.xyz, r0.xyzx, l(-1.000000, -1.000000, 1.000000, 0.000000)
					add o4.xy, v0.xzxx, l(0.500000, 0.500000, 0.000000, 0.000000)
					mov o5.x, v4.x
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "INSTANCING_ON" "USE_NOISE_DISTORTION" "USE_CUTOUT" "USE_CUTOUT_TEX" "_BLENDMODE_MUL" "USE_QUAD_DECAL" "USE_ALPHA_POW" }
					"!!vs_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// NORMAL                   0   xyzw        1     NONE   float       
					// COLOR                    0   xyzw        2     NONE   float   xyzw
					// TEXCOORD                 0   xyzw        3     NONE   float       
					// SV_InstanceID            0   x           4   INSTID    uint   x   
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xyzw        2     NONE   float   xyzw
					// TEXCOORD                 1   xyz         3     NONE   float   xyz 
					// TEXCOORD                 2   xy          4     NONE   float   xy  
					// SV_InstanceID            0   x           5     NONE    uint   x   
					//
					vs_4_0
					dcl_constantbuffer CB0[6], immediateIndexed
					dcl_constantbuffer CB1[21], immediateIndexed
					dcl_constantbuffer CB2[1], immediateIndexed
					dcl_constantbuffer CB3[12], dynamicIndexed
					dcl_input v0.xyz
					dcl_input v2.xyzw
					dcl_input_sgv v4.x, instance_id
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xyzw
					dcl_output o3.xyz
					dcl_output o4.xy
					dcl_output o5.x
					dcl_temps 3
					iadd r0.x, v4.x, cb2[0].x
					ishl r0.x, r0.x, l(3)
					mul r1.xyzw, v0.yyyy, cb3[r0.x + 1].xyzw
					mad r1.xyzw, cb3[r0.x + 0].xyzw, v0.xxxx, r1.xyzw
					mad r1.xyzw, cb3[r0.x + 2].xyzw, v0.zzzz, r1.xyzw
					add r0.xyzw, r1.xyzw, cb3[r0.x + 3].xyzw
					mul r1.xyzw, r0.yyyy, cb1[18].xyzw
					mad r1.xyzw, cb1[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb1[19].xyzw, r0.zzzz, r1.xyzw
					mad r1.xyzw, cb1[20].xyzw, r0.wwww, r1.xyzw
					mov o0.xyzw, r1.xyzw
					mov o1.xyzw, v2.xyzw
					mul r1.y, r1.y, cb0[5].x
					mul r2.xzw, r1.xxwy, l(0.500000, 0.000000, 0.500000, 0.500000)
					mov o2.zw, r1.zzzw
					add o2.xy, r2.zzzz, r2.xwxx
					mul r1.xyz, r0.yyyy, cb1[10].xyzx
					mad r1.xyz, cb1[9].xyzx, r0.xxxx, r1.xyzx
					mad r0.xyz, cb1[11].xyzx, r0.zzzz, r1.xyzx
					mad r0.xyz, cb1[12].xyzx, r0.wwww, r0.xyzx
					mul o3.xyz, r0.xyzx, l(-1.000000, -1.000000, 1.000000, 0.000000)
					add o4.xy, v0.xzxx, l(0.500000, 0.500000, 0.000000, 0.000000)
					mov o5.x, v4.x
					ret 
					// Approximately 0 instruction slots used"
				}
			}
			Program "fp" {
				SubProgram "d3d11 " {
					Keywords { "_BLENDMODE_ADD" }
					"!!ps_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// COLOR                    0   xyzw        1     NONE   float       
					// TEXCOORD                 0   xyzw        2     NONE   float   xy w
					// TEXCOORD                 1   xyz         3     NONE   float   xyz 
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[3], immediateIndexed
					dcl_constantbuffer CB1[8], immediateIndexed
					dcl_constantbuffer CB2[22], immediateIndexed
					dcl_constantbuffer CB3[5], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_sampler s1, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_resource_texture2d (float,float,float,float) t1
					dcl_input_ps linear v2.xyw
					dcl_input_ps linear v3.xyz
					dcl_output o0.xyzw
					dcl_temps 2
					div r0.xy, v2.xyxx, v2.wwww
					sample r0.xyzw, r0.xyxx, t0.xyzw, s1
					mad r0.x, cb1[7].x, r0.x, cb1[7].y
					div r0.x, l(1.000000, 1.000000, 1.000000, 1.000000), r0.x
					div r0.y, cb1[5].z, v3.z
					mul r0.yzw, r0.yyyy, v3.xxyz
					mul r0.xyz, r0.xxxx, r0.yzwy
					mul r1.xyz, r0.yyyy, cb2[19].xyzx
					mad r0.xyw, cb2[18].xyxz, r0.xxxx, r1.xyxz
					mad r0.xyz, cb2[20].xyzx, r0.zzzz, r0.xywx
					add r0.xyz, r0.xyzx, cb2[21].xyzx
					mul r1.xyz, r0.yyyy, cb3[1].xyzx
					mad r0.xyw, cb3[0].xyxz, r0.xxxx, r1.xyxz
					mad r0.xyz, cb3[2].xyzx, r0.zzzz, r0.xywx
					add r0.xyz, r0.xyzx, cb3[3].xyzx
					add r1.xyz, -|r0.xyzx|, l(0.500000, 0.500000, 0.500000, 0.000000)
					mul_sat r1.xyz, r1.xyzx, l(10000.000000, 10000.000000, 10000.000000, 0.000000)
					mul r0.w, r1.y, r1.x
					mul r0.w, r1.z, r0.w
					add r0.y, r0.y, r0.y
					add r0.xz, r0.xxzx, l(0.500000, 0.000000, 0.500000, 0.000000)
					mad r0.xz, r0.xxzx, cb0[2].xxyx, cb0[2].zzwz
					sample r1.xyzw, r0.xzxx, t1.xyzw, s0
					mul r1.xyzw, r1.xyzw, cb3[4].xyzw
					add r0.x, -|r0.y|, l(1.000000)
					mul r0.x, r0.x, r0.w
					log r0.x, r0.x
					mul r0.x, r0.x, l(0.200000)
					exp r0.x, r0.x
					mul_sat o0.w, r0.x, r1.w
					add o0.xyz, r1.xyzx, r1.xyzx
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "_BLENDMODE_ADD" "USE_QUAD_DECAL" }
					"!!ps_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// COLOR                    0   xyzw        1     NONE   float       
					// TEXCOORD                 0   xyzw        2     NONE   float       
					// TEXCOORD                 1   xyz         3     NONE   float       
					// TEXCOORD                 2   xy          4     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[3], immediateIndexed
					dcl_constantbuffer CB1[5], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_input_ps linear v4.xy
					dcl_output o0.xyzw
					dcl_temps 1
					mad r0.xy, v4.xyxx, cb0[2].xyxx, cb0[2].zwzz
					sample r0.xyzw, r0.xyxx, t0.xyzw, s0
					mul r0.xyzw, r0.xyzw, cb1[4].xyzw
					add o0.xyz, r0.xyzx, r0.xyzx
					mov_sat o0.w, r0.w
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "USE_NOISE_DISTORTION" "USE_CUTOUT" "USE_CUTOUT_TEX" "_BLENDMODE_ADD" "USE_QUAD_DECAL" "USE_ALPHA_POW" }
					"!!ps_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// COLOR                    0   xyzw        1     NONE   float      w
					// TEXCOORD                 0   xyzw        2     NONE   float       
					// TEXCOORD                 1   xyz         3     NONE   float       
					// TEXCOORD                 2   xy          4     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[12], immediateIndexed
					dcl_constantbuffer CB1[1], immediateIndexed
					dcl_constantbuffer CB2[6], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_sampler s1, mode_default
					dcl_sampler s2, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_resource_texture2d (float,float,float,float) t1
					dcl_resource_texture2d (float,float,float,float) t2
					dcl_input_ps linear v1.w
					dcl_input_ps linear v4.xy
					dcl_output o0.xyzw
					dcl_temps 3
					add r0.xy, v4.xyxx, l(1.000000, 1.000000, 0.000000, 0.000000)
					mad r0.xy, r0.xyxx, cb0[5].xyxx, cb0[5].zwzz
					sample r0.xyzw, r0.xyxx, t2.xyzw, s2
					mad r0.x, -cb2[5].x, v1.w, l(1.000000)
					mad r0.x, r0.x, l(2.000000), l(-1.000000)
					add r0.x, -r0.x, r0.w
					mul_sat r0.x, r0.x, cb0[10].y
					mul r0.y, cb0[10].w, cb1[0].x
					mad r0.zw, v4.xxxy, cb0[4].xxxy, cb0[4].zzzw
					sample r1.xyzw, r0.zwzz, t0.xyzw, s1
					mad r0.zw, r1.xxxy, l(0.000000, 0.000000, 2.000000, 2.000000), l(0.000000, 0.000000, -1.000000, -1.000000)
					mad r1.xy, v4.xyxx, cb0[2].xyxx, cb0[2].zwzz
					mad r1.zw, -r0.zzzw, cb0[11].xxxx, r1.xxxy
					mad r0.zw, r0.zzzw, cb0[11].xxxx, r1.xxxy
					mad r0.zw, cb0[10].wwww, cb1[0].xxxx, r0.zzzw
					sample r2.xyzw, r0.zwzz, t1.xyzw, s0
					mad r0.yz, -r0.yyyy, l(0.000000, 1.400000, 1.400000, 0.000000), r1.zzwz
					sample r1.xyzw, r0.yzyy, t1.xyzw, s0
					mul r1.xyzw, r1.xyzw, r2.xyzw
					mul r1.xyzw, r1.xyzw, cb2[4].xyzw
					mul_sat r0.x, r0.x, r1.w
					add r0.yzw, r1.xxyz, r1.xxyz
					log r1.x, r0.x
					mov o0.w, r0.x
					mul r0.x, r1.x, cb0[10].z
					exp r0.x, r0.x
					mul o0.xyz, r0.xxxx, r0.yzwy
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "INSTANCING_ON" "_BLENDMODE_ADD" }
					"!!ps_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// COLOR                    0   xyzw        1     NONE   float       
					// TEXCOORD                 0   xyzw        2     NONE   float   xy w
					// TEXCOORD                 1   xyz         3     NONE   float   xyz 
					// SV_InstanceID            0   x           4     NONE    uint   x   
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[3], immediateIndexed
					dcl_constantbuffer CB1[8], immediateIndexed
					dcl_constantbuffer CB2[22], immediateIndexed
					dcl_constantbuffer CB3[1], immediateIndexed
					dcl_constantbuffer CB4[12], dynamicIndexed
					dcl_sampler s0, mode_default
					dcl_sampler s1, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_resource_texture2d (float,float,float,float) t1
					dcl_input_ps linear v2.xyw
					dcl_input_ps linear v3.xyz
					dcl_input_ps constant v4.x
					dcl_output o0.xyzw
					dcl_temps 3
					div r0.xy, v2.xyxx, v2.wwww
					sample r0.xyzw, r0.xyxx, t0.xyzw, s1
					mad r0.x, cb1[7].x, r0.x, cb1[7].y
					div r0.x, l(1.000000, 1.000000, 1.000000, 1.000000), r0.x
					div r0.y, cb1[5].z, v3.z
					mul r0.yzw, r0.yyyy, v3.xxyz
					mul r0.xyz, r0.xxxx, r0.yzwy
					mul r1.xyz, r0.yyyy, cb2[19].xyzx
					mad r0.xyw, cb2[18].xyxz, r0.xxxx, r1.xyxz
					mad r0.xyz, cb2[20].xyzx, r0.zzzz, r0.xywx
					add r0.xyz, r0.xyzx, cb2[21].xyzx
					iadd r0.w, v4.x, cb3[0].x
					imul null, r0.w, r0.w, l(6)
					mul r1.xyz, r0.yyyy, cb4[r0.w + 1].xyzx
					mad r1.xyz, cb4[r0.w + 0].xyzx, r0.xxxx, r1.xyzx
					mad r0.xyz, cb4[r0.w + 2].xyzx, r0.zzzz, r1.xyzx
					add r0.xyz, r0.xyzx, cb4[r0.w + 3].xyzx
					add r1.xyz, -|r0.xyzx|, l(0.500000, 0.500000, 0.500000, 0.000000)
					mul_sat r1.xyz, r1.xyzx, l(10000.000000, 10000.000000, 10000.000000, 0.000000)
					mul r1.x, r1.y, r1.x
					mul r1.x, r1.z, r1.x
					add r0.y, r0.y, r0.y
					add r0.xz, r0.xxzx, l(0.500000, 0.000000, 0.500000, 0.000000)
					mad r0.xz, r0.xxzx, cb0[2].xxyx, cb0[2].zzwz
					sample r2.xyzw, r0.xzxx, t1.xyzw, s0
					mul r2.xyzw, r2.xyzw, cb4[r0.w + 4].xyzw
					add r0.x, -|r0.y|, l(1.000000)
					mul r0.x, r0.x, r1.x
					log r0.x, r0.x
					mul r0.x, r0.x, l(0.200000)
					exp r0.x, r0.x
					mul_sat o0.w, r0.x, r2.w
					add o0.xyz, r2.xyzx, r2.xyzx
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "INSTANCING_ON" "_BLENDMODE_ADD" "USE_QUAD_DECAL" }
					"!!ps_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// COLOR                    0   xyzw        1     NONE   float       
					// TEXCOORD                 0   xyzw        2     NONE   float       
					// TEXCOORD                 1   xyz         3     NONE   float       
					// TEXCOORD                 2   xy          4     NONE   float   xy  
					// SV_InstanceID            0   x           5     NONE    uint   x   
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[3], immediateIndexed
					dcl_constantbuffer CB1[1], immediateIndexed
					dcl_constantbuffer CB2[11], dynamicIndexed
					dcl_sampler s0, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_input_ps linear v4.xy
					dcl_input_ps constant v5.x
					dcl_output o0.xyzw
					dcl_temps 2
					mad r0.xy, v4.xyxx, cb0[2].xyxx, cb0[2].zwzz
					sample r0.xyzw, r0.xyxx, t0.xyzw, s0
					iadd r1.x, v5.x, cb1[0].x
					imul null, r1.x, r1.x, l(6)
					mul r0.xyzw, r0.xyzw, cb2[r1.x + 4].xyzw
					add o0.xyz, r0.xyzx, r0.xyzx
					mov_sat o0.w, r0.w
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "INSTANCING_ON" "USE_NOISE_DISTORTION" "USE_CUTOUT" "USE_CUTOUT_TEX" "_BLENDMODE_ADD" "USE_QUAD_DECAL" "USE_ALPHA_POW" }
					"!!ps_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// COLOR                    0   xyzw        1     NONE   float      w
					// TEXCOORD                 0   xyzw        2     NONE   float       
					// TEXCOORD                 1   xyz         3     NONE   float       
					// TEXCOORD                 2   xy          4     NONE   float   xy  
					// SV_InstanceID            0   x           5     NONE    uint   x   
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[12], immediateIndexed
					dcl_constantbuffer CB1[1], immediateIndexed
					dcl_constantbuffer CB2[1], immediateIndexed
					dcl_constantbuffer CB3[12], dynamicIndexed
					dcl_sampler s0, mode_default
					dcl_sampler s1, mode_default
					dcl_sampler s2, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_resource_texture2d (float,float,float,float) t1
					dcl_resource_texture2d (float,float,float,float) t2
					dcl_input_ps linear v1.w
					dcl_input_ps linear v4.xy
					dcl_input_ps constant v5.x
					dcl_output o0.xyzw
					dcl_temps 3
					mul r0.x, cb0[10].w, cb1[0].x
					mad r0.yz, v4.xxyx, cb0[4].xxyx, cb0[4].zzwz
					sample r1.xyzw, r0.yzyy, t0.xyzw, s1
					mad r0.yz, r1.xxyx, l(0.000000, 2.000000, 2.000000, 0.000000), l(0.000000, -1.000000, -1.000000, 0.000000)
					mad r1.xy, v4.xyxx, cb0[2].xyxx, cb0[2].zwzz
					mad r1.zw, -r0.yyyz, cb0[11].xxxx, r1.xxxy
					mad r0.yz, r0.yyzy, cb0[11].xxxx, r1.xxyx
					mad r0.yz, cb0[10].wwww, cb1[0].xxxx, r0.yyzy
					sample r2.xyzw, r0.yzyy, t1.xyzw, s0
					mad r0.xy, -r0.xxxx, l(1.400000, 1.400000, 0.000000, 0.000000), r1.zwzz
					sample r0.xyzw, r0.xyxx, t1.xyzw, s0
					mul r0.xyzw, r0.xyzw, r2.xyzw
					iadd r1.x, v5.x, cb2[0].x
					imul null, r1.x, r1.x, l(6)
					mul r0.xyzw, r0.xyzw, cb3[r1.x + 4].xyzw
					mad r1.x, -cb3[r1.x + 5].x, v1.w, l(1.000000)
					mad r1.x, r1.x, l(2.000000), l(-1.000000)
					add r1.yz, v4.xxyx, l(0.000000, 1.000000, 1.000000, 0.000000)
					mad r1.yz, r1.yyzy, cb0[5].xxyx, cb0[5].zzwz
					sample r2.xyzw, r1.yzyy, t2.xyzw, s2
					add r1.x, -r1.x, r2.w
					mul_sat r1.x, r1.x, cb0[10].y
					mul_sat r0.w, r0.w, r1.x
					add r0.xyz, r0.xyzx, r0.xyzx
					log r1.x, r0.w
					mov o0.w, r0.w
					mul r0.w, r1.x, cb0[10].z
					exp r0.w, r0.w
					mul o0.xyz, r0.wwww, r0.xyzx
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "_BLENDMODE_BLEND" }
					"!!ps_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// COLOR                    0   xyzw        1     NONE   float       
					// TEXCOORD                 0   xyzw        2     NONE   float   xy w
					// TEXCOORD                 1   xyz         3     NONE   float   xyz 
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[3], immediateIndexed
					dcl_constantbuffer CB1[8], immediateIndexed
					dcl_constantbuffer CB2[22], immediateIndexed
					dcl_constantbuffer CB3[5], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_sampler s1, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_resource_texture2d (float,float,float,float) t1
					dcl_input_ps linear v2.xyw
					dcl_input_ps linear v3.xyz
					dcl_output o0.xyzw
					dcl_temps 2
					div r0.xy, v2.xyxx, v2.wwww
					sample r0.xyzw, r0.xyxx, t0.xyzw, s1
					mad r0.x, cb1[7].x, r0.x, cb1[7].y
					div r0.x, l(1.000000, 1.000000, 1.000000, 1.000000), r0.x
					div r0.y, cb1[5].z, v3.z
					mul r0.yzw, r0.yyyy, v3.xxyz
					mul r0.xyz, r0.xxxx, r0.yzwy
					mul r1.xyz, r0.yyyy, cb2[19].xyzx
					mad r0.xyw, cb2[18].xyxz, r0.xxxx, r1.xyxz
					mad r0.xyz, cb2[20].xyzx, r0.zzzz, r0.xywx
					add r0.xyz, r0.xyzx, cb2[21].xyzx
					mul r1.xyz, r0.yyyy, cb3[1].xyzx
					mad r0.xyw, cb3[0].xyxz, r0.xxxx, r1.xyxz
					mad r0.xyz, cb3[2].xyzx, r0.zzzz, r0.xywx
					add r0.xyz, r0.xyzx, cb3[3].xyzx
					add r1.xyz, -|r0.xyzx|, l(0.500000, 0.500000, 0.500000, 0.000000)
					mul_sat r1.xyz, r1.xyzx, l(10000.000000, 10000.000000, 10000.000000, 0.000000)
					mul r0.w, r1.y, r1.x
					mul r0.w, r1.z, r0.w
					add r0.y, r0.y, r0.y
					add r0.xz, r0.xxzx, l(0.500000, 0.000000, 0.500000, 0.000000)
					mad r0.xz, r0.xxzx, cb0[2].xxyx, cb0[2].zzwz
					sample r1.xyzw, r0.xzxx, t1.xyzw, s0
					mul r1.xyzw, r1.xyzw, cb3[4].xyzw
					add r0.x, -|r0.y|, l(1.000000)
					mul r0.x, r0.x, r0.w
					log r0.x, r0.x
					mul r0.x, r0.x, l(0.200000)
					exp r0.x, r0.x
					mul_sat o0.w, r0.x, r1.w
					add o0.xyz, r1.xyzx, r1.xyzx
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "_BLENDMODE_BLEND" "USE_QUAD_DECAL" }
					"!!ps_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// COLOR                    0   xyzw        1     NONE   float       
					// TEXCOORD                 0   xyzw        2     NONE   float       
					// TEXCOORD                 1   xyz         3     NONE   float       
					// TEXCOORD                 2   xy          4     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[3], immediateIndexed
					dcl_constantbuffer CB1[5], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_input_ps linear v4.xy
					dcl_output o0.xyzw
					dcl_temps 1
					mad r0.xy, v4.xyxx, cb0[2].xyxx, cb0[2].zwzz
					sample r0.xyzw, r0.xyxx, t0.xyzw, s0
					mul r0.xyzw, r0.xyzw, cb1[4].xyzw
					add o0.xyz, r0.xyzx, r0.xyzx
					mov_sat o0.w, r0.w
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "USE_NOISE_DISTORTION" "USE_CUTOUT" "USE_CUTOUT_TEX" "_BLENDMODE_BLEND" "USE_QUAD_DECAL" "USE_ALPHA_POW" }
					"!!ps_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// COLOR                    0   xyzw        1     NONE   float      w
					// TEXCOORD                 0   xyzw        2     NONE   float       
					// TEXCOORD                 1   xyz         3     NONE   float       
					// TEXCOORD                 2   xy          4     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[12], immediateIndexed
					dcl_constantbuffer CB1[1], immediateIndexed
					dcl_constantbuffer CB2[6], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_sampler s1, mode_default
					dcl_sampler s2, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_resource_texture2d (float,float,float,float) t1
					dcl_resource_texture2d (float,float,float,float) t2
					dcl_input_ps linear v1.w
					dcl_input_ps linear v4.xy
					dcl_output o0.xyzw
					dcl_temps 3
					add r0.xy, v4.xyxx, l(1.000000, 1.000000, 0.000000, 0.000000)
					mad r0.xy, r0.xyxx, cb0[5].xyxx, cb0[5].zwzz
					sample r0.xyzw, r0.xyxx, t2.xyzw, s2
					mad r0.x, -cb2[5].x, v1.w, l(1.000000)
					mad r0.x, r0.x, l(2.000000), l(-1.000000)
					add r0.x, -r0.x, r0.w
					mul_sat r0.x, r0.x, cb0[10].y
					mul r0.y, cb0[10].w, cb1[0].x
					mad r0.zw, v4.xxxy, cb0[4].xxxy, cb0[4].zzzw
					sample r1.xyzw, r0.zwzz, t0.xyzw, s1
					mad r0.zw, r1.xxxy, l(0.000000, 0.000000, 2.000000, 2.000000), l(0.000000, 0.000000, -1.000000, -1.000000)
					mad r1.xy, v4.xyxx, cb0[2].xyxx, cb0[2].zwzz
					mad r1.zw, -r0.zzzw, cb0[11].xxxx, r1.xxxy
					mad r0.zw, r0.zzzw, cb0[11].xxxx, r1.xxxy
					mad r0.zw, cb0[10].wwww, cb1[0].xxxx, r0.zzzw
					sample r2.xyzw, r0.zwzz, t1.xyzw, s0
					mad r0.yz, -r0.yyyy, l(0.000000, 1.400000, 1.400000, 0.000000), r1.zzwz
					sample r1.xyzw, r0.yzyy, t1.xyzw, s0
					mul r1.xyzw, r1.xyzw, r2.xyzw
					mul r1.xyzw, r1.xyzw, cb2[4].xyzw
					mul_sat r0.x, r0.x, r1.w
					add r0.yzw, r1.xxyz, r1.xxyz
					log r1.x, r0.x
					mov o0.w, r0.x
					mul r0.x, r1.x, cb0[10].z
					exp r0.x, r0.x
					mul o0.xyz, r0.xxxx, r0.yzwy
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "INSTANCING_ON" "_BLENDMODE_BLEND" }
					"!!ps_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// COLOR                    0   xyzw        1     NONE   float       
					// TEXCOORD                 0   xyzw        2     NONE   float   xy w
					// TEXCOORD                 1   xyz         3     NONE   float   xyz 
					// SV_InstanceID            0   x           4     NONE    uint   x   
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[3], immediateIndexed
					dcl_constantbuffer CB1[8], immediateIndexed
					dcl_constantbuffer CB2[22], immediateIndexed
					dcl_constantbuffer CB3[1], immediateIndexed
					dcl_constantbuffer CB4[12], dynamicIndexed
					dcl_sampler s0, mode_default
					dcl_sampler s1, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_resource_texture2d (float,float,float,float) t1
					dcl_input_ps linear v2.xyw
					dcl_input_ps linear v3.xyz
					dcl_input_ps constant v4.x
					dcl_output o0.xyzw
					dcl_temps 3
					div r0.xy, v2.xyxx, v2.wwww
					sample r0.xyzw, r0.xyxx, t0.xyzw, s1
					mad r0.x, cb1[7].x, r0.x, cb1[7].y
					div r0.x, l(1.000000, 1.000000, 1.000000, 1.000000), r0.x
					div r0.y, cb1[5].z, v3.z
					mul r0.yzw, r0.yyyy, v3.xxyz
					mul r0.xyz, r0.xxxx, r0.yzwy
					mul r1.xyz, r0.yyyy, cb2[19].xyzx
					mad r0.xyw, cb2[18].xyxz, r0.xxxx, r1.xyxz
					mad r0.xyz, cb2[20].xyzx, r0.zzzz, r0.xywx
					add r0.xyz, r0.xyzx, cb2[21].xyzx
					iadd r0.w, v4.x, cb3[0].x
					imul null, r0.w, r0.w, l(6)
					mul r1.xyz, r0.yyyy, cb4[r0.w + 1].xyzx
					mad r1.xyz, cb4[r0.w + 0].xyzx, r0.xxxx, r1.xyzx
					mad r0.xyz, cb4[r0.w + 2].xyzx, r0.zzzz, r1.xyzx
					add r0.xyz, r0.xyzx, cb4[r0.w + 3].xyzx
					add r1.xyz, -|r0.xyzx|, l(0.500000, 0.500000, 0.500000, 0.000000)
					mul_sat r1.xyz, r1.xyzx, l(10000.000000, 10000.000000, 10000.000000, 0.000000)
					mul r1.x, r1.y, r1.x
					mul r1.x, r1.z, r1.x
					add r0.y, r0.y, r0.y
					add r0.xz, r0.xxzx, l(0.500000, 0.000000, 0.500000, 0.000000)
					mad r0.xz, r0.xxzx, cb0[2].xxyx, cb0[2].zzwz
					sample r2.xyzw, r0.xzxx, t1.xyzw, s0
					mul r2.xyzw, r2.xyzw, cb4[r0.w + 4].xyzw
					add r0.x, -|r0.y|, l(1.000000)
					mul r0.x, r0.x, r1.x
					log r0.x, r0.x
					mul r0.x, r0.x, l(0.200000)
					exp r0.x, r0.x
					mul_sat o0.w, r0.x, r2.w
					add o0.xyz, r2.xyzx, r2.xyzx
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "INSTANCING_ON" "_BLENDMODE_BLEND" "USE_QUAD_DECAL" }
					"!!ps_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// COLOR                    0   xyzw        1     NONE   float       
					// TEXCOORD                 0   xyzw        2     NONE   float       
					// TEXCOORD                 1   xyz         3     NONE   float       
					// TEXCOORD                 2   xy          4     NONE   float   xy  
					// SV_InstanceID            0   x           5     NONE    uint   x   
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[3], immediateIndexed
					dcl_constantbuffer CB1[1], immediateIndexed
					dcl_constantbuffer CB2[11], dynamicIndexed
					dcl_sampler s0, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_input_ps linear v4.xy
					dcl_input_ps constant v5.x
					dcl_output o0.xyzw
					dcl_temps 2
					mad r0.xy, v4.xyxx, cb0[2].xyxx, cb0[2].zwzz
					sample r0.xyzw, r0.xyxx, t0.xyzw, s0
					iadd r1.x, v5.x, cb1[0].x
					imul null, r1.x, r1.x, l(6)
					mul r0.xyzw, r0.xyzw, cb2[r1.x + 4].xyzw
					add o0.xyz, r0.xyzx, r0.xyzx
					mov_sat o0.w, r0.w
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "INSTANCING_ON" "USE_NOISE_DISTORTION" "USE_CUTOUT" "USE_CUTOUT_TEX" "_BLENDMODE_BLEND" "USE_QUAD_DECAL" "USE_ALPHA_POW" }
					"!!ps_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// COLOR                    0   xyzw        1     NONE   float      w
					// TEXCOORD                 0   xyzw        2     NONE   float       
					// TEXCOORD                 1   xyz         3     NONE   float       
					// TEXCOORD                 2   xy          4     NONE   float   xy  
					// SV_InstanceID            0   x           5     NONE    uint   x   
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[12], immediateIndexed
					dcl_constantbuffer CB1[1], immediateIndexed
					dcl_constantbuffer CB2[1], immediateIndexed
					dcl_constantbuffer CB3[12], dynamicIndexed
					dcl_sampler s0, mode_default
					dcl_sampler s1, mode_default
					dcl_sampler s2, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_resource_texture2d (float,float,float,float) t1
					dcl_resource_texture2d (float,float,float,float) t2
					dcl_input_ps linear v1.w
					dcl_input_ps linear v4.xy
					dcl_input_ps constant v5.x
					dcl_output o0.xyzw
					dcl_temps 3
					mul r0.x, cb0[10].w, cb1[0].x
					mad r0.yz, v4.xxyx, cb0[4].xxyx, cb0[4].zzwz
					sample r1.xyzw, r0.yzyy, t0.xyzw, s1
					mad r0.yz, r1.xxyx, l(0.000000, 2.000000, 2.000000, 0.000000), l(0.000000, -1.000000, -1.000000, 0.000000)
					mad r1.xy, v4.xyxx, cb0[2].xyxx, cb0[2].zwzz
					mad r1.zw, -r0.yyyz, cb0[11].xxxx, r1.xxxy
					mad r0.yz, r0.yyzy, cb0[11].xxxx, r1.xxyx
					mad r0.yz, cb0[10].wwww, cb1[0].xxxx, r0.yyzy
					sample r2.xyzw, r0.yzyy, t1.xyzw, s0
					mad r0.xy, -r0.xxxx, l(1.400000, 1.400000, 0.000000, 0.000000), r1.zwzz
					sample r0.xyzw, r0.xyxx, t1.xyzw, s0
					mul r0.xyzw, r0.xyzw, r2.xyzw
					iadd r1.x, v5.x, cb2[0].x
					imul null, r1.x, r1.x, l(6)
					mul r0.xyzw, r0.xyzw, cb3[r1.x + 4].xyzw
					mad r1.x, -cb3[r1.x + 5].x, v1.w, l(1.000000)
					mad r1.x, r1.x, l(2.000000), l(-1.000000)
					add r1.yz, v4.xxyx, l(0.000000, 1.000000, 1.000000, 0.000000)
					mad r1.yz, r1.yyzy, cb0[5].xxyx, cb0[5].zzwz
					sample r2.xyzw, r1.yzyy, t2.xyzw, s2
					add r1.x, -r1.x, r2.w
					mul_sat r1.x, r1.x, cb0[10].y
					mul_sat r0.w, r0.w, r1.x
					add r0.xyz, r0.xyzx, r0.xyzx
					log r1.x, r0.w
					mov o0.w, r0.w
					mul r0.w, r1.x, cb0[10].z
					exp r0.w, r0.w
					mul o0.xyz, r0.wwww, r0.xyzx
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "_BLENDMODE_MUL" }
					"!!ps_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// COLOR                    0   xyzw        1     NONE   float       
					// TEXCOORD                 0   xyzw        2     NONE   float   xy w
					// TEXCOORD                 1   xyz         3     NONE   float   xyz 
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[3], immediateIndexed
					dcl_constantbuffer CB1[8], immediateIndexed
					dcl_constantbuffer CB2[22], immediateIndexed
					dcl_constantbuffer CB3[5], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_sampler s1, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_resource_texture2d (float,float,float,float) t1
					dcl_input_ps linear v2.xyw
					dcl_input_ps linear v3.xyz
					dcl_output o0.xyzw
					dcl_temps 2
					div r0.xy, v2.xyxx, v2.wwww
					sample r0.xyzw, r0.xyxx, t0.xyzw, s1
					mad r0.x, cb1[7].x, r0.x, cb1[7].y
					div r0.x, l(1.000000, 1.000000, 1.000000, 1.000000), r0.x
					div r0.y, cb1[5].z, v3.z
					mul r0.yzw, r0.yyyy, v3.xxyz
					mul r0.xyz, r0.xxxx, r0.yzwy
					mul r1.xyz, r0.yyyy, cb2[19].xyzx
					mad r0.xyw, cb2[18].xyxz, r0.xxxx, r1.xyxz
					mad r0.xyz, cb2[20].xyzx, r0.zzzz, r0.xywx
					add r0.xyz, r0.xyzx, cb2[21].xyzx
					mul r1.xyz, r0.yyyy, cb3[1].xyzx
					mad r0.xyw, cb3[0].xyxz, r0.xxxx, r1.xyxz
					mad r0.xyz, cb3[2].xyzx, r0.zzzz, r0.xywx
					add r0.xyz, r0.xyzx, cb3[3].xyzx
					add r1.xyz, -|r0.xyzx|, l(0.500000, 0.500000, 0.500000, 0.000000)
					mul_sat r1.xyz, r1.xyzx, l(10000.000000, 10000.000000, 10000.000000, 0.000000)
					mul r0.w, r1.y, r1.x
					mul r0.w, r1.z, r0.w
					add r0.y, r0.y, r0.y
					add r0.xz, r0.xxzx, l(0.500000, 0.000000, 0.500000, 0.000000)
					mad r0.xz, r0.xxzx, cb0[2].xxyx, cb0[2].zzwz
					sample r1.xyzw, r0.xzxx, t1.xyzw, s0
					mul r1.xyzw, r1.xyzw, cb3[4].xyzw
					add r0.x, -|r0.y|, l(1.000000)
					mul r0.x, r0.x, r0.w
					log r0.x, r0.x
					mul r0.x, r0.x, l(0.200000)
					exp r0.x, r0.x
					mul_sat r0.w, r0.x, r1.w
					add r0.xyz, r1.xyzx, r1.xyzx
					add r1.xyzw, r0.xyzw, l(-1.000000, -1.000000, -1.000000, -1.000000)
					add r0.x, r0.w, r0.w
					min r0.x, r0.x, l(1.000000)
					mad o0.xyzw, r0.xxxx, r1.xyzw, l(1.000000, 1.000000, 1.000000, 1.000000)
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "_BLENDMODE_MUL" "USE_QUAD_DECAL" }
					"!!ps_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// COLOR                    0   xyzw        1     NONE   float       
					// TEXCOORD                 0   xyzw        2     NONE   float       
					// TEXCOORD                 1   xyz         3     NONE   float       
					// TEXCOORD                 2   xy          4     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[3], immediateIndexed
					dcl_constantbuffer CB1[5], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_input_ps linear v4.xy
					dcl_output o0.xyzw
					dcl_temps 2
					mad r0.xy, v4.xyxx, cb0[2].xyxx, cb0[2].zwzz
					sample r0.xyzw, r0.xyxx, t0.xyzw, s0
					mul r0.xyzw, r0.xyzw, cb1[4].xyzw
					add r0.xyz, r0.xyzx, r0.xyzx
					mov_sat r0.w, r0.w
					add r1.xyzw, r0.xyzw, l(-1.000000, -1.000000, -1.000000, -1.000000)
					add r0.x, r0.w, r0.w
					min r0.x, r0.x, l(1.000000)
					mad o0.xyzw, r0.xxxx, r1.xyzw, l(1.000000, 1.000000, 1.000000, 1.000000)
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "USE_NOISE_DISTORTION" "USE_CUTOUT" "USE_CUTOUT_TEX" "_BLENDMODE_MUL" "USE_QUAD_DECAL" "USE_ALPHA_POW" }
					"!!ps_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// COLOR                    0   xyzw        1     NONE   float      w
					// TEXCOORD                 0   xyzw        2     NONE   float       
					// TEXCOORD                 1   xyz         3     NONE   float       
					// TEXCOORD                 2   xy          4     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[12], immediateIndexed
					dcl_constantbuffer CB1[1], immediateIndexed
					dcl_constantbuffer CB2[6], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_sampler s1, mode_default
					dcl_sampler s2, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_resource_texture2d (float,float,float,float) t1
					dcl_resource_texture2d (float,float,float,float) t2
					dcl_input_ps linear v1.w
					dcl_input_ps linear v4.xy
					dcl_output o0.xyzw
					dcl_temps 3
					mul r0.x, cb0[10].w, cb1[0].x
					mad r0.yz, v4.xxyx, cb0[4].xxyx, cb0[4].zzwz
					sample r1.xyzw, r0.yzyy, t0.xyzw, s1
					mad r0.yz, r1.xxyx, l(0.000000, 2.000000, 2.000000, 0.000000), l(0.000000, -1.000000, -1.000000, 0.000000)
					mad r1.xy, v4.xyxx, cb0[2].xyxx, cb0[2].zwzz
					mad r1.zw, -r0.yyyz, cb0[11].xxxx, r1.xxxy
					mad r0.yz, r0.yyzy, cb0[11].xxxx, r1.xxyx
					mad r0.yz, cb0[10].wwww, cb1[0].xxxx, r0.yyzy
					sample r2.xyzw, r0.yzyy, t1.xyzw, s0
					mad r0.xy, -r0.xxxx, l(1.400000, 1.400000, 0.000000, 0.000000), r1.zwzz
					sample r0.xyzw, r0.xyxx, t1.xyzw, s0
					mul r0.xyzw, r0.xyzw, r2.xyzw
					mul r0.xyzw, r0.xyzw, cb2[4].xyzw
					add r0.xyz, r0.xyzx, r0.xyzx
					add r1.xy, v4.xyxx, l(1.000000, 1.000000, 0.000000, 0.000000)
					mad r1.xy, r1.xyxx, cb0[5].xyxx, cb0[5].zwzz
					sample r1.xyzw, r1.xyxx, t2.xyzw, s2
					mad r1.x, -cb2[5].x, v1.w, l(1.000000)
					mad r1.x, r1.x, l(2.000000), l(-1.000000)
					add r1.x, -r1.x, r1.w
					mul_sat r1.x, r1.x, cb0[10].y
					mul_sat r1.w, r0.w, r1.x
					log r0.w, r1.w
					mul r0.w, r0.w, cb0[10].z
					exp r0.w, r0.w
					mul r1.xyz, r0.wwww, r0.xyzx
					add r0.xyzw, r1.xyzw, l(-1.000000, -1.000000, -1.000000, -1.000000)
					add r1.x, r1.w, r1.w
					min r1.x, r1.x, l(1.000000)
					mad o0.xyzw, r1.xxxx, r0.xyzw, l(1.000000, 1.000000, 1.000000, 1.000000)
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "INSTANCING_ON" "_BLENDMODE_MUL" }
					"!!ps_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// COLOR                    0   xyzw        1     NONE   float       
					// TEXCOORD                 0   xyzw        2     NONE   float   xy w
					// TEXCOORD                 1   xyz         3     NONE   float   xyz 
					// SV_InstanceID            0   x           4     NONE    uint   x   
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[3], immediateIndexed
					dcl_constantbuffer CB1[8], immediateIndexed
					dcl_constantbuffer CB2[22], immediateIndexed
					dcl_constantbuffer CB3[1], immediateIndexed
					dcl_constantbuffer CB4[12], dynamicIndexed
					dcl_sampler s0, mode_default
					dcl_sampler s1, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_resource_texture2d (float,float,float,float) t1
					dcl_input_ps linear v2.xyw
					dcl_input_ps linear v3.xyz
					dcl_input_ps constant v4.x
					dcl_output o0.xyzw
					dcl_temps 3
					div r0.xy, v2.xyxx, v2.wwww
					sample r0.xyzw, r0.xyxx, t0.xyzw, s1
					mad r0.x, cb1[7].x, r0.x, cb1[7].y
					div r0.x, l(1.000000, 1.000000, 1.000000, 1.000000), r0.x
					div r0.y, cb1[5].z, v3.z
					mul r0.yzw, r0.yyyy, v3.xxyz
					mul r0.xyz, r0.xxxx, r0.yzwy
					mul r1.xyz, r0.yyyy, cb2[19].xyzx
					mad r0.xyw, cb2[18].xyxz, r0.xxxx, r1.xyxz
					mad r0.xyz, cb2[20].xyzx, r0.zzzz, r0.xywx
					add r0.xyz, r0.xyzx, cb2[21].xyzx
					iadd r0.w, v4.x, cb3[0].x
					imul null, r0.w, r0.w, l(6)
					mul r1.xyz, r0.yyyy, cb4[r0.w + 1].xyzx
					mad r1.xyz, cb4[r0.w + 0].xyzx, r0.xxxx, r1.xyzx
					mad r0.xyz, cb4[r0.w + 2].xyzx, r0.zzzz, r1.xyzx
					add r0.xyz, r0.xyzx, cb4[r0.w + 3].xyzx
					add r1.xyz, -|r0.xyzx|, l(0.500000, 0.500000, 0.500000, 0.000000)
					mul_sat r1.xyz, r1.xyzx, l(10000.000000, 10000.000000, 10000.000000, 0.000000)
					mul r1.x, r1.y, r1.x
					mul r1.x, r1.z, r1.x
					add r0.y, r0.y, r0.y
					add r0.xz, r0.xxzx, l(0.500000, 0.000000, 0.500000, 0.000000)
					mad r0.xz, r0.xxzx, cb0[2].xxyx, cb0[2].zzwz
					sample r2.xyzw, r0.xzxx, t1.xyzw, s0
					mul r2.xyzw, r2.xyzw, cb4[r0.w + 4].xyzw
					add r0.x, -|r0.y|, l(1.000000)
					mul r0.x, r0.x, r1.x
					log r0.x, r0.x
					mul r0.x, r0.x, l(0.200000)
					exp r0.x, r0.x
					mul_sat r0.w, r0.x, r2.w
					add r0.xyz, r2.xyzx, r2.xyzx
					add r1.xyzw, r0.xyzw, l(-1.000000, -1.000000, -1.000000, -1.000000)
					add r0.x, r0.w, r0.w
					min r0.x, r0.x, l(1.000000)
					mad o0.xyzw, r0.xxxx, r1.xyzw, l(1.000000, 1.000000, 1.000000, 1.000000)
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "INSTANCING_ON" "_BLENDMODE_MUL" "USE_QUAD_DECAL" }
					"!!ps_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// COLOR                    0   xyzw        1     NONE   float       
					// TEXCOORD                 0   xyzw        2     NONE   float       
					// TEXCOORD                 1   xyz         3     NONE   float       
					// TEXCOORD                 2   xy          4     NONE   float   xy  
					// SV_InstanceID            0   x           5     NONE    uint   x   
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[3], immediateIndexed
					dcl_constantbuffer CB1[1], immediateIndexed
					dcl_constantbuffer CB2[11], dynamicIndexed
					dcl_sampler s0, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_input_ps linear v4.xy
					dcl_input_ps constant v5.x
					dcl_output o0.xyzw
					dcl_temps 2
					mad r0.xy, v4.xyxx, cb0[2].xyxx, cb0[2].zwzz
					sample r0.xyzw, r0.xyxx, t0.xyzw, s0
					iadd r1.x, v5.x, cb1[0].x
					imul null, r1.x, r1.x, l(6)
					mul r0.xyzw, r0.xyzw, cb2[r1.x + 4].xyzw
					add r0.xyz, r0.xyzx, r0.xyzx
					mov_sat r0.w, r0.w
					add r1.xyzw, r0.xyzw, l(-1.000000, -1.000000, -1.000000, -1.000000)
					add r0.x, r0.w, r0.w
					min r0.x, r0.x, l(1.000000)
					mad o0.xyzw, r0.xxxx, r1.xyzw, l(1.000000, 1.000000, 1.000000, 1.000000)
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "INSTANCING_ON" "USE_NOISE_DISTORTION" "USE_CUTOUT" "USE_CUTOUT_TEX" "_BLENDMODE_MUL" "USE_QUAD_DECAL" "USE_ALPHA_POW" }
					"!!ps_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// COLOR                    0   xyzw        1     NONE   float      w
					// TEXCOORD                 0   xyzw        2     NONE   float       
					// TEXCOORD                 1   xyz         3     NONE   float       
					// TEXCOORD                 2   xy          4     NONE   float   xy  
					// SV_InstanceID            0   x           5     NONE    uint   x   
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[12], immediateIndexed
					dcl_constantbuffer CB1[1], immediateIndexed
					dcl_constantbuffer CB2[1], immediateIndexed
					dcl_constantbuffer CB3[12], dynamicIndexed
					dcl_sampler s0, mode_default
					dcl_sampler s1, mode_default
					dcl_sampler s2, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_resource_texture2d (float,float,float,float) t1
					dcl_resource_texture2d (float,float,float,float) t2
					dcl_input_ps linear v1.w
					dcl_input_ps linear v4.xy
					dcl_input_ps constant v5.x
					dcl_output o0.xyzw
					dcl_temps 3
					mul r0.x, cb0[10].w, cb1[0].x
					mad r0.yz, v4.xxyx, cb0[4].xxyx, cb0[4].zzwz
					sample r1.xyzw, r0.yzyy, t0.xyzw, s1
					mad r0.yz, r1.xxyx, l(0.000000, 2.000000, 2.000000, 0.000000), l(0.000000, -1.000000, -1.000000, 0.000000)
					mad r1.xy, v4.xyxx, cb0[2].xyxx, cb0[2].zwzz
					mad r1.zw, -r0.yyyz, cb0[11].xxxx, r1.xxxy
					mad r0.yz, r0.yyzy, cb0[11].xxxx, r1.xxyx
					mad r0.yz, cb0[10].wwww, cb1[0].xxxx, r0.yyzy
					sample r2.xyzw, r0.yzyy, t1.xyzw, s0
					mad r0.xy, -r0.xxxx, l(1.400000, 1.400000, 0.000000, 0.000000), r1.zwzz
					sample r0.xyzw, r0.xyxx, t1.xyzw, s0
					mul r0.xyzw, r0.xyzw, r2.xyzw
					iadd r1.x, v5.x, cb2[0].x
					imul null, r1.x, r1.x, l(6)
					mul r0.xyzw, r0.xyzw, cb3[r1.x + 4].xyzw
					mad r1.x, -cb3[r1.x + 5].x, v1.w, l(1.000000)
					mad r1.x, r1.x, l(2.000000), l(-1.000000)
					add r1.yz, v4.xxyx, l(0.000000, 1.000000, 1.000000, 0.000000)
					mad r1.yz, r1.yyzy, cb0[5].xxyx, cb0[5].zzwz
					sample r2.xyzw, r1.yzyy, t2.xyzw, s2
					add r1.x, -r1.x, r2.w
					mul_sat r1.x, r1.x, cb0[10].y
					mul_sat r1.w, r0.w, r1.x
					add r0.xyz, r0.xyzx, r0.xyzx
					log r0.w, r1.w
					mul r0.w, r0.w, cb0[10].z
					exp r0.w, r0.w
					mul r1.xyz, r0.wwww, r0.xyzx
					add r0.xyzw, r1.xyzw, l(-1.000000, -1.000000, -1.000000, -1.000000)
					add r1.x, r1.w, r1.w
					min r1.x, r1.x, l(1.000000)
					mad o0.xyzw, r1.xxxx, r0.xyzw, l(1.000000, 1.000000, 1.000000, 1.000000)
					ret 
					// Approximately 0 instruction slots used"
				}
			}
		}
	}
	CustomEditor "RFX4_UberDecalGUI"
}