Shader "KriptoFX/RFX4/Distortion" {
	Properties {
		[Header(Main Settings)] [Toggle(_EMISSION)] _UseMainTex ("Use Main Texture", Float) = 0
		[PerRendererData] [HDR] _TintColor ("Tint Color", Vector) = (1,1,1,1)
		_TintDistortion ("Tint Distortion", Float) = 1
		_MainTex ("Main Texture", 2D) = "black" {}
		[Header(Main Settings)] [Normal] _NormalTex ("Normal(RG) Alpha(A)", 2D) = "bump" {}
		[PerRendererData] [HDR] _MainColor ("Main Color", Vector) = (1,1,1,1)
		[PerRendererData] _Distortion ("Distortion", Float) = 100
		[Toggle(USE_REFRACTIVE)] _UseRefractive ("Use Refractive Distort", Float) = 0
		_RefractiveStrength ("Refractive Strength", Range(-1, 1)) = 0
		[Toggle(_FADING_ON)] _UseSoft ("Use Soft Particles", Float) = 0
		_InvFade ("Soft Particles Factor", Float) = 3
		[Space] [Header(Height Settings)] [Toggle(USE_HEIGHT)] _UseHeight ("Use Height Map", Float) = 0
		_HeightTex ("Height Tex", 2D) = "white" {}
		_Height ("_Height", Float) = 0.1
		_HeightUVScrollDistort ("Height UV Scroll(XY)", Vector) = (8,12,0,0)
		[Space] [Header(Fresnel)] [Toggle(USE_FRESNEL)] _UseFresnel ("Use Fresnel", Float) = 0
		[HDR] _FresnelColor ("Fresnel Color", Vector) = (0.5,0.5,0.5,1)
		_FresnelInvert ("Fresnel Invert", Range(0, 1)) = 1
		_FresnelPow ("Fresnel Pow", Float) = 5
		_FresnelR0 ("Fresnel R0", Float) = 0.04
		_FresnelDistort ("Fresnel Distort", Float) = 1500
		[Space] [Header(Cutout)] [Toggle(USE_CUTOUT)] _UseCutout ("Use Cutout", Float) = 0
		_CutoutTex ("Cutout Tex", 2D) = "white" {}
		[PerRendererData] _Cutout ("Cutout", Range(0, 1.2)) = 1
		[HDR] _CutoutColor ("Cutout Color", Vector) = (1,1,1,1)
		_CutoutThreshold ("Cutout Threshold", Range(0, 1)) = 0.015
		[Space] [Header(Rendering)] [Toggle] _ZWriteMode ("ZWrite On?", Float) = 0
		[Enum(Off,0,Front,1,Back,2)] _CullMode ("Culling", Float) = 0
		[Toggle(USE_ALPHA_CLIPING)] _UseAlphaCliping ("Use Alpha Cliping", Float) = 0
		_AlphaClip ("Alpha Clip Threshold", Float) = 100
		[Toggle(_FLIPBOOK_BLENDING)] _UseBlending ("Use Blending", Float) = 0
	}
	SubShader {
		Tags { "IGNOREPROJECTOR" = "true" "QUEUE" = "Transparent+1" "RenderType" = "Transparent" }
		GrabPass {
			"_GrabTexture"
		}
		Pass {
			Tags { "IGNOREPROJECTOR" = "true" "QUEUE" = "Transparent+1" "RenderType" = "Transparent" }
			Blend SrcAlpha OneMinusSrcAlpha, SrcAlpha OneMinusSrcAlpha
			ZWrite Off
			Cull Off
			GpuProgramID 34787
			Program "vp" {
				SubProgram "d3d11 " {
					"!!vs_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xy          2     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xyzw        2     NONE   float   xyzw
					// TEXCOORD                 2   xy          3     NONE   float   xy  
					//
					vs_4_0
					dcl_constantbuffer CB0[3], immediateIndexed
					dcl_constantbuffer CB1[4], immediateIndexed
					dcl_constantbuffer CB2[21], immediateIndexed
					dcl_input v0.xyz
					dcl_input v1.xyzw
					dcl_input v2.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xyzw
					dcl_output o3.xy
					dcl_temps 2
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					add r0.xyzw, r0.xyzw, cb1[3].xyzw
					mul r1.xyzw, r0.yyyy, cb2[18].xyzw
					mad r1.xyzw, cb2[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb2[19].xyzw, r0.zzzz, r1.xyzw
					mad r0.xyzw, cb2[20].xyzw, r0.wwww, r1.xyzw
					mov o0.xyzw, r0.xyzw
					mov o1.xyzw, v1.xyzw
					mul r1.xyz, r0.xwyx, l(0.500000, 0.500000, -0.500000, 0.000000)
					mov o2.zw, r0.zzzw
					add o2.xy, r1.yyyy, r1.xzxx
					mad o3.xy, v2.xyxx, cb0[2].xyxx, cb0[2].zwzz
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "SOFTPARTICLES_ON" "USE_ALPHA_CLIPING" }
					"!!vs_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xy          2     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xyzw        2     NONE   float   xyzw
					// TEXCOORD                 2   xy          3     NONE   float   xy  
					//
					vs_4_0
					dcl_constantbuffer CB0[3], immediateIndexed
					dcl_constantbuffer CB1[4], immediateIndexed
					dcl_constantbuffer CB2[21], immediateIndexed
					dcl_input v0.xyz
					dcl_input v1.xyzw
					dcl_input v2.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xyzw
					dcl_output o3.xy
					dcl_temps 2
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					add r0.xyzw, r0.xyzw, cb1[3].xyzw
					mul r1.xyzw, r0.yyyy, cb2[18].xyzw
					mad r1.xyzw, cb2[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb2[19].xyzw, r0.zzzz, r1.xyzw
					mad r0.xyzw, cb2[20].xyzw, r0.wwww, r1.xyzw
					mov o0.xyzw, r0.xyzw
					mov o1.xyzw, v1.xyzw
					mul r1.xyz, r0.xwyx, l(0.500000, 0.500000, -0.500000, 0.000000)
					mov o2.zw, r0.zzzw
					add o2.xy, r1.yyyy, r1.xzxx
					mad o3.xy, v2.xyxx, cb0[2].xyxx, cb0[2].zwzz
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "SOFTPARTICLES_ON" }
					"!!vs_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xy          2     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xyzw        2     NONE   float   xyzw
					// TEXCOORD                 2   xy          3     NONE   float   xy  
					//
					vs_4_0
					dcl_constantbuffer CB0[3], immediateIndexed
					dcl_constantbuffer CB1[4], immediateIndexed
					dcl_constantbuffer CB2[21], immediateIndexed
					dcl_input v0.xyz
					dcl_input v1.xyzw
					dcl_input v2.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xyzw
					dcl_output o3.xy
					dcl_temps 2
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					add r0.xyzw, r0.xyzw, cb1[3].xyzw
					mul r1.xyzw, r0.yyyy, cb2[18].xyzw
					mad r1.xyzw, cb2[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb2[19].xyzw, r0.zzzz, r1.xyzw
					mad r0.xyzw, cb2[20].xyzw, r0.wwww, r1.xyzw
					mov o0.xyzw, r0.xyzw
					mov o1.xyzw, v1.xyzw
					mul r1.xyz, r0.xwyx, l(0.500000, 0.500000, -0.500000, 0.000000)
					mov o2.zw, r0.zzzw
					add o2.xy, r1.yyyy, r1.xzxx
					mad o3.xy, v2.xyxx, cb0[2].xyxx, cb0[2].zwzz
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "USE_ALPHA_CLIPING" }
					"!!vs_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xy          2     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xyzw        2     NONE   float   xyzw
					// TEXCOORD                 2   xy          3     NONE   float   xy  
					//
					vs_4_0
					dcl_constantbuffer CB0[3], immediateIndexed
					dcl_constantbuffer CB1[4], immediateIndexed
					dcl_constantbuffer CB2[21], immediateIndexed
					dcl_input v0.xyz
					dcl_input v1.xyzw
					dcl_input v2.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xyzw
					dcl_output o3.xy
					dcl_temps 2
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					add r0.xyzw, r0.xyzw, cb1[3].xyzw
					mul r1.xyzw, r0.yyyy, cb2[18].xyzw
					mad r1.xyzw, cb2[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb2[19].xyzw, r0.zzzz, r1.xyzw
					mad r0.xyzw, cb2[20].xyzw, r0.wwww, r1.xyzw
					mov o0.xyzw, r0.xyzw
					mov o1.xyzw, v1.xyzw
					mul r1.xyz, r0.xwyx, l(0.500000, 0.500000, -0.500000, 0.000000)
					mov o2.zw, r0.zzzw
					add o2.xy, r1.yyyy, r1.xzxx
					mad o3.xy, v2.xyxx, cb0[2].xyxx, cb0[2].zwzz
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "DISTORT_OFF" }
					"!!vs_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xy          2     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xyzw        2     NONE   float   xyzw
					// TEXCOORD                 2   xy          3     NONE   float   xy  
					//
					vs_4_0
					dcl_constantbuffer CB0[3], immediateIndexed
					dcl_constantbuffer CB1[4], immediateIndexed
					dcl_constantbuffer CB2[21], immediateIndexed
					dcl_input v0.xyz
					dcl_input v1.xyzw
					dcl_input v2.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xyzw
					dcl_output o3.xy
					dcl_temps 2
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					add r0.xyzw, r0.xyzw, cb1[3].xyzw
					mul r1.xyzw, r0.yyyy, cb2[18].xyzw
					mad r1.xyzw, cb2[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb2[19].xyzw, r0.zzzz, r1.xyzw
					mad r0.xyzw, cb2[20].xyzw, r0.wwww, r1.xyzw
					mov o0.xyzw, r0.xyzw
					mov o1.xyzw, v1.xyzw
					mul r1.xyz, r0.xwyx, l(0.500000, 0.500000, -0.500000, 0.000000)
					mov o2.zw, r0.zzzw
					add o2.xy, r1.yyyy, r1.xzxx
					mad o3.xy, v2.xyxx, cb0[2].xyxx, cb0[2].zwzz
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "SOFTPARTICLES_ON" "DISTORT_OFF" "USE_ALPHA_CLIPING" }
					"!!vs_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xy          2     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xyzw        2     NONE   float   xyzw
					// TEXCOORD                 2   xy          3     NONE   float   xy  
					//
					vs_4_0
					dcl_constantbuffer CB0[3], immediateIndexed
					dcl_constantbuffer CB1[4], immediateIndexed
					dcl_constantbuffer CB2[21], immediateIndexed
					dcl_input v0.xyz
					dcl_input v1.xyzw
					dcl_input v2.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xyzw
					dcl_output o3.xy
					dcl_temps 2
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					add r0.xyzw, r0.xyzw, cb1[3].xyzw
					mul r1.xyzw, r0.yyyy, cb2[18].xyzw
					mad r1.xyzw, cb2[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb2[19].xyzw, r0.zzzz, r1.xyzw
					mad r0.xyzw, cb2[20].xyzw, r0.wwww, r1.xyzw
					mov o0.xyzw, r0.xyzw
					mov o1.xyzw, v1.xyzw
					mul r1.xyz, r0.xwyx, l(0.500000, 0.500000, -0.500000, 0.000000)
					mov o2.zw, r0.zzzw
					add o2.xy, r1.yyyy, r1.xzxx
					mad o3.xy, v2.xyxx, cb0[2].xyxx, cb0[2].zwzz
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "SOFTPARTICLES_ON" "DISTORT_OFF" }
					"!!vs_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xy          2     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xyzw        2     NONE   float   xyzw
					// TEXCOORD                 2   xy          3     NONE   float   xy  
					//
					vs_4_0
					dcl_constantbuffer CB0[3], immediateIndexed
					dcl_constantbuffer CB1[4], immediateIndexed
					dcl_constantbuffer CB2[21], immediateIndexed
					dcl_input v0.xyz
					dcl_input v1.xyzw
					dcl_input v2.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xyzw
					dcl_output o3.xy
					dcl_temps 2
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					add r0.xyzw, r0.xyzw, cb1[3].xyzw
					mul r1.xyzw, r0.yyyy, cb2[18].xyzw
					mad r1.xyzw, cb2[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb2[19].xyzw, r0.zzzz, r1.xyzw
					mad r0.xyzw, cb2[20].xyzw, r0.wwww, r1.xyzw
					mov o0.xyzw, r0.xyzw
					mov o1.xyzw, v1.xyzw
					mul r1.xyz, r0.xwyx, l(0.500000, 0.500000, -0.500000, 0.000000)
					mov o2.zw, r0.zzzw
					add o2.xy, r1.yyyy, r1.xzxx
					mad o3.xy, v2.xyxx, cb0[2].xyxx, cb0[2].zwzz
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "DISTORT_OFF" "USE_ALPHA_CLIPING" }
					"!!vs_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xy          2     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xyzw        2     NONE   float   xyzw
					// TEXCOORD                 2   xy          3     NONE   float   xy  
					//
					vs_4_0
					dcl_constantbuffer CB0[3], immediateIndexed
					dcl_constantbuffer CB1[4], immediateIndexed
					dcl_constantbuffer CB2[21], immediateIndexed
					dcl_input v0.xyz
					dcl_input v1.xyzw
					dcl_input v2.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xyzw
					dcl_output o3.xy
					dcl_temps 2
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					add r0.xyzw, r0.xyzw, cb1[3].xyzw
					mul r1.xyzw, r0.yyyy, cb2[18].xyzw
					mad r1.xyzw, cb2[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb2[19].xyzw, r0.zzzz, r1.xyzw
					mad r0.xyzw, cb2[20].xyzw, r0.wwww, r1.xyzw
					mov o0.xyzw, r0.xyzw
					mov o1.xyzw, v1.xyzw
					mul r1.xyz, r0.xwyx, l(0.500000, 0.500000, -0.500000, 0.000000)
					mov o2.zw, r0.zzzw
					add o2.xy, r1.yyyy, r1.xzxx
					mad o3.xy, v2.xyxx, cb0[2].xyxx, cb0[2].zwzz
					ret 
					// Approximately 0 instruction slots used"
				}
			}
			Program "fp" {
				SubProgram "d3d11 " {
					"!!ps_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// COLOR                    0   xyzw        1     NONE   float      w
					// TEXCOORD                 0   xyzw        2     NONE   float   xy w
					// TEXCOORD                 2   xy          3     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[9], immediateIndexed
					dcl_constantbuffer CB1[3], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_sampler s1, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_resource_texture2d (float,float,float,float) t1
					dcl_input_ps linear v1.w
					dcl_input_ps linear v2.xyw
					dcl_input_ps linear v3.xy
					dcl_output o0.xyzw
					dcl_temps 2
					sample r0.xyzw, v3.xyxx, t0.xyzw, s1
					mul r0.x, r0.w, r0.x
					mad r0.xy, r0.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
					mul r0.xy, r0.xyxx, cb1[2].xxxx
					mul r0.xy, r0.xyxx, cb0[8].xyxx
					mul r0.xy, r0.xyxx, v1.wwww
					mad r0.xy, r0.xyxx, v1.wwww, v2.xyxx
					div r0.xy, r0.xyxx, v2.wwww
					sample r0.xyzw, r0.xyxx, t1.xyzw, s0
					add r1.xyz, cb1[0].xyzx, l(-1.000000, -1.000000, -1.000000, 0.000000)
					mad r1.xyz, v1.wwww, r1.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
					mul o0.xyz, r0.xyzx, r1.xyzx
					mul r0.x, cb1[0].w, cb1[0].w
					min o0.w, r0.x, l(1.000000)
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "SOFTPARTICLES_ON" "USE_ALPHA_CLIPING" }
					"!!ps_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// COLOR                    0   xyzw        1     NONE   float      w
					// TEXCOORD                 0   xyzw        2     NONE   float   xy w
					// TEXCOORD                 2   xy          3     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[14], immediateIndexed
					dcl_constantbuffer CB1[3], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_sampler s1, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_resource_texture2d (float,float,float,float) t1
					dcl_input_ps linear v1.w
					dcl_input_ps linear v2.xyw
					dcl_input_ps linear v3.xy
					dcl_output o0.xyzw
					dcl_temps 2
					sample r0.xyzw, v3.xyxx, t0.xyzw, s1
					mul r0.x, r0.w, r0.x
					mad r0.xy, r0.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
					dp2 r0.z, r0.xyxx, r0.xyxx
					mul r0.xy, r0.xyxx, cb1[2].xxxx
					mul r0.xy, r0.xyxx, cb0[8].xyxx
					mul r0.xy, r0.xyxx, v1.wwww
					min r0.z, r0.z, l(1.000000)
					add r0.z, -r0.z, l(1.000000)
					sqrt r0.z, r0.z
					log r0.z, r0.z
					mul r0.z, r0.z, l(127.000000)
					exp r0.z, r0.z
					add r0.z, -r0.z, l(0.940000)
					mul r0.z, r0.z, cb0[13].y
					mul_sat r0.z, r0.z, l(0.100000)
					mul r0.xy, r0.zzzz, r0.xyxx
					mad r0.xy, r0.xyxx, v1.wwww, v2.xyxx
					div r0.xy, r0.xyxx, v2.wwww
					sample r1.xyzw, r0.xyxx, t1.xyzw, s0
					add r0.xyw, cb1[0].xyxz, l(-1.000000, -1.000000, 0.000000, -1.000000)
					mad r0.xyw, v1.wwww, r0.xyxw, l(1.000000, 1.000000, 0.000000, 1.000000)
					mul o0.xyz, r0.xywx, r1.xyzx
					mul r0.x, cb1[0].w, cb1[0].w
					mul r0.x, r0.z, r0.x
					min o0.w, r0.x, l(1.000000)
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "SOFTPARTICLES_ON" }
					"!!ps_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// COLOR                    0   xyzw        1     NONE   float      w
					// TEXCOORD                 0   xyzw        2     NONE   float   xy w
					// TEXCOORD                 2   xy          3     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[9], immediateIndexed
					dcl_constantbuffer CB1[3], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_sampler s1, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_resource_texture2d (float,float,float,float) t1
					dcl_input_ps linear v1.w
					dcl_input_ps linear v2.xyw
					dcl_input_ps linear v3.xy
					dcl_output o0.xyzw
					dcl_temps 2
					sample r0.xyzw, v3.xyxx, t0.xyzw, s1
					mul r0.x, r0.w, r0.x
					mad r0.xy, r0.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
					mul r0.xy, r0.xyxx, cb1[2].xxxx
					mul r0.xy, r0.xyxx, cb0[8].xyxx
					mul r0.xy, r0.xyxx, v1.wwww
					mad r0.xy, r0.xyxx, v1.wwww, v2.xyxx
					div r0.xy, r0.xyxx, v2.wwww
					sample r0.xyzw, r0.xyxx, t1.xyzw, s0
					add r1.xyz, cb1[0].xyzx, l(-1.000000, -1.000000, -1.000000, 0.000000)
					mad r1.xyz, v1.wwww, r1.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
					mul o0.xyz, r0.xyzx, r1.xyzx
					mul r0.x, cb1[0].w, cb1[0].w
					min o0.w, r0.x, l(1.000000)
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "USE_ALPHA_CLIPING" }
					"!!ps_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// COLOR                    0   xyzw        1     NONE   float      w
					// TEXCOORD                 0   xyzw        2     NONE   float   xy w
					// TEXCOORD                 2   xy          3     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[14], immediateIndexed
					dcl_constantbuffer CB1[3], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_sampler s1, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_resource_texture2d (float,float,float,float) t1
					dcl_input_ps linear v1.w
					dcl_input_ps linear v2.xyw
					dcl_input_ps linear v3.xy
					dcl_output o0.xyzw
					dcl_temps 2
					sample r0.xyzw, v3.xyxx, t0.xyzw, s1
					mul r0.x, r0.w, r0.x
					mad r0.xy, r0.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
					dp2 r0.z, r0.xyxx, r0.xyxx
					mul r0.xy, r0.xyxx, cb1[2].xxxx
					mul r0.xy, r0.xyxx, cb0[8].xyxx
					mul r0.xy, r0.xyxx, v1.wwww
					min r0.z, r0.z, l(1.000000)
					add r0.z, -r0.z, l(1.000000)
					sqrt r0.z, r0.z
					log r0.z, r0.z
					mul r0.z, r0.z, l(127.000000)
					exp r0.z, r0.z
					add r0.z, -r0.z, l(0.940000)
					mul r0.z, r0.z, cb0[13].y
					mul_sat r0.z, r0.z, l(0.100000)
					mul r0.xy, r0.zzzz, r0.xyxx
					mad r0.xy, r0.xyxx, v1.wwww, v2.xyxx
					div r0.xy, r0.xyxx, v2.wwww
					sample r1.xyzw, r0.xyxx, t1.xyzw, s0
					add r0.xyw, cb1[0].xyxz, l(-1.000000, -1.000000, 0.000000, -1.000000)
					mad r0.xyw, v1.wwww, r0.xyxw, l(1.000000, 1.000000, 0.000000, 1.000000)
					mul o0.xyz, r0.xywx, r1.xyzx
					mul r0.x, cb1[0].w, cb1[0].w
					mul r0.x, r0.z, r0.x
					min o0.w, r0.x, l(1.000000)
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "DISTORT_OFF" }
					"!!ps_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// COLOR                    0   xyzw        1     NONE   float       
					// TEXCOORD                 0   xyzw        2     NONE   float       
					// TEXCOORD                 2   xy          3     NONE   float       
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_output o0.xyzw
					mov o0.xyzw, l(0,0,0,0)
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "SOFTPARTICLES_ON" "DISTORT_OFF" "USE_ALPHA_CLIPING" }
					"!!ps_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// COLOR                    0   xyzw        1     NONE   float       
					// TEXCOORD                 0   xyzw        2     NONE   float       
					// TEXCOORD                 2   xy          3     NONE   float       
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_output o0.xyzw
					mov o0.xyzw, l(0,0,0,0)
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "SOFTPARTICLES_ON" "DISTORT_OFF" }
					"!!ps_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// COLOR                    0   xyzw        1     NONE   float       
					// TEXCOORD                 0   xyzw        2     NONE   float       
					// TEXCOORD                 2   xy          3     NONE   float       
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_output o0.xyzw
					mov o0.xyzw, l(0,0,0,0)
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "DISTORT_OFF" "USE_ALPHA_CLIPING" }
					"!!ps_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// COLOR                    0   xyzw        1     NONE   float       
					// TEXCOORD                 0   xyzw        2     NONE   float       
					// TEXCOORD                 2   xy          3     NONE   float       
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_output o0.xyzw
					mov o0.xyzw, l(0,0,0,0)
					ret 
					// Approximately 0 instruction slots used"
				}
			}
		}
	}
	CustomEditor "RFX4_UberDistortionGUI"
}