Shader "KriptoFX/ME/Gold" {
	Properties {
		_MainColor ("Color", Vector) = (1,1,1,1)
		_MainTex ("Albedo (RGB)", 2D) = "white" {}
		_Cutoff ("Cutoff", Range(0, 0.9)) = 0.5
		_SpeedDistort ("Speed(XY) Distort(ZW)", Vector) = (1,0,0,0)
	}
	SubShader {
		Pass {
			GpuProgramID 33559
			Program "vp" {
				SubProgram "d3d11 " {
					"!!vs_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyzw
					// COLOR                    0   xyzw        1     NONE   float       
					// NORMAL                   0   xyz         2     NONE   float   xyz 
					// TEXCOORD                 0   xy          3     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// COLOR                    0   xyz         1     NONE   float   xyz 
					// TEXCOORD                 0   xy          2     NONE   float   xy  
					// NORMAL                   0   xyz         3     NONE   float   xyz 
					// TEXCOORD                 1   xyz         4     NONE   float   xyz 
					//
					vs_4_0
					dcl_constantbuffer CB0[85], dynamicIndexed
					dcl_constantbuffer CB1[5], immediateIndexed
					dcl_constantbuffer CB2[7], immediateIndexed
					dcl_constantbuffer CB3[21], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_input v0.xyzw
					dcl_input v2.xyz
					dcl_input v3.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyz
					dcl_output o2.xy
					dcl_output o3.xyz
					dcl_output o4.xyz
					dcl_temps 7
					mul r0.xyzw, v0.yyyy, cb2[1].xyzw
					mad r0.xyzw, cb2[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb2[2].xyzw, v0.zzzz, r0.xyzw
					add r1.xyzw, r0.xyzw, cb2[3].xyzw
					mul r2.xyzw, r1.yyyy, cb3[18].xyzw
					mad r2.xyzw, cb3[17].xyzw, r1.xxxx, r2.xyzw
					mad r2.xyzw, cb3[19].xyzw, r1.zzzz, r2.xyzw
					mad o0.xyzw, cb3[20].xyzw, r1.wwww, r2.xyzw
					mad r0.xyz, cb2[3].xyzx, v0.wwww, r0.xyzx
					dp3 r1.x, v2.xyzx, cb2[4].xyzx
					dp3 r1.y, v2.xyzx, cb2[5].xyzx
					dp3 r1.z, v2.xyzx, cb2[6].xyzx
					dp3 r0.w, r1.xyzx, r1.xyzx
					rsq r0.w, r0.w
					mul r1.xyz, r0.wwww, r1.xyzx
					mov r2.xyz, l(0,0,0,0)
					mov r0.w, l(0)
					loop 
					  ige r1.w, r0.w, cb0[83].x
					  breakc_nz r1.w
					  mad r3.xyz, -r0.xyzx, cb0[r0.w + 43].wwww, cb0[r0.w + 3].xyzx
					  dp3 r1.w, r3.xyzx, r3.xyzx
					  sqrt r2.w, r1.w
					  div r2.w, r2.w, cb0[r0.w + 3].w
					  sample_l r4.xyzw, r2.wwww, t0.xyzw, s0, l(0.000000)
					  add r2.w, r4.x, l(-1.000000)
					  mad r2.w, cb0[r0.w + 43].w, r2.w, l(1.000000)
					  rsq r1.w, r1.w
					  mul r3.xyz, r1.wwww, r3.xyzx
					  dp3 r1.w, r1.xyzx, r3.xyzx
					  max r1.w, r1.w, l(0.000000)
					  mul r1.w, r2.w, r1.w
					  mad r2.xyz, cb0[r0.w + 43].xyzx, r1.wwww, r2.xyzx
					  iadd r0.w, r0.w, l(1)
					endloop 
					dp3 r3.x, l(1.000000, 1.000000, 1.000000, 0.000000), cb2[4].xyzx
					dp3 r3.y, l(1.000000, 1.000000, 1.000000, 0.000000), cb2[5].xyzx
					dp3 r3.z, l(1.000000, 1.000000, 1.000000, 0.000000), cb2[6].xyzx
					dp3 r0.w, r3.xyzx, r3.xyzx
					rsq r0.w, r0.w
					mul r3.xyz, r0.wwww, r3.xyzx
					mov r4.xyz, l(0,0,0,0)
					mov r0.w, l(0)
					loop 
					  ige r1.w, r0.w, cb0[83].x
					  breakc_nz r1.w
					  mad r5.xyz, -r0.xyzx, cb0[r0.w + 43].wwww, cb0[r0.w + 3].xyzx
					  dp3 r1.w, r5.xyzx, r5.xyzx
					  sqrt r2.w, r1.w
					  div r2.w, r2.w, cb0[r0.w + 3].w
					  sample_l r6.xyzw, r2.wwww, t0.xyzw, s0, l(0.000000)
					  add r2.w, r6.x, l(-1.000000)
					  mad r2.w, cb0[r0.w + 43].w, r2.w, l(1.000000)
					  rsq r1.w, r1.w
					  mul r5.xyz, r1.wwww, r5.xyzx
					  dp3 r1.w, r3.xyzx, r5.xyzx
					  max r1.w, r1.w, l(0.000000)
					  mul r1.w, r2.w, r1.w
					  mad r4.xyz, cb0[r0.w + 43].xyzx, r1.wwww, r4.xyzx
					  iadd r0.w, r0.w, l(1)
					endloop 
					mul r3.xyz, r4.xyzx, l(3.000000, 3.000000, 3.000000, 0.000000)
					max r2.xyz, r2.xyzx, r3.xyzx
					dp3 r0.w, r2.xyzx, l(0.330000, 0.330000, 0.330000, 0.000000)
					add r2.xyz, -r0.wwww, r2.xyzx
					mad o1.xyz, r2.xyzx, l(0.250000, 0.250000, 0.250000, 0.000000), r0.wwww
					mad o2.xy, v3.xyxx, cb0[84].xyxx, cb0[84].zwzz
					add r0.xyz, -r0.xyzx, cb1[4].xyzx
					dp3 r0.w, r0.xyzx, r0.xyzx
					rsq r0.w, r0.w
					mul o4.xyz, r0.wwww, r0.xyzx
					mov o3.xyz, r1.xyzx
					ret 
					// Approximately 0 instruction slots used"
				}
			}
			Program "fp" {
				SubProgram "d3d11 " {
					"!!ps_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// COLOR                    0   xyz         1     NONE   float   xyz 
					// TEXCOORD                 0   xy          2     NONE   float   xy  
					// NORMAL                   0   xyz         3     NONE   float   xyz 
					// TEXCOORD                 1   xyz         4     NONE   float   xyz 
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[88], immediateIndexed
					dcl_constantbuffer CB1[1], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_sampler s1, mode_default
					dcl_resource_texturecube (float,float,float,float) t0
					dcl_resource_texture2d (float,float,float,float) t1
					dcl_input_ps linear v1.xyz
					dcl_input_ps linear v2.xy
					dcl_input_ps linear v3.xyz
					dcl_input_ps linear v4.xyz
					dcl_output o0.xyzw
					dcl_temps 2
					mul r0.xy, cb0[87].xyxx, cb1[0].xxxx
					mad r0.zw, cb1[0].xxxx, cb0[87].xxxy, v2.xxxy
					sample r1.xyzw, r0.zwzz, t1.xyzw, s0
					mad r0.zw, r1.xxxy, cb0[87].zzzw, v2.xxxy
					mad r0.xy, -r0.xyxx, l(1.400000, 1.400000, 0.000000, 0.000000), r0.zwzz
					sample r0.xyzw, r0.xyxx, t1.xyzw, s0
					add r0.y, -cb0[85].x, l(1.000000)
					add r0.y, -r0.y, cb0[86].w
					lt r0.x, r0.y, r0.x
					discard_nz r0.x
					dp3 r0.x, -v4.xyzx, v3.xyzx
					add r0.x, r0.x, r0.x
					mad r0.xyz, v3.xyzx, -r0.xxxx, -v4.xyzx
					sample r0.xyzw, r0.xyzx, t0.xyzw, s1
					dp3_sat r0.w, v4.xyzx, v3.xyzx
					add r0.w, -r0.w, l(1.000000)
					mul r0.w, r0.w, r0.w
					mul r0.xyz, r0.xyzx, cb0[86].xyzx
					mul r1.xyz, r0.wwww, v1.xyzx
					mul r1.xyz, r1.xyzx, cb0[86].xyzx
					mul r1.xyz, r1.xyzx, l(0.250000, 0.250000, 0.250000, 0.000000)
					mad_sat o0.xyz, r0.xyzx, l(1.500000, 1.500000, 1.500000, 0.000000), r1.xyzx
					mov o0.w, l(1.000000)
					ret 
					// Approximately 0 instruction slots used"
				}
			}
		}
		Pass {
			Tags { "LIGHTMODE" = "SHADOWCASTER" "QUEUE" = "Transparent" "SHADOWSUPPORT" = "true" }
			GpuProgramID 106802
			Program "vp" {
				SubProgram "d3d11 " {
					Keywords { "SHADOWS_DEPTH" }
					"!!vs_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// TEXCOORD                 0   xy          0     NONE   float   xy  
					// POSITION                 0   xyzw        1     NONE   float   xyzw
					// NORMAL                   0   xyz         2     NONE   float   xyz 
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// TEXCOORD                 3   xy          0     NONE   float   xy  
					// SV_POSITION              0   xyzw        1      POS   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[3], immediateIndexed
					dcl_constantbuffer CB1[1], immediateIndexed
					dcl_constantbuffer CB2[6], immediateIndexed
					dcl_constantbuffer CB3[7], immediateIndexed
					dcl_constantbuffer CB4[21], immediateIndexed
					dcl_input v0.xy
					dcl_input v1.xyzw
					dcl_input v2.xyz
					dcl_output o0.xy
					dcl_output_siv o1.xyzw, position
					dcl_temps 3
					mad o0.xy, v0.xyxx, cb0[2].xyxx, cb0[2].zwzz
					dp3 r0.x, v2.xyzx, cb3[4].xyzx
					dp3 r0.y, v2.xyzx, cb3[5].xyzx
					dp3 r0.z, v2.xyzx, cb3[6].xyzx
					dp3 r0.w, r0.xyzx, r0.xyzx
					rsq r0.w, r0.w
					mul r0.xyz, r0.wwww, r0.xyzx
					mul r1.xyzw, v1.yyyy, cb3[1].xyzw
					mad r1.xyzw, cb3[0].xyzw, v1.xxxx, r1.xyzw
					mad r1.xyzw, cb3[2].xyzw, v1.zzzz, r1.xyzw
					mad r1.xyzw, cb3[3].xyzw, v1.wwww, r1.xyzw
					mad r2.xyz, -r1.xyzx, cb1[0].wwww, cb1[0].xyzx
					dp3 r0.w, r2.xyzx, r2.xyzx
					rsq r0.w, r0.w
					mul r2.xyz, r0.wwww, r2.xyzx
					dp3 r0.w, r0.xyzx, r2.xyzx
					mad r0.w, -r0.w, r0.w, l(1.000000)
					sqrt r0.w, r0.w
					mul r0.w, r0.w, cb2[5].z
					mad r0.xyz, -r0.xyzx, r0.wwww, r1.xyzx
					ne r0.w, cb2[5].z, l(0.000000)
					movc r0.xyz, r0.wwww, r0.xyzx, r1.xyzx
					mul r2.xyzw, r0.yyyy, cb4[18].xyzw
					mad r2.xyzw, cb4[17].xyzw, r0.xxxx, r2.xyzw
					mad r0.xyzw, cb4[19].xyzw, r0.zzzz, r2.xyzw
					mad r0.xyzw, cb4[20].xyzw, r1.wwww, r0.xyzw
					div r1.x, cb2[5].x, r0.w
					min r1.x, r1.x, l(0.000000)
					max r1.x, r1.x, l(-1.000000)
					add r0.z, r0.z, r1.x
					min r1.x, r0.w, r0.z
					mov o1.xyw, r0.xyxw
					add r0.x, -r0.z, r1.x
					mad o1.z, cb2[5].y, r0.x, r0.z
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "SHADOWS_CUBE" }
					"!!vs_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// TEXCOORD                 0   xy          0     NONE   float   xy  
					// POSITION                 0   xyzw        1     NONE   float   xyzw
					// NORMAL                   0   xyz         2     NONE   float   xyz 
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// TEXCOORD                 3   xy          0     NONE   float   xy  
					// SV_POSITION              0   xyzw        1      POS   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[3], immediateIndexed
					dcl_constantbuffer CB1[1], immediateIndexed
					dcl_constantbuffer CB2[6], immediateIndexed
					dcl_constantbuffer CB3[7], immediateIndexed
					dcl_constantbuffer CB4[21], immediateIndexed
					dcl_input v0.xy
					dcl_input v1.xyzw
					dcl_input v2.xyz
					dcl_output o0.xy
					dcl_output_siv o1.xyzw, position
					dcl_temps 3
					mad o0.xy, v0.xyxx, cb0[2].xyxx, cb0[2].zwzz
					dp3 r0.x, v2.xyzx, cb3[4].xyzx
					dp3 r0.y, v2.xyzx, cb3[5].xyzx
					dp3 r0.z, v2.xyzx, cb3[6].xyzx
					dp3 r0.w, r0.xyzx, r0.xyzx
					rsq r0.w, r0.w
					mul r0.xyz, r0.wwww, r0.xyzx
					mul r1.xyzw, v1.yyyy, cb3[1].xyzw
					mad r1.xyzw, cb3[0].xyzw, v1.xxxx, r1.xyzw
					mad r1.xyzw, cb3[2].xyzw, v1.zzzz, r1.xyzw
					mad r1.xyzw, cb3[3].xyzw, v1.wwww, r1.xyzw
					mad r2.xyz, -r1.xyzx, cb1[0].wwww, cb1[0].xyzx
					dp3 r0.w, r2.xyzx, r2.xyzx
					rsq r0.w, r0.w
					mul r2.xyz, r0.wwww, r2.xyzx
					dp3 r0.w, r0.xyzx, r2.xyzx
					mad r0.w, -r0.w, r0.w, l(1.000000)
					sqrt r0.w, r0.w
					mul r0.w, r0.w, cb2[5].z
					mad r0.xyz, -r0.xyzx, r0.wwww, r1.xyzx
					ne r0.w, cb2[5].z, l(0.000000)
					movc r0.xyz, r0.wwww, r0.xyzx, r1.xyzx
					mul r2.xyzw, r0.yyyy, cb4[18].xyzw
					mad r2.xyzw, cb4[17].xyzw, r0.xxxx, r2.xyzw
					mad r0.xyzw, cb4[19].xyzw, r0.zzzz, r2.xyzw
					mad r0.xyzw, cb4[20].xyzw, r1.wwww, r0.xyzw
					min r1.x, r0.w, r0.z
					add r1.x, -r0.z, r1.x
					mad o1.z, cb2[5].y, r1.x, r0.z
					mov o1.xyw, r0.xyxw
					ret 
					// Approximately 0 instruction slots used"
				}
			}
			Program "fp" {
				SubProgram "d3d11 " {
					Keywords { "SHADOWS_DEPTH" }
					"!!ps_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// TEXCOORD                 3   xy          0     NONE   float   xy  
					// SV_POSITION              0   xyzw        1      POS   float       
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[6], immediateIndexed
					dcl_constantbuffer CB1[1], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_input_ps linear v0.xy
					dcl_output o0.xyzw
					dcl_temps 2
					mul r0.xy, cb0[5].xyxx, cb1[0].xxxx
					mad r0.zw, cb1[0].xxxx, cb0[5].xxxy, v0.xxxy
					sample r1.xyzw, r0.zwzz, t0.xyzw, s0
					mad r0.zw, r1.xxxy, cb0[5].zzzw, v0.xxxy
					mad r0.xy, -r0.xyxx, l(1.400000, 1.400000, 0.000000, 0.000000), r0.zwzz
					sample r0.xyzw, r0.xyxx, t0.xyzw, s0
					add r0.y, -cb0[3].x, l(1.000000)
					add r0.y, -r0.y, cb0[4].w
					lt r0.x, r0.y, r0.x
					discard_nz r0.x
					mov o0.xyzw, l(0,0,0,0)
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "SHADOWS_CUBE" }
					"!!ps_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// TEXCOORD                 3   xy          0     NONE   float   xy  
					// SV_POSITION              0   xyzw        1      POS   float       
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[6], immediateIndexed
					dcl_constantbuffer CB1[1], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_input_ps linear v0.xy
					dcl_output o0.xyzw
					dcl_temps 2
					mul r0.xy, cb0[5].xyxx, cb1[0].xxxx
					mad r0.zw, cb1[0].xxxx, cb0[5].xxxy, v0.xxxy
					sample r1.xyzw, r0.zwzz, t0.xyzw, s0
					mad r0.zw, r1.xxxy, cb0[5].zzzw, v0.xxxy
					mad r0.xy, -r0.xyxx, l(1.400000, 1.400000, 0.000000, 0.000000), r0.zwzz
					sample r0.xyzw, r0.xyxx, t0.xyzw, s0
					add r0.y, -cb0[3].x, l(1.000000)
					add r0.y, -r0.y, cb0[4].w
					lt r0.x, r0.y, r0.x
					discard_nz r0.x
					mov o0.xyzw, l(0,0,0,0)
					ret 
					// Approximately 0 instruction slots used"
				}
			}
		}
	}
}