Shader "Morph3D/EyeAndLash" {
	Properties {
		_Color ("Color", Vector) = (1,1,1,1)
		_MainTex ("Albedo (RGB)", 2D) = "white" {}
		_Spread ("Spread", Range(0, 128)) = 64
	}
	SubShader {
		LOD 200
		Tags { "IGNOREPROJECTOR" = "true" "QUEUE" = "Transparent" "RenderType" = "Transparent" }
		Pass {
			Name "FORWARD"
			LOD 200
			Tags { "IGNOREPROJECTOR" = "true" "LIGHTMODE" = "FORWARDBASE" "QUEUE" = "Transparent" "RenderType" = "Transparent" }
			Blend SrcAlpha OneMinusSrcAlpha, SrcAlpha OneMinusSrcAlpha
			ColorMask RGB -1
			ZTest Less
			ZWrite Off
			GpuProgramID 31631
			Program "vp" {
				SubProgram "d3d11 " {
					Keywords { "DIRECTIONAL" }
					"!!vs_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyzw
					// TANGENT                  0   xyzw        1     NONE   float       
					// NORMAL                   0   xyz         2     NONE   float   xyz 
					// TEXCOORD                 0   xyzw        3     NONE   float   xy  
					// TEXCOORD                 1   xyzw        4     NONE   float       
					// TEXCOORD                 2   xyzw        5     NONE   float       
					// TEXCOORD                 3   xyzw        6     NONE   float       
					// COLOR                    0   xyzw        7     NONE   float       
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					// TEXCOORD                 1   xyz         2     NONE   float   xyz 
					// TEXCOORD                 2   xyz         3     NONE   float   xyz 
					// TEXCOORD                 3   xyz         4     NONE   float   xyz 
					// TEXCOORD                 6   xyzw        5     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[7], immediateIndexed
					dcl_constantbuffer CB1[7], immediateIndexed
					dcl_constantbuffer CB2[21], immediateIndexed
					dcl_input v0.xyzw
					dcl_input v2.xyz
					dcl_input v3.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xy
					dcl_output o2.xyz
					dcl_output o3.xyz
					dcl_output o4.xyz
					dcl_output o5.xyzw
					dcl_temps 2
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					add r1.xyzw, r0.xyzw, cb1[3].xyzw
					mad o3.xyz, cb1[3].xyzx, v0.wwww, r0.xyzx
					mul r0.xyzw, r1.yyyy, cb2[18].xyzw
					mad r0.xyzw, cb2[17].xyzw, r1.xxxx, r0.xyzw
					mad r0.xyzw, cb2[19].xyzw, r1.zzzz, r0.xyzw
					mad o0.xyzw, cb2[20].xyzw, r1.wwww, r0.xyzw
					mad o1.xy, v3.xyxx, cb0[6].xyxx, cb0[6].zwzz
					dp3 r0.x, v2.xyzx, cb1[4].xyzx
					dp3 r0.y, v2.xyzx, cb1[5].xyzx
					dp3 r0.z, v2.xyzx, cb1[6].xyzx
					dp3 r0.w, r0.xyzx, r0.xyzx
					rsq r0.w, r0.w
					mul o2.xyz, r0.wwww, r0.xyzx
					mov o4.xyz, l(0,0,0,0)
					mov o5.xyzw, l(0,0,0,0)
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "DIRECTIONAL" "LIGHTPROBE_SH" }
					"!!vs_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyzw
					// TANGENT                  0   xyzw        1     NONE   float       
					// NORMAL                   0   xyz         2     NONE   float   xyz 
					// TEXCOORD                 0   xyzw        3     NONE   float   xy  
					// TEXCOORD                 1   xyzw        4     NONE   float       
					// TEXCOORD                 2   xyzw        5     NONE   float       
					// TEXCOORD                 3   xyzw        6     NONE   float       
					// COLOR                    0   xyzw        7     NONE   float       
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					// TEXCOORD                 1   xyz         2     NONE   float   xyz 
					// TEXCOORD                 2   xyz         3     NONE   float   xyz 
					// TEXCOORD                 3   xyz         4     NONE   float   xyz 
					// TEXCOORD                 6   xyzw        5     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[7], immediateIndexed
					dcl_constantbuffer CB1[46], immediateIndexed
					dcl_constantbuffer CB2[7], immediateIndexed
					dcl_constantbuffer CB3[21], immediateIndexed
					dcl_input v0.xyzw
					dcl_input v2.xyz
					dcl_input v3.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xy
					dcl_output o2.xyz
					dcl_output o3.xyz
					dcl_output o4.xyz
					dcl_output o5.xyzw
					dcl_temps 4
					mul r0.xyzw, v0.yyyy, cb2[1].xyzw
					mad r0.xyzw, cb2[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb2[2].xyzw, v0.zzzz, r0.xyzw
					add r1.xyzw, r0.xyzw, cb2[3].xyzw
					mad o3.xyz, cb2[3].xyzx, v0.wwww, r0.xyzx
					mul r0.xyzw, r1.yyyy, cb3[18].xyzw
					mad r0.xyzw, cb3[17].xyzw, r1.xxxx, r0.xyzw
					mad r0.xyzw, cb3[19].xyzw, r1.zzzz, r0.xyzw
					mad o0.xyzw, cb3[20].xyzw, r1.wwww, r0.xyzw
					mad o1.xy, v3.xyxx, cb0[6].xyxx, cb0[6].zwzz
					dp3 r0.x, v2.xyzx, cb2[4].xyzx
					dp3 r0.y, v2.xyzx, cb2[5].xyzx
					dp3 r0.z, v2.xyzx, cb2[6].xyzx
					dp3 r0.w, r0.xyzx, r0.xyzx
					rsq r0.w, r0.w
					mul r0.xyz, r0.wwww, r0.xyzx
					mov o2.xyz, r0.xyzx
					mul r1.x, r0.y, r0.y
					mad r1.x, r0.x, r0.x, -r1.x
					mul r2.xyzw, r0.yzzx, r0.xyzz
					dp4 r3.x, cb1[42].xyzw, r2.xyzw
					dp4 r3.y, cb1[43].xyzw, r2.xyzw
					dp4 r3.z, cb1[44].xyzw, r2.xyzw
					mad r1.xyz, cb1[45].xyzx, r1.xxxx, r3.xyzx
					mov r0.w, l(1.000000)
					dp4 r2.x, cb1[39].xyzw, r0.xyzw
					dp4 r2.y, cb1[40].xyzw, r0.xyzw
					dp4 r2.z, cb1[41].xyzw, r0.xyzw
					add r0.xyz, r1.xyzx, r2.xyzx
					max r0.xyz, r0.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
					log r0.xyz, r0.xyzx
					mul r0.xyz, r0.xyzx, l(0.416667, 0.416667, 0.416667, 0.000000)
					exp r0.xyz, r0.xyzx
					mad r0.xyz, r0.xyzx, l(1.055000, 1.055000, 1.055000, 0.000000), l(-0.055000, -0.055000, -0.055000, 0.000000)
					max o4.xyz, r0.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
					mov o5.xyzw, l(0,0,0,0)
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "DIRECTIONAL" "LIGHTPROBE_SH" "VERTEXLIGHT_ON" }
					"!!vs_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyzw
					// TANGENT                  0   xyzw        1     NONE   float       
					// NORMAL                   0   xyz         2     NONE   float   xyz 
					// TEXCOORD                 0   xyzw        3     NONE   float   xy  
					// TEXCOORD                 1   xyzw        4     NONE   float       
					// TEXCOORD                 2   xyzw        5     NONE   float       
					// TEXCOORD                 3   xyzw        6     NONE   float       
					// COLOR                    0   xyzw        7     NONE   float       
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					// TEXCOORD                 1   xyz         2     NONE   float   xyz 
					// TEXCOORD                 2   xyz         3     NONE   float   xyz 
					// TEXCOORD                 3   xyz         4     NONE   float   xyz 
					// TEXCOORD                 6   xyzw        5     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[7], immediateIndexed
					dcl_constantbuffer CB1[46], immediateIndexed
					dcl_constantbuffer CB2[7], immediateIndexed
					dcl_constantbuffer CB3[21], immediateIndexed
					dcl_input v0.xyzw
					dcl_input v2.xyz
					dcl_input v3.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xy
					dcl_output o2.xyz
					dcl_output o3.xyz
					dcl_output o4.xyz
					dcl_output o5.xyzw
					dcl_temps 6
					mul r0.xyzw, v0.yyyy, cb2[1].xyzw
					mad r0.xyzw, cb2[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb2[2].xyzw, v0.zzzz, r0.xyzw
					add r1.xyzw, r0.xyzw, cb2[3].xyzw
					mad r0.xyz, cb2[3].xyzx, v0.wwww, r0.xyzx
					mul r2.xyzw, r1.yyyy, cb3[18].xyzw
					mad r2.xyzw, cb3[17].xyzw, r1.xxxx, r2.xyzw
					mad r2.xyzw, cb3[19].xyzw, r1.zzzz, r2.xyzw
					mad o0.xyzw, cb3[20].xyzw, r1.wwww, r2.xyzw
					mad o1.xy, v3.xyxx, cb0[6].xyxx, cb0[6].zwzz
					dp3 r1.x, v2.xyzx, cb2[4].xyzx
					dp3 r1.y, v2.xyzx, cb2[5].xyzx
					dp3 r1.z, v2.xyzx, cb2[6].xyzx
					dp3 r0.w, r1.xyzx, r1.xyzx
					rsq r0.w, r0.w
					mul r1.xyz, r0.wwww, r1.xyzx
					mov o2.xyz, r1.xyzx
					mov o3.xyz, r0.xyzx
					mul r0.w, r1.y, r1.y
					mad r0.w, r1.x, r1.x, -r0.w
					mul r2.xyzw, r1.yzzx, r1.xyzz
					dp4 r3.x, cb1[42].xyzw, r2.xyzw
					dp4 r3.y, cb1[43].xyzw, r2.xyzw
					dp4 r3.z, cb1[44].xyzw, r2.xyzw
					mad r2.xyz, cb1[45].xyzx, r0.wwww, r3.xyzx
					mov r1.w, l(1.000000)
					dp4 r3.x, cb1[39].xyzw, r1.xyzw
					dp4 r3.y, cb1[40].xyzw, r1.xyzw
					dp4 r3.z, cb1[41].xyzw, r1.xyzw
					add r2.xyz, r2.xyzx, r3.xyzx
					max r2.xyz, r2.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
					log r2.xyz, r2.xyzx
					mul r2.xyz, r2.xyzx, l(0.416667, 0.416667, 0.416667, 0.000000)
					exp r2.xyz, r2.xyzx
					mad r2.xyz, r2.xyzx, l(1.055000, 1.055000, 1.055000, 0.000000), l(-0.055000, -0.055000, -0.055000, 0.000000)
					max r2.xyz, r2.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
					add r3.xyzw, -r0.yyyy, cb1[4].xyzw
					mul r4.xyzw, r1.yyyy, r3.xyzw
					mul r3.xyzw, r3.xyzw, r3.xyzw
					add r5.xyzw, -r0.xxxx, cb1[3].xyzw
					add r0.xyzw, -r0.zzzz, cb1[5].xyzw
					mad r4.xyzw, r5.xyzw, r1.xxxx, r4.xyzw
					mad r1.xyzw, r0.xyzw, r1.zzzz, r4.xyzw
					mad r3.xyzw, r5.xyzw, r5.xyzw, r3.xyzw
					mad r0.xyzw, r0.xyzw, r0.xyzw, r3.xyzw
					max r0.xyzw, r0.xyzw, l(0.000001, 0.000001, 0.000001, 0.000001)
					rsq r3.xyzw, r0.xyzw
					mad r0.xyzw, r0.xyzw, cb1[6].xyzw, l(1.000000, 1.000000, 1.000000, 1.000000)
					div r0.xyzw, l(1.000000, 1.000000, 1.000000, 1.000000), r0.xyzw
					mul r1.xyzw, r1.xyzw, r3.xyzw
					max r1.xyzw, r1.xyzw, l(0.000000, 0.000000, 0.000000, 0.000000)
					mul r0.xyzw, r0.xyzw, r1.xyzw
					mul r1.xyz, r0.yyyy, cb1[8].xyzx
					mad r1.xyz, cb1[7].xyzx, r0.xxxx, r1.xyzx
					mad r0.xyz, cb1[9].xyzx, r0.zzzz, r1.xyzx
					mad r0.xyz, cb1[10].xyzx, r0.wwww, r0.xyzx
					add o4.xyz, r0.xyzx, r2.xyzx
					mov o5.xyzw, l(0,0,0,0)
					ret 
					// Approximately 0 instruction slots used"
				}
			}
			Program "fp" {
				SubProgram "d3d11 " {
					Keywords { "DIRECTIONAL" }
					"!!ps_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					// TEXCOORD                 1   xyz         2     NONE   float   xyz 
					// TEXCOORD                 2   xyz         3     NONE   float   xyz 
					// TEXCOORD                 3   xyz         4     NONE   float   xyz 
					// TEXCOORD                 6   xyzw        5     NONE   float       
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[6], immediateIndexed
					dcl_constantbuffer CB1[5], immediateIndexed
					dcl_constantbuffer CB2[47], immediateIndexed
					dcl_constantbuffer CB3[7], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_sampler s1, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_resource_texture3d (float,float,float,float) t1
					dcl_input_ps linear v1.xy
					dcl_input_ps linear v2.xyz
					dcl_input_ps linear v3.xyz
					dcl_input_ps linear v4.xyz
					dcl_output o0.xyzw
					dcl_temps 4
					add r0.xyz, -v3.xyzx, cb1[4].xyzx
					dp3 r0.w, r0.xyzx, r0.xyzx
					rsq r0.w, r0.w
					mul r0.xyz, r0.wwww, r0.xyzx
					sample r1.xyzw, v1.xyxx, t0.xyzw, s1
					mul r1.xyzw, r1.xyzw, cb0[5].xyzw
					eq r0.w, cb3[0].x, l(1.000000)
					if_nz r0.w
					  eq r0.w, cb3[0].y, l(1.000000)
					  mul r2.xyz, v3.yyyy, cb3[2].xyzx
					  mad r2.xyz, cb3[1].xyzx, v3.xxxx, r2.xyzx
					  mad r2.xyz, cb3[3].xyzx, v3.zzzz, r2.xyzx
					  add r2.xyz, r2.xyzx, cb3[4].xyzx
					  movc r2.xyz, r0.wwww, r2.xyzx, v3.xyzx
					  add r2.xyz, r2.xyzx, -cb3[6].xyzx
					  mul r2.yzw, r2.xxyz, cb3[5].xxyz
					  mad r0.w, r2.y, l(0.250000), l(0.750000)
					  mad r2.y, cb3[0].z, l(0.500000), l(0.750000)
					  max r2.x, r0.w, r2.y
					  sample r2.xyzw, r2.xzwx, t1.xyzw, s0
					else 
					  mov r2.xyzw, l(1.000000,1.000000,1.000000,1.000000)
					endif 
					dp4_sat r0.w, r2.xyzw, cb2[46].xyzw
					mul r2.xyz, r1.xyzx, v4.xyzx
					dp3 r3.x, v2.xyzx, cb2[0].xyzx
					mul r1.xyz, r1.xyzx, cb0[2].xyzx
					mul r0.w, r0.w, r3.x
					mul r3.xyz, r0.wwww, r1.xyzx
					lt r0.w, l(0.415000), v1.x
					dp3 r1.x, cb2[0].xyzx, cb2[0].xyzx
					rsq r1.x, r1.x
					mad r0.xyz, cb2[0].xyzx, r1.xxxx, r0.xyzx
					dp3 r1.x, r0.xyzx, r0.xyzx
					rsq r1.x, r1.x
					mul r0.xyz, r0.xyzx, r1.xxxx
					dp3 r0.x, v2.xyzx, r0.xyzx
					max r0.x, r0.x, l(0.000000)
					log r0.x, r0.x
					mul r0.x, r0.x, cb0[4].x
					exp r0.x, r0.x
					lt r0.y, l(0.500000), r0.x
					mul r0.z, r0.x, l(1.500000)
					movc r0.x, r0.y, r0.z, r0.x
					min r0.x, r0.x, l(1.000000)
					movc r3.w, r0.w, r0.x, r1.w
					mov r2.w, l(0)
					add o0.xyzw, r2.xyzw, r3.xyzw
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "DIRECTIONAL" "LIGHTPROBE_SH" }
					"!!ps_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					// TEXCOORD                 1   xyz         2     NONE   float   xyz 
					// TEXCOORD                 2   xyz         3     NONE   float   xyz 
					// TEXCOORD                 3   xyz         4     NONE   float   xyz 
					// TEXCOORD                 6   xyzw        5     NONE   float       
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[6], immediateIndexed
					dcl_constantbuffer CB1[5], immediateIndexed
					dcl_constantbuffer CB2[47], immediateIndexed
					dcl_constantbuffer CB3[7], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_sampler s1, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_resource_texture3d (float,float,float,float) t1
					dcl_input_ps linear v1.xy
					dcl_input_ps linear v2.xyz
					dcl_input_ps linear v3.xyz
					dcl_input_ps linear v4.xyz
					dcl_output o0.xyzw
					dcl_temps 4
					add r0.xyz, -v3.xyzx, cb1[4].xyzx
					dp3 r0.w, r0.xyzx, r0.xyzx
					rsq r0.w, r0.w
					mul r0.xyz, r0.wwww, r0.xyzx
					sample r1.xyzw, v1.xyxx, t0.xyzw, s1
					mul r1.xyzw, r1.xyzw, cb0[5].xyzw
					eq r0.w, cb3[0].x, l(1.000000)
					if_nz r0.w
					  eq r0.w, cb3[0].y, l(1.000000)
					  mul r2.xyz, v3.yyyy, cb3[2].xyzx
					  mad r2.xyz, cb3[1].xyzx, v3.xxxx, r2.xyzx
					  mad r2.xyz, cb3[3].xyzx, v3.zzzz, r2.xyzx
					  add r2.xyz, r2.xyzx, cb3[4].xyzx
					  movc r2.xyz, r0.wwww, r2.xyzx, v3.xyzx
					  add r2.xyz, r2.xyzx, -cb3[6].xyzx
					  mul r2.yzw, r2.xxyz, cb3[5].xxyz
					  mad r0.w, r2.y, l(0.250000), l(0.750000)
					  mad r2.y, cb3[0].z, l(0.500000), l(0.750000)
					  max r2.x, r0.w, r2.y
					  sample r2.xyzw, r2.xzwx, t1.xyzw, s0
					else 
					  mov r2.xyzw, l(1.000000,1.000000,1.000000,1.000000)
					endif 
					dp4_sat r0.w, r2.xyzw, cb2[46].xyzw
					mul r2.xyz, r1.xyzx, v4.xyzx
					dp3 r3.x, v2.xyzx, cb2[0].xyzx
					mul r1.xyz, r1.xyzx, cb0[2].xyzx
					mul r0.w, r0.w, r3.x
					mul r3.xyz, r0.wwww, r1.xyzx
					lt r0.w, l(0.415000), v1.x
					dp3 r1.x, cb2[0].xyzx, cb2[0].xyzx
					rsq r1.x, r1.x
					mad r0.xyz, cb2[0].xyzx, r1.xxxx, r0.xyzx
					dp3 r1.x, r0.xyzx, r0.xyzx
					rsq r1.x, r1.x
					mul r0.xyz, r0.xyzx, r1.xxxx
					dp3 r0.x, v2.xyzx, r0.xyzx
					max r0.x, r0.x, l(0.000000)
					log r0.x, r0.x
					mul r0.x, r0.x, cb0[4].x
					exp r0.x, r0.x
					lt r0.y, l(0.500000), r0.x
					mul r0.z, r0.x, l(1.500000)
					movc r0.x, r0.y, r0.z, r0.x
					min r0.x, r0.x, l(1.000000)
					movc r3.w, r0.w, r0.x, r1.w
					mov r2.w, l(0)
					add o0.xyzw, r2.xyzw, r3.xyzw
					ret 
					// Approximately 0 instruction slots used"
				}
			}
		}
		Pass {
			Name "FORWARD"
			LOD 200
			Tags { "IGNOREPROJECTOR" = "true" "LIGHTMODE" = "FORWARDADD" "QUEUE" = "Transparent" "RenderType" = "Transparent" }
			Blend SrcAlpha One, SrcAlpha One
			ColorMask RGB -1
			ZTest Less
			ZWrite Off
			GpuProgramID 102974
			Program "vp" {
				SubProgram "d3d11 " {
					Keywords { "POINT" }
					"!!vs_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyzw
					// TANGENT                  0   xyzw        1     NONE   float       
					// NORMAL                   0   xyz         2     NONE   float   xyz 
					// TEXCOORD                 0   xyzw        3     NONE   float   xy  
					// TEXCOORD                 1   xyzw        4     NONE   float       
					// TEXCOORD                 2   xyzw        5     NONE   float       
					// TEXCOORD                 3   xyzw        6     NONE   float       
					// COLOR                    0   xyzw        7     NONE   float       
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					// TEXCOORD                 1   xyz         2     NONE   float   xyz 
					// TEXCOORD                 2   xyz         3     NONE   float   xyz 
					// TEXCOORD                 3   xyz         4     NONE   float   xyz 
					//
					vs_4_0
					dcl_constantbuffer CB0[11], immediateIndexed
					dcl_constantbuffer CB1[7], immediateIndexed
					dcl_constantbuffer CB2[21], immediateIndexed
					dcl_input v0.xyzw
					dcl_input v2.xyz
					dcl_input v3.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xy
					dcl_output o2.xyz
					dcl_output o3.xyz
					dcl_output o4.xyz
					dcl_temps 3
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					add r1.xyzw, r0.xyzw, cb1[3].xyzw
					mul r2.xyzw, r1.yyyy, cb2[18].xyzw
					mad r2.xyzw, cb2[17].xyzw, r1.xxxx, r2.xyzw
					mad r2.xyzw, cb2[19].xyzw, r1.zzzz, r2.xyzw
					mad o0.xyzw, cb2[20].xyzw, r1.wwww, r2.xyzw
					mad o1.xy, v3.xyxx, cb0[10].xyxx, cb0[10].zwzz
					dp3 r1.x, v2.xyzx, cb1[4].xyzx
					dp3 r1.y, v2.xyzx, cb1[5].xyzx
					dp3 r1.z, v2.xyzx, cb1[6].xyzx
					dp3 r1.w, r1.xyzx, r1.xyzx
					rsq r1.w, r1.w
					mul o2.xyz, r1.wwww, r1.xyzx
					mad o3.xyz, cb1[3].xyzx, v0.wwww, r0.xyzx
					mad r0.xyzw, cb1[3].xyzw, v0.wwww, r0.xyzw
					mul r1.xyz, r0.yyyy, cb0[5].xyzx
					mad r1.xyz, cb0[4].xyzx, r0.xxxx, r1.xyzx
					mad r0.xyz, cb0[6].xyzx, r0.zzzz, r1.xyzx
					mad o4.xyz, cb0[7].xyzx, r0.wwww, r0.xyzx
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "DIRECTIONAL" }
					"!!vs_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyzw
					// TANGENT                  0   xyzw        1     NONE   float       
					// NORMAL                   0   xyz         2     NONE   float   xyz 
					// TEXCOORD                 0   xyzw        3     NONE   float   xy  
					// TEXCOORD                 1   xyzw        4     NONE   float       
					// TEXCOORD                 2   xyzw        5     NONE   float       
					// TEXCOORD                 3   xyzw        6     NONE   float       
					// COLOR                    0   xyzw        7     NONE   float       
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					// TEXCOORD                 1   xyz         2     NONE   float   xyz 
					// TEXCOORD                 2   xyz         3     NONE   float   xyz 
					//
					vs_4_0
					dcl_constantbuffer CB0[7], immediateIndexed
					dcl_constantbuffer CB1[7], immediateIndexed
					dcl_constantbuffer CB2[21], immediateIndexed
					dcl_input v0.xyzw
					dcl_input v2.xyz
					dcl_input v3.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xy
					dcl_output o2.xyz
					dcl_output o3.xyz
					dcl_temps 2
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					add r1.xyzw, r0.xyzw, cb1[3].xyzw
					mad o3.xyz, cb1[3].xyzx, v0.wwww, r0.xyzx
					mul r0.xyzw, r1.yyyy, cb2[18].xyzw
					mad r0.xyzw, cb2[17].xyzw, r1.xxxx, r0.xyzw
					mad r0.xyzw, cb2[19].xyzw, r1.zzzz, r0.xyzw
					mad o0.xyzw, cb2[20].xyzw, r1.wwww, r0.xyzw
					mad o1.xy, v3.xyxx, cb0[6].xyxx, cb0[6].zwzz
					dp3 r0.x, v2.xyzx, cb1[4].xyzx
					dp3 r0.y, v2.xyzx, cb1[5].xyzx
					dp3 r0.z, v2.xyzx, cb1[6].xyzx
					dp3 r0.w, r0.xyzx, r0.xyzx
					rsq r0.w, r0.w
					mul o2.xyz, r0.wwww, r0.xyzx
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "SPOT" }
					"!!vs_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyzw
					// TANGENT                  0   xyzw        1     NONE   float       
					// NORMAL                   0   xyz         2     NONE   float   xyz 
					// TEXCOORD                 0   xyzw        3     NONE   float   xy  
					// TEXCOORD                 1   xyzw        4     NONE   float       
					// TEXCOORD                 2   xyzw        5     NONE   float       
					// TEXCOORD                 3   xyzw        6     NONE   float       
					// COLOR                    0   xyzw        7     NONE   float       
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					// TEXCOORD                 1   xyz         2     NONE   float   xyz 
					// TEXCOORD                 2   xyz         3     NONE   float   xyz 
					// TEXCOORD                 3   xyzw        4     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[11], immediateIndexed
					dcl_constantbuffer CB1[7], immediateIndexed
					dcl_constantbuffer CB2[21], immediateIndexed
					dcl_input v0.xyzw
					dcl_input v2.xyz
					dcl_input v3.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xy
					dcl_output o2.xyz
					dcl_output o3.xyz
					dcl_output o4.xyzw
					dcl_temps 3
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					add r1.xyzw, r0.xyzw, cb1[3].xyzw
					mul r2.xyzw, r1.yyyy, cb2[18].xyzw
					mad r2.xyzw, cb2[17].xyzw, r1.xxxx, r2.xyzw
					mad r2.xyzw, cb2[19].xyzw, r1.zzzz, r2.xyzw
					mad o0.xyzw, cb2[20].xyzw, r1.wwww, r2.xyzw
					mad o1.xy, v3.xyxx, cb0[10].xyxx, cb0[10].zwzz
					dp3 r1.x, v2.xyzx, cb1[4].xyzx
					dp3 r1.y, v2.xyzx, cb1[5].xyzx
					dp3 r1.z, v2.xyzx, cb1[6].xyzx
					dp3 r1.w, r1.xyzx, r1.xyzx
					rsq r1.w, r1.w
					mul o2.xyz, r1.wwww, r1.xyzx
					mad o3.xyz, cb1[3].xyzx, v0.wwww, r0.xyzx
					mad r0.xyzw, cb1[3].xyzw, v0.wwww, r0.xyzw
					mul r1.xyzw, r0.yyyy, cb0[5].xyzw
					mad r1.xyzw, cb0[4].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb0[6].xyzw, r0.zzzz, r1.xyzw
					mad o4.xyzw, cb0[7].xyzw, r0.wwww, r1.xyzw
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "POINT_COOKIE" }
					"!!vs_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyzw
					// TANGENT                  0   xyzw        1     NONE   float       
					// NORMAL                   0   xyz         2     NONE   float   xyz 
					// TEXCOORD                 0   xyzw        3     NONE   float   xy  
					// TEXCOORD                 1   xyzw        4     NONE   float       
					// TEXCOORD                 2   xyzw        5     NONE   float       
					// TEXCOORD                 3   xyzw        6     NONE   float       
					// COLOR                    0   xyzw        7     NONE   float       
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					// TEXCOORD                 1   xyz         2     NONE   float   xyz 
					// TEXCOORD                 2   xyz         3     NONE   float   xyz 
					// TEXCOORD                 3   xyz         4     NONE   float   xyz 
					//
					vs_4_0
					dcl_constantbuffer CB0[11], immediateIndexed
					dcl_constantbuffer CB1[7], immediateIndexed
					dcl_constantbuffer CB2[21], immediateIndexed
					dcl_input v0.xyzw
					dcl_input v2.xyz
					dcl_input v3.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xy
					dcl_output o2.xyz
					dcl_output o3.xyz
					dcl_output o4.xyz
					dcl_temps 3
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					add r1.xyzw, r0.xyzw, cb1[3].xyzw
					mul r2.xyzw, r1.yyyy, cb2[18].xyzw
					mad r2.xyzw, cb2[17].xyzw, r1.xxxx, r2.xyzw
					mad r2.xyzw, cb2[19].xyzw, r1.zzzz, r2.xyzw
					mad o0.xyzw, cb2[20].xyzw, r1.wwww, r2.xyzw
					mad o1.xy, v3.xyxx, cb0[10].xyxx, cb0[10].zwzz
					dp3 r1.x, v2.xyzx, cb1[4].xyzx
					dp3 r1.y, v2.xyzx, cb1[5].xyzx
					dp3 r1.z, v2.xyzx, cb1[6].xyzx
					dp3 r1.w, r1.xyzx, r1.xyzx
					rsq r1.w, r1.w
					mul o2.xyz, r1.wwww, r1.xyzx
					mad o3.xyz, cb1[3].xyzx, v0.wwww, r0.xyzx
					mad r0.xyzw, cb1[3].xyzw, v0.wwww, r0.xyzw
					mul r1.xyz, r0.yyyy, cb0[5].xyzx
					mad r1.xyz, cb0[4].xyzx, r0.xxxx, r1.xyzx
					mad r0.xyz, cb0[6].xyzx, r0.zzzz, r1.xyzx
					mad o4.xyz, cb0[7].xyzx, r0.wwww, r0.xyzx
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "DIRECTIONAL_COOKIE" }
					"!!vs_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyzw
					// TANGENT                  0   xyzw        1     NONE   float       
					// NORMAL                   0   xyz         2     NONE   float   xyz 
					// TEXCOORD                 0   xyzw        3     NONE   float   xy  
					// TEXCOORD                 1   xyzw        4     NONE   float       
					// TEXCOORD                 2   xyzw        5     NONE   float       
					// TEXCOORD                 3   xyzw        6     NONE   float       
					// COLOR                    0   xyzw        7     NONE   float       
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					// TEXCOORD                 3     zw        1     NONE   float     zw
					// TEXCOORD                 1   xyz         2     NONE   float   xyz 
					// TEXCOORD                 2   xyz         3     NONE   float   xyz 
					//
					vs_4_0
					dcl_constantbuffer CB0[11], immediateIndexed
					dcl_constantbuffer CB1[7], immediateIndexed
					dcl_constantbuffer CB2[21], immediateIndexed
					dcl_input v0.xyzw
					dcl_input v2.xyz
					dcl_input v3.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xy
					dcl_output o1.zw
					dcl_output o2.xyz
					dcl_output o3.xyz
					dcl_temps 3
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					add r1.xyzw, r0.xyzw, cb1[3].xyzw
					mul r2.xyzw, r1.yyyy, cb2[18].xyzw
					mad r2.xyzw, cb2[17].xyzw, r1.xxxx, r2.xyzw
					mad r2.xyzw, cb2[19].xyzw, r1.zzzz, r2.xyzw
					mad o0.xyzw, cb2[20].xyzw, r1.wwww, r2.xyzw
					mad r1.xyzw, cb1[3].xyzw, v0.wwww, r0.xyzw
					mad o3.xyz, cb1[3].xyzx, v0.wwww, r0.xyzx
					mul r0.xy, r1.yyyy, cb0[5].xyxx
					mad r0.xy, cb0[4].xyxx, r1.xxxx, r0.xyxx
					mad r0.xy, cb0[6].xyxx, r1.zzzz, r0.xyxx
					mad o1.zw, cb0[7].xxxy, r1.wwww, r0.xxxy
					mad o1.xy, v3.xyxx, cb0[10].xyxx, cb0[10].zwzz
					dp3 r0.x, v2.xyzx, cb1[4].xyzx
					dp3 r0.y, v2.xyzx, cb1[5].xyzx
					dp3 r0.z, v2.xyzx, cb1[6].xyzx
					dp3 r0.w, r0.xyzx, r0.xyzx
					rsq r0.w, r0.w
					mul o2.xyz, r0.wwww, r0.xyzx
					ret 
					// Approximately 0 instruction slots used"
				}
			}
			Program "fp" {
				SubProgram "d3d11 " {
					Keywords { "POINT" }
					"!!ps_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					// TEXCOORD                 1   xyz         2     NONE   float   xyz 
					// TEXCOORD                 2   xyz         3     NONE   float   xyz 
					// TEXCOORD                 3   xyz         4     NONE   float       
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[10], immediateIndexed
					dcl_constantbuffer CB1[5], immediateIndexed
					dcl_constantbuffer CB2[47], immediateIndexed
					dcl_constantbuffer CB3[7], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_sampler s1, mode_default
					dcl_sampler s2, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_resource_texture2d (float,float,float,float) t1
					dcl_resource_texture3d (float,float,float,float) t2
					dcl_input_ps linear v1.xy
					dcl_input_ps linear v2.xyz
					dcl_input_ps linear v3.xyz
					dcl_output o0.xyzw
					dcl_temps 5
					add r0.xyz, -v3.xyzx, cb2[0].xyzx
					dp3 r0.w, r0.xyzx, r0.xyzx
					rsq r0.w, r0.w
					mul r0.xyz, r0.wwww, r0.xyzx
					add r1.xyz, -v3.xyzx, cb1[4].xyzx
					dp3 r0.w, r1.xyzx, r1.xyzx
					rsq r0.w, r0.w
					sample r2.xyzw, v1.xyxx, t0.xyzw, s2
					mul r2.xyzw, r2.xyzw, cb0[9].xyzw
					mul r3.xyz, v3.yyyy, cb0[5].xyzx
					mad r3.xyz, cb0[4].xyzx, v3.xxxx, r3.xyzx
					mad r3.xyz, cb0[6].xyzx, v3.zzzz, r3.xyzx
					add r3.xyz, r3.xyzx, cb0[7].xyzx
					eq r1.w, cb3[0].x, l(1.000000)
					if_nz r1.w
					  eq r1.w, cb3[0].y, l(1.000000)
					  mul r4.xyz, v3.yyyy, cb3[2].xyzx
					  mad r4.xyz, cb3[1].xyzx, v3.xxxx, r4.xyzx
					  mad r4.xyz, cb3[3].xyzx, v3.zzzz, r4.xyzx
					  add r4.xyz, r4.xyzx, cb3[4].xyzx
					  movc r4.xyz, r1.wwww, r4.xyzx, v3.xyzx
					  add r4.xyz, r4.xyzx, -cb3[6].xyzx
					  mul r4.yzw, r4.xxyz, cb3[5].xxyz
					  mad r1.w, r4.y, l(0.250000), l(0.750000)
					  mad r3.w, cb3[0].z, l(0.500000), l(0.750000)
					  max r4.x, r1.w, r3.w
					  sample r4.xyzw, r4.xzwx, t2.xyzw, s0
					else 
					  mov r4.xyzw, l(1.000000,1.000000,1.000000,1.000000)
					endif 
					dp4_sat r1.w, r4.xyzw, cb2[46].xyzw
					dp3 r3.x, r3.xyzx, r3.xyzx
					sample r3.xyzw, r3.xxxx, t1.xyzw, s1
					mul r1.w, r1.w, r3.x
					dp3 r3.x, v2.xyzx, r0.xyzx
					mul r2.xyz, r2.xyzx, cb0[2].xyzx
					mul r1.w, r1.w, r3.x
					mul o0.xyz, r1.wwww, r2.xyzx
					lt r1.w, l(0.415000), v1.x
					mad r0.xyz, r1.xyzx, r0.wwww, r0.xyzx
					dp3 r0.w, r0.xyzx, r0.xyzx
					rsq r0.w, r0.w
					mul r0.xyz, r0.wwww, r0.xyzx
					dp3 r0.x, v2.xyzx, r0.xyzx
					max r0.x, r0.x, l(0.000000)
					log r0.x, r0.x
					mul r0.x, r0.x, cb0[8].x
					exp r0.x, r0.x
					lt r0.y, l(0.500000), r0.x
					mul r0.z, r0.x, l(1.500000)
					movc r0.x, r0.y, r0.z, r0.x
					min r0.x, r0.x, l(1.000000)
					movc o0.w, r1.w, r0.x, r2.w
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "DIRECTIONAL" }
					"!!ps_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					// TEXCOORD                 1   xyz         2     NONE   float   xyz 
					// TEXCOORD                 2   xyz         3     NONE   float   xyz 
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[6], immediateIndexed
					dcl_constantbuffer CB1[5], immediateIndexed
					dcl_constantbuffer CB2[47], immediateIndexed
					dcl_constantbuffer CB3[7], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_sampler s1, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_resource_texture3d (float,float,float,float) t1
					dcl_input_ps linear v1.xy
					dcl_input_ps linear v2.xyz
					dcl_input_ps linear v3.xyz
					dcl_output o0.xyzw
					dcl_temps 3
					add r0.xyz, -v3.xyzx, cb1[4].xyzx
					dp3 r0.w, r0.xyzx, r0.xyzx
					rsq r0.w, r0.w
					mul r0.xyz, r0.wwww, r0.xyzx
					sample r1.xyzw, v1.xyxx, t0.xyzw, s1
					mul r1.xyzw, r1.xyzw, cb0[5].xyzw
					eq r0.w, cb3[0].x, l(1.000000)
					if_nz r0.w
					  eq r0.w, cb3[0].y, l(1.000000)
					  mul r2.xyz, v3.yyyy, cb3[2].xyzx
					  mad r2.xyz, cb3[1].xyzx, v3.xxxx, r2.xyzx
					  mad r2.xyz, cb3[3].xyzx, v3.zzzz, r2.xyzx
					  add r2.xyz, r2.xyzx, cb3[4].xyzx
					  movc r2.xyz, r0.wwww, r2.xyzx, v3.xyzx
					  add r2.xyz, r2.xyzx, -cb3[6].xyzx
					  mul r2.yzw, r2.xxyz, cb3[5].xxyz
					  mad r0.w, r2.y, l(0.250000), l(0.750000)
					  mad r2.y, cb3[0].z, l(0.500000), l(0.750000)
					  max r2.x, r0.w, r2.y
					  sample r2.xyzw, r2.xzwx, t1.xyzw, s0
					else 
					  mov r2.xyzw, l(1.000000,1.000000,1.000000,1.000000)
					endif 
					dp4_sat r0.w, r2.xyzw, cb2[46].xyzw
					dp3 r2.x, v2.xyzx, cb2[0].xyzx
					mul r1.xyz, r1.xyzx, cb0[2].xyzx
					mul r0.w, r0.w, r2.x
					mul o0.xyz, r0.wwww, r1.xyzx
					lt r0.w, l(0.415000), v1.x
					dp3 r1.x, cb2[0].xyzx, cb2[0].xyzx
					rsq r1.x, r1.x
					mad r0.xyz, cb2[0].xyzx, r1.xxxx, r0.xyzx
					dp3 r1.x, r0.xyzx, r0.xyzx
					rsq r1.x, r1.x
					mul r0.xyz, r0.xyzx, r1.xxxx
					dp3 r0.x, v2.xyzx, r0.xyzx
					max r0.x, r0.x, l(0.000000)
					log r0.x, r0.x
					mul r0.x, r0.x, cb0[4].x
					exp r0.x, r0.x
					lt r0.y, l(0.500000), r0.x
					mul r0.z, r0.x, l(1.500000)
					movc r0.x, r0.y, r0.z, r0.x
					min r0.x, r0.x, l(1.000000)
					movc o0.w, r0.w, r0.x, r1.w
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "SPOT" }
					"!!ps_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					// TEXCOORD                 1   xyz         2     NONE   float   xyz 
					// TEXCOORD                 2   xyz         3     NONE   float   xyz 
					// TEXCOORD                 3   xyzw        4     NONE   float       
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[10], immediateIndexed
					dcl_constantbuffer CB1[5], immediateIndexed
					dcl_constantbuffer CB2[47], immediateIndexed
					dcl_constantbuffer CB3[7], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_sampler s1, mode_default
					dcl_sampler s2, mode_default
					dcl_sampler s3, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_resource_texture2d (float,float,float,float) t1
					dcl_resource_texture2d (float,float,float,float) t2
					dcl_resource_texture3d (float,float,float,float) t3
					dcl_input_ps linear v1.xy
					dcl_input_ps linear v2.xyz
					dcl_input_ps linear v3.xyz
					dcl_output o0.xyzw
					dcl_temps 6
					add r0.xyz, -v3.xyzx, cb2[0].xyzx
					dp3 r0.w, r0.xyzx, r0.xyzx
					rsq r0.w, r0.w
					mul r0.xyz, r0.wwww, r0.xyzx
					add r1.xyz, -v3.xyzx, cb1[4].xyzx
					dp3 r0.w, r1.xyzx, r1.xyzx
					rsq r0.w, r0.w
					sample r2.xyzw, v1.xyxx, t0.xyzw, s3
					mul r2.xyzw, r2.xyzw, cb0[9].xyzw
					mul r3.xyzw, v3.yyyy, cb0[5].xyzw
					mad r3.xyzw, cb0[4].xyzw, v3.xxxx, r3.xyzw
					mad r3.xyzw, cb0[6].xyzw, v3.zzzz, r3.xyzw
					add r3.xyzw, r3.xyzw, cb0[7].xyzw
					eq r1.w, cb3[0].x, l(1.000000)
					if_nz r1.w
					  eq r1.w, cb3[0].y, l(1.000000)
					  mul r4.xyz, v3.yyyy, cb3[2].xyzx
					  mad r4.xyz, cb3[1].xyzx, v3.xxxx, r4.xyzx
					  mad r4.xyz, cb3[3].xyzx, v3.zzzz, r4.xyzx
					  add r4.xyz, r4.xyzx, cb3[4].xyzx
					  movc r4.xyz, r1.wwww, r4.xyzx, v3.xyzx
					  add r4.xyz, r4.xyzx, -cb3[6].xyzx
					  mul r4.yzw, r4.xxyz, cb3[5].xxyz
					  mad r1.w, r4.y, l(0.250000), l(0.750000)
					  mad r4.y, cb3[0].z, l(0.500000), l(0.750000)
					  max r4.x, r1.w, r4.y
					  sample r4.xyzw, r4.xzwx, t3.xyzw, s0
					else 
					  mov r4.xyzw, l(1.000000,1.000000,1.000000,1.000000)
					endif 
					dp4_sat r1.w, r4.xyzw, cb2[46].xyzw
					lt r4.x, l(0.000000), r3.z
					and r4.x, r4.x, l(0x3f800000)
					div r4.yz, r3.xxyx, r3.wwww
					add r4.yz, r4.yyzy, l(0.000000, 0.500000, 0.500000, 0.000000)
					sample r5.xyzw, r4.yzyy, t1.xyzw, s1
					mul r3.w, r4.x, r5.w
					dp3 r3.x, r3.xyzx, r3.xyzx
					sample r4.xyzw, r3.xxxx, t2.xyzw, s2
					mul r3.x, r3.w, r4.x
					mul r1.w, r1.w, r3.x
					dp3 r3.x, v2.xyzx, r0.xyzx
					mul r2.xyz, r2.xyzx, cb0[2].xyzx
					mul r1.w, r1.w, r3.x
					mul o0.xyz, r1.wwww, r2.xyzx
					lt r1.w, l(0.415000), v1.x
					mad r0.xyz, r1.xyzx, r0.wwww, r0.xyzx
					dp3 r0.w, r0.xyzx, r0.xyzx
					rsq r0.w, r0.w
					mul r0.xyz, r0.wwww, r0.xyzx
					dp3 r0.x, v2.xyzx, r0.xyzx
					max r0.x, r0.x, l(0.000000)
					log r0.x, r0.x
					mul r0.x, r0.x, cb0[8].x
					exp r0.x, r0.x
					lt r0.y, l(0.500000), r0.x
					mul r0.z, r0.x, l(1.500000)
					movc r0.x, r0.y, r0.z, r0.x
					min r0.x, r0.x, l(1.000000)
					movc o0.w, r1.w, r0.x, r2.w
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "POINT_COOKIE" }
					"!!ps_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					// TEXCOORD                 1   xyz         2     NONE   float   xyz 
					// TEXCOORD                 2   xyz         3     NONE   float   xyz 
					// TEXCOORD                 3   xyz         4     NONE   float       
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[10], immediateIndexed
					dcl_constantbuffer CB1[5], immediateIndexed
					dcl_constantbuffer CB2[47], immediateIndexed
					dcl_constantbuffer CB3[7], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_sampler s1, mode_default
					dcl_sampler s2, mode_default
					dcl_sampler s3, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_resource_texture2d (float,float,float,float) t1
					dcl_resource_texturecube (float,float,float,float) t2
					dcl_resource_texture3d (float,float,float,float) t3
					dcl_input_ps linear v1.xy
					dcl_input_ps linear v2.xyz
					dcl_input_ps linear v3.xyz
					dcl_output o0.xyzw
					dcl_temps 5
					add r0.xyz, -v3.xyzx, cb2[0].xyzx
					dp3 r0.w, r0.xyzx, r0.xyzx
					rsq r0.w, r0.w
					mul r0.xyz, r0.wwww, r0.xyzx
					add r1.xyz, -v3.xyzx, cb1[4].xyzx
					dp3 r0.w, r1.xyzx, r1.xyzx
					rsq r0.w, r0.w
					sample r2.xyzw, v1.xyxx, t0.xyzw, s3
					mul r2.xyzw, r2.xyzw, cb0[9].xyzw
					mul r3.xyz, v3.yyyy, cb0[5].xyzx
					mad r3.xyz, cb0[4].xyzx, v3.xxxx, r3.xyzx
					mad r3.xyz, cb0[6].xyzx, v3.zzzz, r3.xyzx
					add r3.xyz, r3.xyzx, cb0[7].xyzx
					eq r1.w, cb3[0].x, l(1.000000)
					if_nz r1.w
					  eq r1.w, cb3[0].y, l(1.000000)
					  mul r4.xyz, v3.yyyy, cb3[2].xyzx
					  mad r4.xyz, cb3[1].xyzx, v3.xxxx, r4.xyzx
					  mad r4.xyz, cb3[3].xyzx, v3.zzzz, r4.xyzx
					  add r4.xyz, r4.xyzx, cb3[4].xyzx
					  movc r4.xyz, r1.wwww, r4.xyzx, v3.xyzx
					  add r4.xyz, r4.xyzx, -cb3[6].xyzx
					  mul r4.yzw, r4.xxyz, cb3[5].xxyz
					  mad r1.w, r4.y, l(0.250000), l(0.750000)
					  mad r3.w, cb3[0].z, l(0.500000), l(0.750000)
					  max r4.x, r1.w, r3.w
					  sample r4.xyzw, r4.xzwx, t3.xyzw, s0
					else 
					  mov r4.xyzw, l(1.000000,1.000000,1.000000,1.000000)
					endif 
					dp4_sat r1.w, r4.xyzw, cb2[46].xyzw
					dp3 r3.w, r3.xyzx, r3.xyzx
					sample r4.xyzw, r3.wwww, t1.xyzw, s2
					sample r3.xyzw, r3.xyzx, t2.xyzw, s1
					mul r3.x, r3.w, r4.x
					mul r1.w, r1.w, r3.x
					dp3 r3.x, v2.xyzx, r0.xyzx
					mul r2.xyz, r2.xyzx, cb0[2].xyzx
					mul r1.w, r1.w, r3.x
					mul o0.xyz, r1.wwww, r2.xyzx
					lt r1.w, l(0.415000), v1.x
					mad r0.xyz, r1.xyzx, r0.wwww, r0.xyzx
					dp3 r0.w, r0.xyzx, r0.xyzx
					rsq r0.w, r0.w
					mul r0.xyz, r0.wwww, r0.xyzx
					dp3 r0.x, v2.xyzx, r0.xyzx
					max r0.x, r0.x, l(0.000000)
					log r0.x, r0.x
					mul r0.x, r0.x, cb0[8].x
					exp r0.x, r0.x
					lt r0.y, l(0.500000), r0.x
					mul r0.z, r0.x, l(1.500000)
					movc r0.x, r0.y, r0.z, r0.x
					min r0.x, r0.x, l(1.000000)
					movc o0.w, r1.w, r0.x, r2.w
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "DIRECTIONAL_COOKIE" }
					"!!ps_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					// TEXCOORD                 3     zw        1     NONE   float       
					// TEXCOORD                 1   xyz         2     NONE   float   xyz 
					// TEXCOORD                 2   xyz         3     NONE   float   xyz 
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[10], immediateIndexed
					dcl_constantbuffer CB1[5], immediateIndexed
					dcl_constantbuffer CB2[47], immediateIndexed
					dcl_constantbuffer CB3[7], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_sampler s1, mode_default
					dcl_sampler s2, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_resource_texture2d (float,float,float,float) t1
					dcl_resource_texture3d (float,float,float,float) t2
					dcl_input_ps linear v1.xy
					dcl_input_ps linear v2.xyz
					dcl_input_ps linear v3.xyz
					dcl_output o0.xyzw
					dcl_temps 4
					add r0.xyz, -v3.xyzx, cb1[4].xyzx
					dp3 r0.w, r0.xyzx, r0.xyzx
					rsq r0.w, r0.w
					mul r0.xyz, r0.wwww, r0.xyzx
					sample r1.xyzw, v1.xyxx, t0.xyzw, s2
					mul r1.xyzw, r1.xyzw, cb0[9].xyzw
					mul r2.xy, v3.yyyy, cb0[5].xyxx
					mad r2.xy, cb0[4].xyxx, v3.xxxx, r2.xyxx
					mad r2.xy, cb0[6].xyxx, v3.zzzz, r2.xyxx
					add r2.xy, r2.xyxx, cb0[7].xyxx
					eq r0.w, cb3[0].x, l(1.000000)
					if_nz r0.w
					  eq r0.w, cb3[0].y, l(1.000000)
					  mul r3.xyz, v3.yyyy, cb3[2].xyzx
					  mad r3.xyz, cb3[1].xyzx, v3.xxxx, r3.xyzx
					  mad r3.xyz, cb3[3].xyzx, v3.zzzz, r3.xyzx
					  add r3.xyz, r3.xyzx, cb3[4].xyzx
					  movc r3.xyz, r0.wwww, r3.xyzx, v3.xyzx
					  add r3.xyz, r3.xyzx, -cb3[6].xyzx
					  mul r3.yzw, r3.xxyz, cb3[5].xxyz
					  mad r0.w, r3.y, l(0.250000), l(0.750000)
					  mad r2.z, cb3[0].z, l(0.500000), l(0.750000)
					  max r3.x, r0.w, r2.z
					  sample r3.xyzw, r3.xzwx, t2.xyzw, s0
					else 
					  mov r3.xyzw, l(1.000000,1.000000,1.000000,1.000000)
					endif 
					dp4_sat r0.w, r3.xyzw, cb2[46].xyzw
					sample r2.xyzw, r2.xyxx, t1.xyzw, s1
					mul r0.w, r0.w, r2.w
					dp3 r2.x, v2.xyzx, cb2[0].xyzx
					mul r1.xyz, r1.xyzx, cb0[2].xyzx
					mul r0.w, r0.w, r2.x
					mul o0.xyz, r0.wwww, r1.xyzx
					lt r0.w, l(0.415000), v1.x
					dp3 r1.x, cb2[0].xyzx, cb2[0].xyzx
					rsq r1.x, r1.x
					mad r0.xyz, cb2[0].xyzx, r1.xxxx, r0.xyzx
					dp3 r1.x, r0.xyzx, r0.xyzx
					rsq r1.x, r1.x
					mul r0.xyz, r0.xyzx, r1.xxxx
					dp3 r0.x, v2.xyzx, r0.xyzx
					max r0.x, r0.x, l(0.000000)
					log r0.x, r0.x
					mul r0.x, r0.x, cb0[8].x
					exp r0.x, r0.x
					lt r0.y, l(0.500000), r0.x
					mul r0.z, r0.x, l(1.500000)
					movc r0.x, r0.y, r0.z, r0.x
					min r0.x, r0.x, l(1.000000)
					movc o0.w, r0.w, r0.x, r1.w
					ret 
					// Approximately 0 instruction slots used"
				}
			}
		}
	}
	Fallback "Diffuse"
}